// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

// StateClosed - The deploy request will be updated to this state
type StateClosed string

const (
	StateClosedClosed StateClosed = "closed"
)

func (e StateClosed) ToPointer() *StateClosed {
	return &e
}
func (e *StateClosed) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "closed":
		*e = StateClosed(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StateClosed: %v", v)
	}
}

type CloseDeployRequestRequestBody struct {
	// The deploy request will be updated to this state
	State *StateClosed `json:"state,omitzero"`
}

func (c *CloseDeployRequestRequestBody) GetState() *StateClosed {
	if c == nil {
		return nil
	}
	return c.State
}

type CloseDeployRequestRequest struct {
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number int64                          `pathParam:"style=simple,explode=false,name=number"`
	Body   *CloseDeployRequestRequestBody `request:"mediaType=application/json"`
}

func (c CloseDeployRequestRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CloseDeployRequestRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CloseDeployRequestRequest) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CloseDeployRequestRequest) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CloseDeployRequestRequest) GetNumber() int64 {
	if c == nil {
		return 0
	}
	return c.Number
}

func (c *CloseDeployRequestRequest) GetBody() *CloseDeployRequestRequestBody {
	if c == nil {
		return nil
	}
	return c.Body
}

type CloseDeployRequestActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CloseDeployRequestActor) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestActor) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CloseDeployRequestActor) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

type CloseDeployRequestClosedBy struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CloseDeployRequestClosedBy) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestClosedBy) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CloseDeployRequestClosedBy) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

type CloseDeployRequestBranchDeletedBy struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CloseDeployRequestBranchDeletedBy) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestBranchDeletedBy) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CloseDeployRequestBranchDeletedBy) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

// CloseDeployRequestStateResponseBody - Whether the deploy request is open or closed
type CloseDeployRequestStateResponseBody string

const (
	CloseDeployRequestStateResponseBodyOpen   CloseDeployRequestStateResponseBody = "open"
	CloseDeployRequestStateResponseBodyClosed CloseDeployRequestStateResponseBody = "closed"
)

func (e CloseDeployRequestStateResponseBody) ToPointer() *CloseDeployRequestStateResponseBody {
	return &e
}
func (e *CloseDeployRequestStateResponseBody) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "open":
		fallthrough
	case "closed":
		*e = CloseDeployRequestStateResponseBody(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseDeployRequestStateResponseBody: %v", v)
	}
}

// CloseDeployRequestDeploymentState1 - The deployment state of the deploy request
type CloseDeployRequestDeploymentState1 string

const (
	CloseDeployRequestDeploymentState1Pending                 CloseDeployRequestDeploymentState1 = "pending"
	CloseDeployRequestDeploymentState1Ready                   CloseDeployRequestDeploymentState1 = "ready"
	CloseDeployRequestDeploymentState1NoChanges               CloseDeployRequestDeploymentState1 = "no_changes"
	CloseDeployRequestDeploymentState1Queued                  CloseDeployRequestDeploymentState1 = "queued"
	CloseDeployRequestDeploymentState1Submitting              CloseDeployRequestDeploymentState1 = "submitting"
	CloseDeployRequestDeploymentState1InProgress              CloseDeployRequestDeploymentState1 = "in_progress"
	CloseDeployRequestDeploymentState1PendingCutover          CloseDeployRequestDeploymentState1 = "pending_cutover"
	CloseDeployRequestDeploymentState1InProgressVschema       CloseDeployRequestDeploymentState1 = "in_progress_vschema"
	CloseDeployRequestDeploymentState1InProgressCancel        CloseDeployRequestDeploymentState1 = "in_progress_cancel"
	CloseDeployRequestDeploymentState1InProgressCutover       CloseDeployRequestDeploymentState1 = "in_progress_cutover"
	CloseDeployRequestDeploymentState1Complete                CloseDeployRequestDeploymentState1 = "complete"
	CloseDeployRequestDeploymentState1CompleteCancel          CloseDeployRequestDeploymentState1 = "complete_cancel"
	CloseDeployRequestDeploymentState1CompleteError           CloseDeployRequestDeploymentState1 = "complete_error"
	CloseDeployRequestDeploymentState1CompletePendingRevert   CloseDeployRequestDeploymentState1 = "complete_pending_revert"
	CloseDeployRequestDeploymentState1InProgressRevert        CloseDeployRequestDeploymentState1 = "in_progress_revert"
	CloseDeployRequestDeploymentState1InProgressRevertVschema CloseDeployRequestDeploymentState1 = "in_progress_revert_vschema"
	CloseDeployRequestDeploymentState1CompleteRevert          CloseDeployRequestDeploymentState1 = "complete_revert"
	CloseDeployRequestDeploymentState1CompleteRevertError     CloseDeployRequestDeploymentState1 = "complete_revert_error"
	CloseDeployRequestDeploymentState1Cancelled               CloseDeployRequestDeploymentState1 = "cancelled"
	CloseDeployRequestDeploymentState1Error                   CloseDeployRequestDeploymentState1 = "error"
)

func (e CloseDeployRequestDeploymentState1) ToPointer() *CloseDeployRequestDeploymentState1 {
	return &e
}
func (e *CloseDeployRequestDeploymentState1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "ready":
		fallthrough
	case "no_changes":
		fallthrough
	case "queued":
		fallthrough
	case "submitting":
		fallthrough
	case "in_progress":
		fallthrough
	case "pending_cutover":
		fallthrough
	case "in_progress_vschema":
		fallthrough
	case "in_progress_cancel":
		fallthrough
	case "in_progress_cutover":
		fallthrough
	case "complete":
		fallthrough
	case "complete_cancel":
		fallthrough
	case "complete_error":
		fallthrough
	case "complete_pending_revert":
		fallthrough
	case "in_progress_revert":
		fallthrough
	case "in_progress_revert_vschema":
		fallthrough
	case "complete_revert":
		fallthrough
	case "complete_revert_error":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = CloseDeployRequestDeploymentState1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseDeployRequestDeploymentState1: %v", v)
	}
}

// CloseDeployRequestDeploymentState2 - The state the deployment is in
type CloseDeployRequestDeploymentState2 string

const (
	CloseDeployRequestDeploymentState2Pending                 CloseDeployRequestDeploymentState2 = "pending"
	CloseDeployRequestDeploymentState2Ready                   CloseDeployRequestDeploymentState2 = "ready"
	CloseDeployRequestDeploymentState2NoChanges               CloseDeployRequestDeploymentState2 = "no_changes"
	CloseDeployRequestDeploymentState2Queued                  CloseDeployRequestDeploymentState2 = "queued"
	CloseDeployRequestDeploymentState2Submitting              CloseDeployRequestDeploymentState2 = "submitting"
	CloseDeployRequestDeploymentState2InProgress              CloseDeployRequestDeploymentState2 = "in_progress"
	CloseDeployRequestDeploymentState2PendingCutover          CloseDeployRequestDeploymentState2 = "pending_cutover"
	CloseDeployRequestDeploymentState2InProgressVschema       CloseDeployRequestDeploymentState2 = "in_progress_vschema"
	CloseDeployRequestDeploymentState2InProgressCancel        CloseDeployRequestDeploymentState2 = "in_progress_cancel"
	CloseDeployRequestDeploymentState2InProgressCutover       CloseDeployRequestDeploymentState2 = "in_progress_cutover"
	CloseDeployRequestDeploymentState2Complete                CloseDeployRequestDeploymentState2 = "complete"
	CloseDeployRequestDeploymentState2CompleteCancel          CloseDeployRequestDeploymentState2 = "complete_cancel"
	CloseDeployRequestDeploymentState2CompleteError           CloseDeployRequestDeploymentState2 = "complete_error"
	CloseDeployRequestDeploymentState2CompletePendingRevert   CloseDeployRequestDeploymentState2 = "complete_pending_revert"
	CloseDeployRequestDeploymentState2InProgressRevert        CloseDeployRequestDeploymentState2 = "in_progress_revert"
	CloseDeployRequestDeploymentState2InProgressRevertVschema CloseDeployRequestDeploymentState2 = "in_progress_revert_vschema"
	CloseDeployRequestDeploymentState2CompleteRevert          CloseDeployRequestDeploymentState2 = "complete_revert"
	CloseDeployRequestDeploymentState2CompleteRevertError     CloseDeployRequestDeploymentState2 = "complete_revert_error"
	CloseDeployRequestDeploymentState2Cancelled               CloseDeployRequestDeploymentState2 = "cancelled"
	CloseDeployRequestDeploymentState2Error                   CloseDeployRequestDeploymentState2 = "error"
)

func (e CloseDeployRequestDeploymentState2) ToPointer() *CloseDeployRequestDeploymentState2 {
	return &e
}
func (e *CloseDeployRequestDeploymentState2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "ready":
		fallthrough
	case "no_changes":
		fallthrough
	case "queued":
		fallthrough
	case "submitting":
		fallthrough
	case "in_progress":
		fallthrough
	case "pending_cutover":
		fallthrough
	case "in_progress_vschema":
		fallthrough
	case "in_progress_cancel":
		fallthrough
	case "in_progress_cutover":
		fallthrough
	case "complete":
		fallthrough
	case "complete_cancel":
		fallthrough
	case "complete_error":
		fallthrough
	case "complete_pending_revert":
		fallthrough
	case "in_progress_revert":
		fallthrough
	case "in_progress_revert_vschema":
		fallthrough
	case "complete_revert":
		fallthrough
	case "complete_revert_error":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = CloseDeployRequestDeploymentState2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseDeployRequestDeploymentState2: %v", v)
	}
}

// CloseDeployRequestDeployOperationState - The state of the deploy operation
type CloseDeployRequestDeployOperationState string

const (
	CloseDeployRequestDeployOperationStatePending    CloseDeployRequestDeployOperationState = "pending"
	CloseDeployRequestDeployOperationStateQueued     CloseDeployRequestDeployOperationState = "queued"
	CloseDeployRequestDeployOperationStateInProgress CloseDeployRequestDeployOperationState = "in_progress"
	CloseDeployRequestDeployOperationStateComplete   CloseDeployRequestDeployOperationState = "complete"
	CloseDeployRequestDeployOperationStateCancelled  CloseDeployRequestDeployOperationState = "cancelled"
	CloseDeployRequestDeployOperationStateError      CloseDeployRequestDeployOperationState = "error"
)

func (e CloseDeployRequestDeployOperationState) ToPointer() *CloseDeployRequestDeployOperationState {
	return &e
}
func (e *CloseDeployRequestDeployOperationState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "queued":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = CloseDeployRequestDeployOperationState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseDeployRequestDeployOperationState: %v", v)
	}
}

type CloseDeployRequestDeployOperation struct {
	// The ID for the deploy operation
	ID string `json:"id"`
	// The state of the deploy operation
	State CloseDeployRequestDeployOperationState `json:"state"`
	// The keyspace modified by the deploy operation
	KeyspaceName string `json:"keyspace_name"`
	// The name of the table modifed by the deploy operation
	TableName string `json:"table_name"`
	// The operation name of the deploy operation
	OperationName string `json:"operation_name"`
	// The estimated seconds until completion for the deploy operation
	EtaSeconds float64 `json:"eta_seconds"`
	// The percent completion for the deploy operation
	ProgressPercentage float64 `json:"progress_percentage"`
	// A link to documentation explaining the deploy error, if present
	DeployErrorDocsURL string `json:"deploy_error_docs_url"`
	// The DDL statement for the deploy operation
	DdlStatement string `json:"ddl_statement"`
	// A syntax-highlighted DDL statement for the deploy operation
	SyntaxHighlightedDdl string `json:"syntax_highlighted_ddl"`
	// When the deploy operation was created
	CreatedAt string `json:"created_at"`
	// When the deploy operation was last updated
	UpdatedAt string `json:"updated_at"`
	// When the deploy operation was last throttled
	ThrottledAt string `json:"throttled_at"`
	// Whether or not the deploy operation is capable of dropping data
	CanDropData bool `json:"can_drop_data"`
	// Whether or not the table modified by the deploy operation is currently locked
	TableLocked bool `json:"table_locked"`
	// Whether or not the table modified by the deploy operation was recently used
	TableRecentlyUsed bool `json:"table_recently_used"`
	// When the table modified by the deploy operation was last used
	TableRecentlyUsedAt string `json:"table_recently_used_at"`
	// Names of foreign keys removed by this operation
	RemovedForeignKeyNames []string `json:"removed_foreign_key_names"`
	// Deploy errors for the deploy operation
	DeployErrors string `json:"deploy_errors"`
}

func (c *CloseDeployRequestDeployOperation) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestDeployOperation) GetState() CloseDeployRequestDeployOperationState {
	if c == nil {
		return CloseDeployRequestDeployOperationState("")
	}
	return c.State
}

func (c *CloseDeployRequestDeployOperation) GetKeyspaceName() string {
	if c == nil {
		return ""
	}
	return c.KeyspaceName
}

func (c *CloseDeployRequestDeployOperation) GetTableName() string {
	if c == nil {
		return ""
	}
	return c.TableName
}

func (c *CloseDeployRequestDeployOperation) GetOperationName() string {
	if c == nil {
		return ""
	}
	return c.OperationName
}

func (c *CloseDeployRequestDeployOperation) GetEtaSeconds() float64 {
	if c == nil {
		return 0.0
	}
	return c.EtaSeconds
}

func (c *CloseDeployRequestDeployOperation) GetProgressPercentage() float64 {
	if c == nil {
		return 0.0
	}
	return c.ProgressPercentage
}

func (c *CloseDeployRequestDeployOperation) GetDeployErrorDocsURL() string {
	if c == nil {
		return ""
	}
	return c.DeployErrorDocsURL
}

func (c *CloseDeployRequestDeployOperation) GetDdlStatement() string {
	if c == nil {
		return ""
	}
	return c.DdlStatement
}

func (c *CloseDeployRequestDeployOperation) GetSyntaxHighlightedDdl() string {
	if c == nil {
		return ""
	}
	return c.SyntaxHighlightedDdl
}

func (c *CloseDeployRequestDeployOperation) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CloseDeployRequestDeployOperation) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CloseDeployRequestDeployOperation) GetThrottledAt() string {
	if c == nil {
		return ""
	}
	return c.ThrottledAt
}

func (c *CloseDeployRequestDeployOperation) GetCanDropData() bool {
	if c == nil {
		return false
	}
	return c.CanDropData
}

func (c *CloseDeployRequestDeployOperation) GetTableLocked() bool {
	if c == nil {
		return false
	}
	return c.TableLocked
}

func (c *CloseDeployRequestDeployOperation) GetTableRecentlyUsed() bool {
	if c == nil {
		return false
	}
	return c.TableRecentlyUsed
}

func (c *CloseDeployRequestDeployOperation) GetTableRecentlyUsedAt() string {
	if c == nil {
		return ""
	}
	return c.TableRecentlyUsedAt
}

func (c *CloseDeployRequestDeployOperation) GetRemovedForeignKeyNames() []string {
	if c == nil {
		return []string{}
	}
	return c.RemovedForeignKeyNames
}

func (c *CloseDeployRequestDeployOperation) GetDeployErrors() string {
	if c == nil {
		return ""
	}
	return c.DeployErrors
}

// CloseDeployRequestDeployOperationSummaryState - The state of the deploy operation summary
type CloseDeployRequestDeployOperationSummaryState string

const (
	CloseDeployRequestDeployOperationSummaryStatePending    CloseDeployRequestDeployOperationSummaryState = "pending"
	CloseDeployRequestDeployOperationSummaryStateInProgress CloseDeployRequestDeployOperationSummaryState = "in_progress"
	CloseDeployRequestDeployOperationSummaryStateComplete   CloseDeployRequestDeployOperationSummaryState = "complete"
	CloseDeployRequestDeployOperationSummaryStateCancelled  CloseDeployRequestDeployOperationSummaryState = "cancelled"
	CloseDeployRequestDeployOperationSummaryStateError      CloseDeployRequestDeployOperationSummaryState = "error"
)

func (e CloseDeployRequestDeployOperationSummaryState) ToPointer() *CloseDeployRequestDeployOperationSummaryState {
	return &e
}
func (e *CloseDeployRequestDeployOperationSummaryState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = CloseDeployRequestDeployOperationSummaryState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseDeployRequestDeployOperationSummaryState: %v", v)
	}
}

// CloseDeployRequestOperationState - The state of the deploy operation
type CloseDeployRequestOperationState string

const (
	CloseDeployRequestOperationStatePending    CloseDeployRequestOperationState = "pending"
	CloseDeployRequestOperationStateQueued     CloseDeployRequestOperationState = "queued"
	CloseDeployRequestOperationStateInProgress CloseDeployRequestOperationState = "in_progress"
	CloseDeployRequestOperationStateComplete   CloseDeployRequestOperationState = "complete"
	CloseDeployRequestOperationStateCancelled  CloseDeployRequestOperationState = "cancelled"
	CloseDeployRequestOperationStateError      CloseDeployRequestOperationState = "error"
)

func (e CloseDeployRequestOperationState) ToPointer() *CloseDeployRequestOperationState {
	return &e
}
func (e *CloseDeployRequestOperationState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "queued":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = CloseDeployRequestOperationState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseDeployRequestOperationState: %v", v)
	}
}

type CloseDeployRequestOperation struct {
	// The ID for the deploy operation
	ID string `json:"id"`
	// The shard the deploy operation is being performed on
	Shard string `json:"shard"`
	// The state of the deploy operation
	State CloseDeployRequestOperationState `json:"state"`
	// The percent completion for the deploy operation
	ProgressPercentage float64 `json:"progress_percentage"`
	// The estimated seconds until completion for the deploy operation
	EtaSeconds int64 `json:"eta_seconds"`
}

func (c *CloseDeployRequestOperation) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestOperation) GetShard() string {
	if c == nil {
		return ""
	}
	return c.Shard
}

func (c *CloseDeployRequestOperation) GetState() CloseDeployRequestOperationState {
	if c == nil {
		return CloseDeployRequestOperationState("")
	}
	return c.State
}

func (c *CloseDeployRequestOperation) GetProgressPercentage() float64 {
	if c == nil {
		return 0.0
	}
	return c.ProgressPercentage
}

func (c *CloseDeployRequestOperation) GetEtaSeconds() int64 {
	if c == nil {
		return 0
	}
	return c.EtaSeconds
}

type CloseDeployRequestDeployOperationSummary struct {
	// The ID for the deploy operation summary
	ID string `json:"id"`
	// When the deploy operation summary was created
	CreatedAt string `json:"created_at"`
	// Deploy errors for the deploy operation summary
	DeployErrors string `json:"deploy_errors"`
	// The DDL statement for the deploy operation summary
	DdlStatement string `json:"ddl_statement"`
	// The estimated seconds until completion for the deploy operation summary
	EtaSeconds int64 `json:"eta_seconds"`
	// The keyspace modified by the deploy operation summary
	KeyspaceName string `json:"keyspace_name"`
	// The operation name of the deploy operation summary
	OperationName string `json:"operation_name"`
	// The percent completion for the deploy operation summary
	ProgressPercentage float64 `json:"progress_percentage"`
	// The state of the deploy operation summary
	State CloseDeployRequestDeployOperationSummaryState `json:"state"`
	// A syntax-highlighted DDL statement for the deploy operation summary
	SyntaxHighlightedDdl string `json:"syntax_highlighted_ddl"`
	// The name of the table modifed by the deploy operation summary
	TableName string `json:"table_name"`
	// When the table modified by the deploy operation summary was last used
	TableRecentlyUsedAt string `json:"table_recently_used_at"`
	// When the deploy operation summary was last throttled
	ThrottledAt string `json:"throttled_at"`
	// Names of foreign keys removed by this operation summary
	RemovedForeignKeyNames []string `json:"removed_foreign_key_names"`
	// The number of shards in the keyspace modified by the deploy operation summary
	ShardCount int64 `json:"shard_count"`
	// Names of shards in the keyspace modified by the deploy operation summary
	ShardNames []string `json:"shard_names"`
	// Whether or not the deploy operation summary is capable of dropping data
	CanDropData bool `json:"can_drop_data"`
	// Whether or not the table modified by the deploy operation summary was recently used
	TableRecentlyUsed bool `json:"table_recently_used"`
	// Whether or not the keyspace modified by the deploy operation summary is sharded
	Sharded    bool                          `json:"sharded"`
	Operations []CloseDeployRequestOperation `json:"operations"`
}

func (c *CloseDeployRequestDeployOperationSummary) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestDeployOperationSummary) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CloseDeployRequestDeployOperationSummary) GetDeployErrors() string {
	if c == nil {
		return ""
	}
	return c.DeployErrors
}

func (c *CloseDeployRequestDeployOperationSummary) GetDdlStatement() string {
	if c == nil {
		return ""
	}
	return c.DdlStatement
}

func (c *CloseDeployRequestDeployOperationSummary) GetEtaSeconds() int64 {
	if c == nil {
		return 0
	}
	return c.EtaSeconds
}

func (c *CloseDeployRequestDeployOperationSummary) GetKeyspaceName() string {
	if c == nil {
		return ""
	}
	return c.KeyspaceName
}

func (c *CloseDeployRequestDeployOperationSummary) GetOperationName() string {
	if c == nil {
		return ""
	}
	return c.OperationName
}

func (c *CloseDeployRequestDeployOperationSummary) GetProgressPercentage() float64 {
	if c == nil {
		return 0.0
	}
	return c.ProgressPercentage
}

func (c *CloseDeployRequestDeployOperationSummary) GetState() CloseDeployRequestDeployOperationSummaryState {
	if c == nil {
		return CloseDeployRequestDeployOperationSummaryState("")
	}
	return c.State
}

func (c *CloseDeployRequestDeployOperationSummary) GetSyntaxHighlightedDdl() string {
	if c == nil {
		return ""
	}
	return c.SyntaxHighlightedDdl
}

func (c *CloseDeployRequestDeployOperationSummary) GetTableName() string {
	if c == nil {
		return ""
	}
	return c.TableName
}

func (c *CloseDeployRequestDeployOperationSummary) GetTableRecentlyUsedAt() string {
	if c == nil {
		return ""
	}
	return c.TableRecentlyUsedAt
}

func (c *CloseDeployRequestDeployOperationSummary) GetThrottledAt() string {
	if c == nil {
		return ""
	}
	return c.ThrottledAt
}

func (c *CloseDeployRequestDeployOperationSummary) GetRemovedForeignKeyNames() []string {
	if c == nil {
		return []string{}
	}
	return c.RemovedForeignKeyNames
}

func (c *CloseDeployRequestDeployOperationSummary) GetShardCount() int64 {
	if c == nil {
		return 0
	}
	return c.ShardCount
}

func (c *CloseDeployRequestDeployOperationSummary) GetShardNames() []string {
	if c == nil {
		return []string{}
	}
	return c.ShardNames
}

func (c *CloseDeployRequestDeployOperationSummary) GetCanDropData() bool {
	if c == nil {
		return false
	}
	return c.CanDropData
}

func (c *CloseDeployRequestDeployOperationSummary) GetTableRecentlyUsed() bool {
	if c == nil {
		return false
	}
	return c.TableRecentlyUsed
}

func (c *CloseDeployRequestDeployOperationSummary) GetSharded() bool {
	if c == nil {
		return false
	}
	return c.Sharded
}

func (c *CloseDeployRequestDeployOperationSummary) GetOperations() []CloseDeployRequestOperation {
	if c == nil {
		return []CloseDeployRequestOperation{}
	}
	return c.Operations
}

type CloseDeployRequestDeploymentActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CloseDeployRequestDeploymentActor) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestDeploymentActor) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CloseDeployRequestDeploymentActor) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

type CloseDeployRequestCutoverActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CloseDeployRequestCutoverActor) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestCutoverActor) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CloseDeployRequestCutoverActor) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

type CloseDeployRequestCancelledActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CloseDeployRequestCancelledActor) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestCancelledActor) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CloseDeployRequestCancelledActor) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

type CloseDeployRequestDeployment struct {
	// The ID of the deployment
	ID string `json:"id"`
	// Whether or not to automatically cutover once deployment is finished
	AutoCutover bool `json:"auto_cutover"`
	// Whether or not to automatically delete the head branch once deployment is finished
	AutoDeleteBranch bool `json:"auto_delete_branch"`
	// When the deployment was created
	CreatedAt string `json:"created_at"`
	// When the cutover for the deployment was initiated
	CutoverAt string `json:"cutover_at"`
	// Whether or not the deployment cutover will expire soon
	CutoverExpiring bool `json:"cutover_expiring"`
	// Deploy check errors for the deployment
	DeployCheckErrors string `json:"deploy_check_errors"`
	// When the deployment was finished
	FinishedAt string `json:"finished_at"`
	// When the deployment was queued
	QueuedAt string `json:"queued_at"`
	// When the deployment was ready for cutover
	ReadyToCutoverAt string `json:"ready_to_cutover_at"`
	// When the deployment was started
	StartedAt string `json:"started_at"`
	// The state the deployment is in
	State CloseDeployRequestDeploymentState2 `json:"state"`
	// When the deployment was submitted
	SubmittedAt string `json:"submitted_at"`
	// When the deployment was last updated
	UpdatedAt string `json:"updated_at"`
	// The name of the base branch the deployment will be merged into
	IntoBranch string `json:"into_branch"`
	// The number of the deploy request associated with this deployment
	DeployRequestNumber int64 `json:"deploy_request_number"`
	// Whether the deployment is deployable
	Deployable bool `json:"deployable"`
	// The deployments ahead of this one in the queue
	PrecedingDeployments     []map[string]any                           `json:"preceding_deployments"`
	DeployOperations         []CloseDeployRequestDeployOperation        `json:"deploy_operations"`
	DeployOperationSummaries []CloseDeployRequestDeployOperationSummary `json:"deploy_operation_summaries"`
	// Schema lint errors preventing the deployment from completing
	LintErrors []map[string]any `json:"lint_errors"`
	// The schema dependencies that must be satisfied
	SequentialDiffDependencies []map[string]any `json:"sequential_diff_dependencies"`
	// Lookup Vitess index operations
	LookupVindexOperations []map[string]any `json:"lookup_vindex_operations"`
	// Deployment throttling configurations
	ThrottlerConfigurations []map[string]any `json:"throttler_configurations"`
	// The request to revert the schema operations in this deployment
	DeploymentRevertRequest map[string]any                    `json:"deployment_revert_request"`
	Actor                   CloseDeployRequestDeploymentActor `json:"actor"`
	CutoverActor            CloseDeployRequestCutoverActor    `json:"cutover_actor"`
	CancelledActor          CloseDeployRequestCancelledActor  `json:"cancelled_actor"`
	// When the schema was last updated for the deployment
	SchemaLastUpdatedAt string `json:"schema_last_updated_at"`
	// Whether or not the deployment has a table locked
	TableLocked bool `json:"table_locked"`
	// The name of he table that is locked by the deployment
	LockedTableName string `json:"locked_table_name"`
	// Whether or not the deployment is an instant DDL deployment
	InstantDdl bool `json:"instant_ddl"`
	// Whether or not the deployment is eligible for instant DDL
	InstantDdlEligible bool `json:"instant_ddl_eligible"`
}

func (c *CloseDeployRequestDeployment) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestDeployment) GetAutoCutover() bool {
	if c == nil {
		return false
	}
	return c.AutoCutover
}

func (c *CloseDeployRequestDeployment) GetAutoDeleteBranch() bool {
	if c == nil {
		return false
	}
	return c.AutoDeleteBranch
}

func (c *CloseDeployRequestDeployment) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CloseDeployRequestDeployment) GetCutoverAt() string {
	if c == nil {
		return ""
	}
	return c.CutoverAt
}

func (c *CloseDeployRequestDeployment) GetCutoverExpiring() bool {
	if c == nil {
		return false
	}
	return c.CutoverExpiring
}

func (c *CloseDeployRequestDeployment) GetDeployCheckErrors() string {
	if c == nil {
		return ""
	}
	return c.DeployCheckErrors
}

func (c *CloseDeployRequestDeployment) GetFinishedAt() string {
	if c == nil {
		return ""
	}
	return c.FinishedAt
}

func (c *CloseDeployRequestDeployment) GetQueuedAt() string {
	if c == nil {
		return ""
	}
	return c.QueuedAt
}

func (c *CloseDeployRequestDeployment) GetReadyToCutoverAt() string {
	if c == nil {
		return ""
	}
	return c.ReadyToCutoverAt
}

func (c *CloseDeployRequestDeployment) GetStartedAt() string {
	if c == nil {
		return ""
	}
	return c.StartedAt
}

func (c *CloseDeployRequestDeployment) GetState() CloseDeployRequestDeploymentState2 {
	if c == nil {
		return CloseDeployRequestDeploymentState2("")
	}
	return c.State
}

func (c *CloseDeployRequestDeployment) GetSubmittedAt() string {
	if c == nil {
		return ""
	}
	return c.SubmittedAt
}

func (c *CloseDeployRequestDeployment) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CloseDeployRequestDeployment) GetIntoBranch() string {
	if c == nil {
		return ""
	}
	return c.IntoBranch
}

func (c *CloseDeployRequestDeployment) GetDeployRequestNumber() int64 {
	if c == nil {
		return 0
	}
	return c.DeployRequestNumber
}

func (c *CloseDeployRequestDeployment) GetDeployable() bool {
	if c == nil {
		return false
	}
	return c.Deployable
}

func (c *CloseDeployRequestDeployment) GetPrecedingDeployments() []map[string]any {
	if c == nil {
		return []map[string]any{}
	}
	return c.PrecedingDeployments
}

func (c *CloseDeployRequestDeployment) GetDeployOperations() []CloseDeployRequestDeployOperation {
	if c == nil {
		return []CloseDeployRequestDeployOperation{}
	}
	return c.DeployOperations
}

func (c *CloseDeployRequestDeployment) GetDeployOperationSummaries() []CloseDeployRequestDeployOperationSummary {
	if c == nil {
		return []CloseDeployRequestDeployOperationSummary{}
	}
	return c.DeployOperationSummaries
}

func (c *CloseDeployRequestDeployment) GetLintErrors() []map[string]any {
	if c == nil {
		return []map[string]any{}
	}
	return c.LintErrors
}

func (c *CloseDeployRequestDeployment) GetSequentialDiffDependencies() []map[string]any {
	if c == nil {
		return []map[string]any{}
	}
	return c.SequentialDiffDependencies
}

func (c *CloseDeployRequestDeployment) GetLookupVindexOperations() []map[string]any {
	if c == nil {
		return []map[string]any{}
	}
	return c.LookupVindexOperations
}

func (c *CloseDeployRequestDeployment) GetThrottlerConfigurations() []map[string]any {
	if c == nil {
		return []map[string]any{}
	}
	return c.ThrottlerConfigurations
}

func (c *CloseDeployRequestDeployment) GetDeploymentRevertRequest() map[string]any {
	if c == nil {
		return map[string]any{}
	}
	return c.DeploymentRevertRequest
}

func (c *CloseDeployRequestDeployment) GetActor() CloseDeployRequestDeploymentActor {
	if c == nil {
		return CloseDeployRequestDeploymentActor{}
	}
	return c.Actor
}

func (c *CloseDeployRequestDeployment) GetCutoverActor() CloseDeployRequestCutoverActor {
	if c == nil {
		return CloseDeployRequestCutoverActor{}
	}
	return c.CutoverActor
}

func (c *CloseDeployRequestDeployment) GetCancelledActor() CloseDeployRequestCancelledActor {
	if c == nil {
		return CloseDeployRequestCancelledActor{}
	}
	return c.CancelledActor
}

func (c *CloseDeployRequestDeployment) GetSchemaLastUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.SchemaLastUpdatedAt
}

func (c *CloseDeployRequestDeployment) GetTableLocked() bool {
	if c == nil {
		return false
	}
	return c.TableLocked
}

func (c *CloseDeployRequestDeployment) GetLockedTableName() string {
	if c == nil {
		return ""
	}
	return c.LockedTableName
}

func (c *CloseDeployRequestDeployment) GetInstantDdl() bool {
	if c == nil {
		return false
	}
	return c.InstantDdl
}

func (c *CloseDeployRequestDeployment) GetInstantDdlEligible() bool {
	if c == nil {
		return false
	}
	return c.InstantDdlEligible
}

// CloseDeployRequestResponseBody - Returns the updated deploy request
type CloseDeployRequestResponseBody struct {
	// The ID of the deploy request
	ID string `json:"id"`
	// The number of the deploy request
	Number   int64                      `json:"number"`
	Actor    CloseDeployRequestActor    `json:"actor"`
	ClosedBy CloseDeployRequestClosedBy `json:"closed_by"`
	// The name of the branch the deploy request was created from
	Branch string `json:"branch"`
	// The ID of the branch the deploy request was created from
	BranchID string `json:"branch_id"`
	// Whether or not the deploy request branch was deleted
	BranchDeleted   bool                              `json:"branch_deleted"`
	BranchDeletedBy CloseDeployRequestBranchDeletedBy `json:"branch_deleted_by"`
	// When the deploy request branch was deleted
	BranchDeletedAt string `json:"branch_deleted_at"`
	// The name of the branch the deploy request will be merged into
	IntoBranch string `json:"into_branch"`
	// Whether or not the branch the deploy request will be merged into is sharded
	IntoBranchSharded bool `json:"into_branch_sharded"`
	// The number of shards the branch the deploy request will be merged into has
	IntoBranchShardCount int64 `json:"into_branch_shard_count"`
	// Whether or not the deploy request is approved
	Approved bool `json:"approved"`
	// Whether the deploy request is open or closed
	State CloseDeployRequestStateResponseBody `json:"state"`
	// The deployment state of the deploy request
	DeploymentState CloseDeployRequestDeploymentState1 `json:"deployment_state"`
	Deployment      CloseDeployRequestDeployment       `json:"deployment"`
	// The number of comments on the deploy request
	NumComments int64 `json:"num_comments"`
	// The PlanetScale app address for the deploy request
	HTMLURL string `json:"html_url"`
	// Notes on the deploy request
	Notes string `json:"notes"`
	// The HTML body of the deploy request
	HTMLBody string `json:"html_body"`
	// When the deploy request was created
	CreatedAt string `json:"created_at"`
	// When the deploy request was last updated
	UpdatedAt string `json:"updated_at"`
	// When the deploy request was closed
	ClosedAt string `json:"closed_at"`
	// When the deploy request was deployed
	DeployedAt string `json:"deployed_at"`
}

func (c *CloseDeployRequestResponseBody) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloseDeployRequestResponseBody) GetNumber() int64 {
	if c == nil {
		return 0
	}
	return c.Number
}

func (c *CloseDeployRequestResponseBody) GetActor() CloseDeployRequestActor {
	if c == nil {
		return CloseDeployRequestActor{}
	}
	return c.Actor
}

func (c *CloseDeployRequestResponseBody) GetClosedBy() CloseDeployRequestClosedBy {
	if c == nil {
		return CloseDeployRequestClosedBy{}
	}
	return c.ClosedBy
}

func (c *CloseDeployRequestResponseBody) GetBranch() string {
	if c == nil {
		return ""
	}
	return c.Branch
}

func (c *CloseDeployRequestResponseBody) GetBranchID() string {
	if c == nil {
		return ""
	}
	return c.BranchID
}

func (c *CloseDeployRequestResponseBody) GetBranchDeleted() bool {
	if c == nil {
		return false
	}
	return c.BranchDeleted
}

func (c *CloseDeployRequestResponseBody) GetBranchDeletedBy() CloseDeployRequestBranchDeletedBy {
	if c == nil {
		return CloseDeployRequestBranchDeletedBy{}
	}
	return c.BranchDeletedBy
}

func (c *CloseDeployRequestResponseBody) GetBranchDeletedAt() string {
	if c == nil {
		return ""
	}
	return c.BranchDeletedAt
}

func (c *CloseDeployRequestResponseBody) GetIntoBranch() string {
	if c == nil {
		return ""
	}
	return c.IntoBranch
}

func (c *CloseDeployRequestResponseBody) GetIntoBranchSharded() bool {
	if c == nil {
		return false
	}
	return c.IntoBranchSharded
}

func (c *CloseDeployRequestResponseBody) GetIntoBranchShardCount() int64 {
	if c == nil {
		return 0
	}
	return c.IntoBranchShardCount
}

func (c *CloseDeployRequestResponseBody) GetApproved() bool {
	if c == nil {
		return false
	}
	return c.Approved
}

func (c *CloseDeployRequestResponseBody) GetState() CloseDeployRequestStateResponseBody {
	if c == nil {
		return CloseDeployRequestStateResponseBody("")
	}
	return c.State
}

func (c *CloseDeployRequestResponseBody) GetDeploymentState() CloseDeployRequestDeploymentState1 {
	if c == nil {
		return CloseDeployRequestDeploymentState1("")
	}
	return c.DeploymentState
}

func (c *CloseDeployRequestResponseBody) GetDeployment() CloseDeployRequestDeployment {
	if c == nil {
		return CloseDeployRequestDeployment{}
	}
	return c.Deployment
}

func (c *CloseDeployRequestResponseBody) GetNumComments() int64 {
	if c == nil {
		return 0
	}
	return c.NumComments
}

func (c *CloseDeployRequestResponseBody) GetHTMLURL() string {
	if c == nil {
		return ""
	}
	return c.HTMLURL
}

func (c *CloseDeployRequestResponseBody) GetNotes() string {
	if c == nil {
		return ""
	}
	return c.Notes
}

func (c *CloseDeployRequestResponseBody) GetHTMLBody() string {
	if c == nil {
		return ""
	}
	return c.HTMLBody
}

func (c *CloseDeployRequestResponseBody) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CloseDeployRequestResponseBody) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CloseDeployRequestResponseBody) GetClosedAt() string {
	if c == nil {
		return ""
	}
	return c.ClosedAt
}

func (c *CloseDeployRequestResponseBody) GetDeployedAt() string {
	if c == nil {
		return ""
	}
	return c.DeployedAt
}

type CloseDeployRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the updated deploy request
	Object *CloseDeployRequestResponseBody
}

func (c CloseDeployRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CloseDeployRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CloseDeployRequestResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CloseDeployRequestResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CloseDeployRequestResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CloseDeployRequestResponse) GetObject() *CloseDeployRequestResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
