// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

// CreateVitessBranchBackupRetentionUnit - Unit for the retention period of the backup
type CreateVitessBranchBackupRetentionUnit string

const (
	CreateVitessBranchBackupRetentionUnitHour  CreateVitessBranchBackupRetentionUnit = "hour"
	CreateVitessBranchBackupRetentionUnitDay   CreateVitessBranchBackupRetentionUnit = "day"
	CreateVitessBranchBackupRetentionUnitWeek  CreateVitessBranchBackupRetentionUnit = "week"
	CreateVitessBranchBackupRetentionUnitMonth CreateVitessBranchBackupRetentionUnit = "month"
	CreateVitessBranchBackupRetentionUnitYear  CreateVitessBranchBackupRetentionUnit = "year"
)

func (e CreateVitessBranchBackupRetentionUnit) ToPointer() *CreateVitessBranchBackupRetentionUnit {
	return &e
}
func (e *CreateVitessBranchBackupRetentionUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "hour":
		fallthrough
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		fallthrough
	case "year":
		*e = CreateVitessBranchBackupRetentionUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateVitessBranchBackupRetentionUnit: %v", v)
	}
}

type CreateVitessBranchBackupRequestBody struct {
	// Name for the backup
	Name *string `json:"name,omitzero"`
	// Unit for the retention period of the backup
	RetentionUnit *CreateVitessBranchBackupRetentionUnit `json:"retention_unit,omitzero"`
	// Value between `1` and `1000` for the retention period of the backup (i.e retention_value `6` and retention_unit `hour` means 6 hours)
	RetentionValue *int64 `json:"retention_value,omitzero"`
}

func (c *CreateVitessBranchBackupRequestBody) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateVitessBranchBackupRequestBody) GetRetentionUnit() *CreateVitessBranchBackupRetentionUnit {
	if c == nil {
		return nil
	}
	return c.RetentionUnit
}

func (c *CreateVitessBranchBackupRequestBody) GetRetentionValue() *int64 {
	if c == nil {
		return nil
	}
	return c.RetentionValue
}

type CreateVitessBranchBackupRequest struct {
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Branch string                               `pathParam:"style=simple,explode=false,name=branch"`
	Body   *CreateVitessBranchBackupRequestBody `request:"mediaType=application/json"`
}

func (c CreateVitessBranchBackupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateVitessBranchBackupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateVitessBranchBackupRequest) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateVitessBranchBackupRequest) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateVitessBranchBackupRequest) GetBranch() string {
	if c == nil {
		return ""
	}
	return c.Branch
}

func (c *CreateVitessBranchBackupRequest) GetBody() *CreateVitessBranchBackupRequestBody {
	if c == nil {
		return nil
	}
	return c.Body
}

// CreateVitessBranchBackupState - The current state of the backup
type CreateVitessBranchBackupState string

const (
	CreateVitessBranchBackupStatePending  CreateVitessBranchBackupState = "pending"
	CreateVitessBranchBackupStateRunning  CreateVitessBranchBackupState = "running"
	CreateVitessBranchBackupStateSuccess  CreateVitessBranchBackupState = "success"
	CreateVitessBranchBackupStateFailed   CreateVitessBranchBackupState = "failed"
	CreateVitessBranchBackupStateCanceled CreateVitessBranchBackupState = "canceled"
	CreateVitessBranchBackupStateIgnored  CreateVitessBranchBackupState = "ignored"
)

func (e CreateVitessBranchBackupState) ToPointer() *CreateVitessBranchBackupState {
	return &e
}
func (e *CreateVitessBranchBackupState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "running":
		fallthrough
	case "success":
		fallthrough
	case "failed":
		fallthrough
	case "canceled":
		fallthrough
	case "ignored":
		*e = CreateVitessBranchBackupState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateVitessBranchBackupState: %v", v)
	}
}

type CreateVitessBranchBackupActor struct {
	// The ID of the actor
	ID string `json:"id"`
}

func (c *CreateVitessBranchBackupActor) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateVitessBranchBackupBackupPolicy struct {
	// The ID of the backup policy
	ID string `json:"id"`
}

func (c *CreateVitessBranchBackupBackupPolicy) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateVitessBranchBackupDatabaseBranch struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
}

func (c *CreateVitessBranchBackupDatabaseBranch) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateVitessBranchBackupDatabaseBranch) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

// CreateVitessBranchBackupResponseBody - Returns the created database branch backup
type CreateVitessBranchBackupResponseBody struct {
	// The ID of the backup
	ID string `json:"id"`
	// The name of the backup
	Name string `json:"name"`
	// The current state of the backup
	State CreateVitessBranchBackupState `json:"state"`
	// The size of the backup in bytes
	Size int64 `json:"size"`
	// The estimated storage cost of the backup
	EstimatedStorageCost float64 `json:"estimated_storage_cost"`
	// When the backup started
	StartedAt *string `json:"started_at"`
	// When the backup expires
	ExpiresAt *string `json:"expires_at"`
	// When the backup completed
	CompletedAt *string `json:"completed_at"`
	// When the backup was deleted
	DeletedAt *string `json:"deleted_at"`
	// Size of the PVC used for the backup
	PvcSize int64 `json:"pvc_size"`
	// The uncompressed (logical) size of the backup in bytes
	UncompressedSize int64 `json:"uncompressed_size"`
	// Whether or not the backup is protected from deletion
	Protected      bool                                    `json:"protected"`
	Actor          *CreateVitessBranchBackupActor          `json:"actor"`
	BackupPolicy   *CreateVitessBranchBackupBackupPolicy   `json:"backup_policy,omitzero"`
	DatabaseBranch *CreateVitessBranchBackupDatabaseBranch `json:"database_branch,omitzero"`
}

func (c CreateVitessBranchBackupResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateVitessBranchBackupResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateVitessBranchBackupResponseBody) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateVitessBranchBackupResponseBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateVitessBranchBackupResponseBody) GetState() CreateVitessBranchBackupState {
	if c == nil {
		return CreateVitessBranchBackupState("")
	}
	return c.State
}

func (c *CreateVitessBranchBackupResponseBody) GetSize() int64 {
	if c == nil {
		return 0
	}
	return c.Size
}

func (c *CreateVitessBranchBackupResponseBody) GetEstimatedStorageCost() float64 {
	if c == nil {
		return 0.0
	}
	return c.EstimatedStorageCost
}

func (c *CreateVitessBranchBackupResponseBody) GetStartedAt() *string {
	if c == nil {
		return nil
	}
	return c.StartedAt
}

func (c *CreateVitessBranchBackupResponseBody) GetExpiresAt() *string {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreateVitessBranchBackupResponseBody) GetCompletedAt() *string {
	if c == nil {
		return nil
	}
	return c.CompletedAt
}

func (c *CreateVitessBranchBackupResponseBody) GetDeletedAt() *string {
	if c == nil {
		return nil
	}
	return c.DeletedAt
}

func (c *CreateVitessBranchBackupResponseBody) GetPvcSize() int64 {
	if c == nil {
		return 0
	}
	return c.PvcSize
}

func (c *CreateVitessBranchBackupResponseBody) GetUncompressedSize() int64 {
	if c == nil {
		return 0
	}
	return c.UncompressedSize
}

func (c *CreateVitessBranchBackupResponseBody) GetProtected() bool {
	if c == nil {
		return false
	}
	return c.Protected
}

func (c *CreateVitessBranchBackupResponseBody) GetActor() *CreateVitessBranchBackupActor {
	if c == nil {
		return nil
	}
	return c.Actor
}

func (c *CreateVitessBranchBackupResponseBody) GetBackupPolicy() *CreateVitessBranchBackupBackupPolicy {
	if c == nil {
		return nil
	}
	return c.BackupPolicy
}

func (c *CreateVitessBranchBackupResponseBody) GetDatabaseBranch() *CreateVitessBranchBackupDatabaseBranch {
	if c == nil {
		return nil
	}
	return c.DatabaseBranch
}

type CreateVitessBranchBackupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the created database branch backup
	Object *CreateVitessBranchBackupResponseBody
}

func (c CreateVitessBranchBackupResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateVitessBranchBackupResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateVitessBranchBackupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateVitessBranchBackupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateVitessBranchBackupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateVitessBranchBackupResponse) GetObject() *CreateVitessBranchBackupResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
