// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type CreateKeyspaceRequestBody struct {
	// The name of the keyspace
	Name string `json:"name"`
	// The database cluster size name (e.g., `PS_10`, `PS_80`). Updates in place via a keyspace resize. Use the List available cluster sizes endpoint for options for your organization.
	ClusterSize string `json:"cluster_size"`
	// The number of additional replicas beyond the included default. Updates in place via a keyspace resize.
	ExtraReplicas *int64 `json:"extra_replicas,omitzero"`
	// The number of shards. Default: 1. Set only at create time; changing this value requires replacement.
	Shards *int64 `json:"shards,omitzero"`
}

func (c *CreateKeyspaceRequestBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateKeyspaceRequestBody) GetClusterSize() string {
	if c == nil {
		return ""
	}
	return c.ClusterSize
}

func (c *CreateKeyspaceRequestBody) GetExtraReplicas() *int64 {
	if c == nil {
		return nil
	}
	return c.ExtraReplicas
}

func (c *CreateKeyspaceRequestBody) GetShards() *int64 {
	if c == nil {
		return nil
	}
	return c.Shards
}

type CreateKeyspaceRequest struct {
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Branch string                     `pathParam:"style=simple,explode=false,name=branch"`
	Body   *CreateKeyspaceRequestBody `request:"mediaType=application/json"`
}

func (c CreateKeyspaceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateKeyspaceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateKeyspaceRequest) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateKeyspaceRequest) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateKeyspaceRequest) GetBranch() string {
	if c == nil {
		return ""
	}
	return c.Branch
}

func (c *CreateKeyspaceRequest) GetBody() *CreateKeyspaceRequestBody {
	if c == nil {
		return nil
	}
	return c.Body
}

// CreateKeyspaceNodeTTLStrategy - Controls when node TTL drains are allowed
type CreateKeyspaceNodeTTLStrategy string

const (
	CreateKeyspaceNodeTTLStrategyNodeTTLFollowMaintenance CreateKeyspaceNodeTTLStrategy = "node_ttl_follow_maintenance"
	CreateKeyspaceNodeTTLStrategyNodeTTLAlways            CreateKeyspaceNodeTTLStrategy = "node_ttl_always"
	CreateKeyspaceNodeTTLStrategyNodeTTLOff               CreateKeyspaceNodeTTLStrategy = "node_ttl_off"
)

func (e CreateKeyspaceNodeTTLStrategy) ToPointer() *CreateKeyspaceNodeTTLStrategy {
	return &e
}
func (e *CreateKeyspaceNodeTTLStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "node_ttl_follow_maintenance":
		fallthrough
	case "node_ttl_always":
		fallthrough
	case "node_ttl_off":
		*e = CreateKeyspaceNodeTTLStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateKeyspaceNodeTTLStrategy: %v", v)
	}
}

// CreateKeyspaceStrategy - The replication durability strategy
type CreateKeyspaceStrategy string

const (
	CreateKeyspaceStrategyAvailable CreateKeyspaceStrategy = "available"
	CreateKeyspaceStrategyLag       CreateKeyspaceStrategy = "lag"
	CreateKeyspaceStrategyAlways    CreateKeyspaceStrategy = "always"
)

func (e CreateKeyspaceStrategy) ToPointer() *CreateKeyspaceStrategy {
	return &e
}
func (e *CreateKeyspaceStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "available":
		fallthrough
	case "lag":
		fallthrough
	case "always":
		*e = CreateKeyspaceStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateKeyspaceStrategy: %v", v)
	}
}

type CreateKeyspaceReplicationDurabilityConstraints struct {
	// The replication durability strategy
	Strategy *CreateKeyspaceStrategy `json:"strategy,omitzero"`
}

func (c *CreateKeyspaceReplicationDurabilityConstraints) GetStrategy() *CreateKeyspaceStrategy {
	if c == nil {
		return nil
	}
	return c.Strategy
}

type CreateKeyspaceVreplicationFlags struct {
	// Enable optimized inserts
	OptimizeInserts bool `json:"optimize_inserts"`
	// Allow no blob binlog row image
	AllowNoBlobBinlogRowImage bool `json:"allow_no_blob_binlog_row_image"`
	// Enable VPlayer batching
	VplayerBatching bool `json:"vplayer_batching"`
}

func (c *CreateKeyspaceVreplicationFlags) GetOptimizeInserts() bool {
	if c == nil {
		return false
	}
	return c.OptimizeInserts
}

func (c *CreateKeyspaceVreplicationFlags) GetAllowNoBlobBinlogRowImage() bool {
	if c == nil {
		return false
	}
	return c.AllowNoBlobBinlogRowImage
}

func (c *CreateKeyspaceVreplicationFlags) GetVplayerBatching() bool {
	if c == nil {
		return false
	}
	return c.VplayerBatching
}

// CreateKeyspaceResponseBody - Returns a created keyspace
type CreateKeyspaceResponseBody struct {
	// The ID of the keyspace
	ID string `json:"id"`
	// Name of the keyspace
	Name string `json:"name"`
	// The number of shards. Set only at create time; changing this value requires replacement.
	Shards int64 `json:"shards"`
	// If the keyspace is sharded
	Sharded bool `json:"sharded"`
	// Total number of replicas in the keyspace
	Replicas int64 `json:"replicas"`
	// The number of additional replicas beyond the included default. Updates in place via a keyspace resize.
	ExtraReplicas int64 `json:"extra_replicas"`
	// When the keyspace was created
	CreatedAt string `json:"created_at"`
	// When the keyspace was last updated
	UpdatedAt string `json:"updated_at"`
	// The database cluster size name (e.g., `PS_10`, `PS_80`). Updates in place via a keyspace resize.
	ClusterSize string `json:"cluster_name"`
	// The SKU representing the keyspace cluster size for display
	ClusterDisplayName string `json:"cluster_display_name"`
	// True while the keyspace is actively resizing. The provider waits for this to become false after create and update.
	Resizing bool `json:"resizing"`
	// True while a resize request is queued. The provider waits for this to become false after create and update.
	ResizePending bool `json:"resize_pending"`
	// Is the keyspace undergoing a config change
	ConfigChangeInProgress bool `json:"config_change_in_progress"`
	// Is the keyspace provisioned and serving traffic
	Ready bool `json:"ready"`
	// Is the keyspace running on metal instances
	Metal bool `json:"metal"`
	// True when this is the branch's default keyspace (usually created with the branch). Import that keyspace to manage its size or replicas; do not try to create it with this resource.
	IsDefault bool `json:"default"`
	// Is this keyspace used in an import
	Imported bool `json:"imported"`
	// Percentage of buffer pool memory allocated to vector indexes
	VectorPoolAllocation *float64 `json:"vector_pool_allocation"`
	// Controls when node TTL drains are allowed
	NodeTTLStrategy                  CreateKeyspaceNodeTTLStrategy                  `json:"node_ttl_strategy"`
	ReplicationDurabilityConstraints CreateKeyspaceReplicationDurabilityConstraints `json:"replication_durability_constraints"`
	VreplicationFlags                CreateKeyspaceVreplicationFlags                `json:"vreplication_flags"`
	// True while any unfinished resize request exists for the keyspace. Computed for observability; apply waits on ready, resizing, resize_pending, and config_change_in_progress instead, because this flag can lag after the resize has already applied.
	ResizeInProgress bool `json:"resize_in_progress"`
}

func (c *CreateKeyspaceResponseBody) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateKeyspaceResponseBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateKeyspaceResponseBody) GetShards() int64 {
	if c == nil {
		return 0
	}
	return c.Shards
}

func (c *CreateKeyspaceResponseBody) GetSharded() bool {
	if c == nil {
		return false
	}
	return c.Sharded
}

func (c *CreateKeyspaceResponseBody) GetReplicas() int64 {
	if c == nil {
		return 0
	}
	return c.Replicas
}

func (c *CreateKeyspaceResponseBody) GetExtraReplicas() int64 {
	if c == nil {
		return 0
	}
	return c.ExtraReplicas
}

func (c *CreateKeyspaceResponseBody) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateKeyspaceResponseBody) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateKeyspaceResponseBody) GetClusterSize() string {
	if c == nil {
		return ""
	}
	return c.ClusterSize
}

func (c *CreateKeyspaceResponseBody) GetClusterDisplayName() string {
	if c == nil {
		return ""
	}
	return c.ClusterDisplayName
}

func (c *CreateKeyspaceResponseBody) GetResizing() bool {
	if c == nil {
		return false
	}
	return c.Resizing
}

func (c *CreateKeyspaceResponseBody) GetResizePending() bool {
	if c == nil {
		return false
	}
	return c.ResizePending
}

func (c *CreateKeyspaceResponseBody) GetConfigChangeInProgress() bool {
	if c == nil {
		return false
	}
	return c.ConfigChangeInProgress
}

func (c *CreateKeyspaceResponseBody) GetReady() bool {
	if c == nil {
		return false
	}
	return c.Ready
}

func (c *CreateKeyspaceResponseBody) GetMetal() bool {
	if c == nil {
		return false
	}
	return c.Metal
}

func (c *CreateKeyspaceResponseBody) GetIsDefault() bool {
	if c == nil {
		return false
	}
	return c.IsDefault
}

func (c *CreateKeyspaceResponseBody) GetImported() bool {
	if c == nil {
		return false
	}
	return c.Imported
}

func (c *CreateKeyspaceResponseBody) GetVectorPoolAllocation() *float64 {
	if c == nil {
		return nil
	}
	return c.VectorPoolAllocation
}

func (c *CreateKeyspaceResponseBody) GetNodeTTLStrategy() CreateKeyspaceNodeTTLStrategy {
	if c == nil {
		return CreateKeyspaceNodeTTLStrategy("")
	}
	return c.NodeTTLStrategy
}

func (c *CreateKeyspaceResponseBody) GetReplicationDurabilityConstraints() CreateKeyspaceReplicationDurabilityConstraints {
	if c == nil {
		return CreateKeyspaceReplicationDurabilityConstraints{}
	}
	return c.ReplicationDurabilityConstraints
}

func (c *CreateKeyspaceResponseBody) GetVreplicationFlags() CreateKeyspaceVreplicationFlags {
	if c == nil {
		return CreateKeyspaceVreplicationFlags{}
	}
	return c.VreplicationFlags
}

func (c *CreateKeyspaceResponseBody) GetResizeInProgress() bool {
	if c == nil {
		return false
	}
	return c.ResizeInProgress
}

type CreateKeyspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a created keyspace
	Object *CreateKeyspaceResponseBody
}

func (c CreateKeyspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateKeyspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateKeyspaceResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateKeyspaceResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateKeyspaceResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateKeyspaceResponse) GetObject() *CreateKeyspaceResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
