// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/models/shared"
	"net/http"
)

type CreateRouterRequestBody struct {
	Name string `json:"name"`
	// The router size SKU, for example `NKR_5`. The API returns current size details in the computed `sku` attribute.
	RouterSize      *string `json:"router_size,omitzero"`
	ReplicasPerCell *int64  `json:"replicas_per_cell,omitzero"`
}

func (c *CreateRouterRequestBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateRouterRequestBody) GetRouterSize() *string {
	if c == nil {
		return nil
	}
	return c.RouterSize
}

func (c *CreateRouterRequestBody) GetReplicasPerCell() *int64 {
	if c == nil {
		return nil
	}
	return c.ReplicasPerCell
}

type CreateRouterRequest struct {
	Organization string                  `pathParam:"style=simple,explode=false,name=organization"`
	Database     string                  `pathParam:"style=simple,explode=false,name=database"`
	Branch       string                  `pathParam:"style=simple,explode=false,name=branch"`
	Body         CreateRouterRequestBody `request:"mediaType=application/json"`
}

func (c *CreateRouterRequest) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateRouterRequest) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateRouterRequest) GetBranch() string {
	if c == nil {
		return ""
	}
	return c.Branch
}

func (c *CreateRouterRequest) GetBody() CreateRouterRequestBody {
	if c == nil {
		return CreateRouterRequestBody{}
	}
	return c.Body
}

type CreateRouterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the created router.
	NekiRouter *shared.NekiRouter
}

func (c CreateRouterResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRouterResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRouterResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateRouterResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateRouterResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateRouterResponse) GetNekiRouter() *shared.NekiRouter {
	if c == nil {
		return nil
	}
	return c.NekiRouter
}
