// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type CreateQueryPatternsReportRequest struct {
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
}

func (c *CreateQueryPatternsReportRequest) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateQueryPatternsReportRequest) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateQueryPatternsReportRequest) GetBranch() string {
	if c == nil {
		return ""
	}
	return c.Branch
}

// CreateQueryPatternsReportState - The state of the download
type CreateQueryPatternsReportState string

const (
	CreateQueryPatternsReportStatePending   CreateQueryPatternsReportState = "pending"
	CreateQueryPatternsReportStateCompleted CreateQueryPatternsReportState = "completed"
	CreateQueryPatternsReportStateFailed    CreateQueryPatternsReportState = "failed"
)

func (e CreateQueryPatternsReportState) ToPointer() *CreateQueryPatternsReportState {
	return &e
}
func (e *CreateQueryPatternsReportState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "completed":
		fallthrough
	case "failed":
		*e = CreateQueryPatternsReportState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateQueryPatternsReportState: %v", v)
	}
}

type CreateQueryPatternsReportActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (c *CreateQueryPatternsReportActor) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateQueryPatternsReportActor) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CreateQueryPatternsReportActor) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

// CreateQueryPatternsReportResponseBody - The created query patterns download
type CreateQueryPatternsReportResponseBody struct {
	// The ID of the query patterns download
	ID string `json:"id"`
	// The state of the download
	State CreateQueryPatternsReportState `json:"state"`
	// When the download was created
	CreatedAt string `json:"created_at"`
	// When the download was finished
	FinishedAt string `json:"finished_at"`
	// The URL to access the query patterns download
	URL string `json:"url"`
	// The URL to download the query patterns file
	DownloadURL string                         `json:"download_url"`
	Actor       CreateQueryPatternsReportActor `json:"actor"`
}

func (c *CreateQueryPatternsReportResponseBody) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateQueryPatternsReportResponseBody) GetState() CreateQueryPatternsReportState {
	if c == nil {
		return CreateQueryPatternsReportState("")
	}
	return c.State
}

func (c *CreateQueryPatternsReportResponseBody) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateQueryPatternsReportResponseBody) GetFinishedAt() string {
	if c == nil {
		return ""
	}
	return c.FinishedAt
}

func (c *CreateQueryPatternsReportResponseBody) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *CreateQueryPatternsReportResponseBody) GetDownloadURL() string {
	if c == nil {
		return ""
	}
	return c.DownloadURL
}

func (c *CreateQueryPatternsReportResponseBody) GetActor() CreateQueryPatternsReportActor {
	if c == nil {
		return CreateQueryPatternsReportActor{}
	}
	return c.Actor
}

type CreateQueryPatternsReportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The created query patterns download
	Object *CreateQueryPatternsReportResponseBody
}

func (c CreateQueryPatternsReportResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateQueryPatternsReportResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateQueryPatternsReportResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateQueryPatternsReportResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateQueryPatternsReportResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateQueryPatternsReportResponse) GetObject() *CreateQueryPatternsReportResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
