// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

// GrantType - Whether an OAuth grant code or a refresh token is being exchanged for an OAuth token
type GrantType string

const (
	GrantTypeAuthorizationCode GrantType = "authorization_code"
	GrantTypeRefreshToken      GrantType = "refresh_token"
)

func (e GrantType) ToPointer() *GrantType {
	return &e
}
func (e *GrantType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authorization_code":
		fallthrough
	case "refresh_token":
		*e = GrantType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GrantType: %v", v)
	}
}

type CreateOauthTokenRequestBody struct {
	// The OAuth application's client ID
	ClientID string `json:"client_id"`
	// The OAuth application's client secret
	ClientSecret string `json:"client_secret"`
	// Whether an OAuth grant code or a refresh token is being exchanged for an OAuth token
	GrantType GrantType `json:"grant_type"`
	// The OAuth grant code provided to your OAuth application's redirect URI. Required when grant_type is authorization_code
	Code *string `json:"code,omitzero"`
	// The OAuth application's redirect URI. Required when grant_type is authorization_code
	RedirectURI *string `json:"redirect_uri,omitzero"`
	// The refresh token from the original OAuth token grant. Required when grant_type is refresh_token
	RefreshToken *string `json:"refresh_token,omitzero"`
}

func (c *CreateOauthTokenRequestBody) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

func (c *CreateOauthTokenRequestBody) GetClientSecret() string {
	if c == nil {
		return ""
	}
	return c.ClientSecret
}

func (c *CreateOauthTokenRequestBody) GetGrantType() GrantType {
	if c == nil {
		return GrantType("")
	}
	return c.GrantType
}

func (c *CreateOauthTokenRequestBody) GetCode() *string {
	if c == nil {
		return nil
	}
	return c.Code
}

func (c *CreateOauthTokenRequestBody) GetRedirectURI() *string {
	if c == nil {
		return nil
	}
	return c.RedirectURI
}

func (c *CreateOauthTokenRequestBody) GetRefreshToken() *string {
	if c == nil {
		return nil
	}
	return c.RefreshToken
}

type CreateOauthTokenRequest struct {
	// The name of the organization the OAuth application belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The ID of the OAuth application
	ID   string                       `pathParam:"style=simple,explode=false,name=id"`
	Body *CreateOauthTokenRequestBody `request:"mediaType=application/json"`
}

func (c CreateOauthTokenRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOauthTokenRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"organization", "id"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateOauthTokenRequest) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateOauthTokenRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenRequest) GetBody() *CreateOauthTokenRequestBody {
	if c == nil {
		return nil
	}
	return c.Body
}

type CreateOauthTokenResource struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (c *CreateOauthTokenResource) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenResource) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenResource) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateOauthTokenResource) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateOauthTokenResource) GetDeletedAt() string {
	if c == nil {
		return ""
	}
	return c.DeletedAt
}

type CreateOauthTokenServiceTokenAccess struct {
	// The ID of the service token access
	ID string `json:"id"`
	// The name of the service token access
	Access string `json:"access"`
	// The description of the service token access
	Description string `json:"description"`
	// The name of the resource the service token access gives access to
	ResourceName string `json:"resource_name"`
	// The ID of the resource the service token access gives access to
	ResourceID string `json:"resource_id"`
	// The type of the resource the service token access gives access to
	ResourceType string                   `json:"resource_type"`
	Resource     CreateOauthTokenResource `json:"resource"`
}

func (c *CreateOauthTokenServiceTokenAccess) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenServiceTokenAccess) GetAccess() string {
	if c == nil {
		return ""
	}
	return c.Access
}

func (c *CreateOauthTokenServiceTokenAccess) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateOauthTokenServiceTokenAccess) GetResourceName() string {
	if c == nil {
		return ""
	}
	return c.ResourceName
}

func (c *CreateOauthTokenServiceTokenAccess) GetResourceID() string {
	if c == nil {
		return ""
	}
	return c.ResourceID
}

func (c *CreateOauthTokenServiceTokenAccess) GetResourceType() string {
	if c == nil {
		return ""
	}
	return c.ResourceType
}

func (c *CreateOauthTokenServiceTokenAccess) GetResource() CreateOauthTokenResource {
	if c == nil {
		return CreateOauthTokenResource{}
	}
	return c.Resource
}

type CreateOauthTokenDatabase1 struct {
	// the name of the database the token has access to
	Name string `json:"name"`
	// the id of the database the token has access to
	ID string `json:"id"`
	// the name of the database's organization
	Organization string `json:"organization"`
	// the planetscale app url for the database
	URL string `json:"url"`
}

func (c *CreateOauthTokenDatabase1) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenDatabase1) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenDatabase1) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateOauthTokenDatabase1) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type CreateOauthTokenDatabaseAccess struct {
	// The name of the access scope
	Name string `json:"name"`
	// The scope description
	Description string `json:"description"`
}

func (c *CreateOauthTokenDatabaseAccess) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenDatabaseAccess) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

type CreateOauthTokenDatabase2 struct {
	Databases []CreateOauthTokenDatabase1      `json:"databases"`
	Accesses  []CreateOauthTokenDatabaseAccess `json:"accesses"`
}

func (c *CreateOauthTokenDatabase2) GetDatabases() []CreateOauthTokenDatabase1 {
	if c == nil {
		return []CreateOauthTokenDatabase1{}
	}
	return c.Databases
}

func (c *CreateOauthTokenDatabase2) GetAccesses() []CreateOauthTokenDatabaseAccess {
	if c == nil {
		return []CreateOauthTokenDatabaseAccess{}
	}
	return c.Accesses
}

type CreateOauthTokenOrganization1 struct {
	// the name of the organization
	Name string `json:"name"`
	// the id of the organization
	ID string `json:"id"`
	// the planetscale app url for the organization
	URL string `json:"url"`
}

func (c *CreateOauthTokenOrganization1) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenOrganization1) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenOrganization1) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type CreateOauthTokenOrganizationAccess struct {
	// The name of the access scope
	Name string `json:"name"`
	// The scope description
	Description string `json:"description"`
}

func (c *CreateOauthTokenOrganizationAccess) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenOrganizationAccess) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

type CreateOauthTokenOrganization2 struct {
	Organizations []CreateOauthTokenOrganization1      `json:"organizations"`
	Accesses      []CreateOauthTokenOrganizationAccess `json:"accesses"`
}

func (c *CreateOauthTokenOrganization2) GetOrganizations() []CreateOauthTokenOrganization1 {
	if c == nil {
		return []CreateOauthTokenOrganization1{}
	}
	return c.Organizations
}

func (c *CreateOauthTokenOrganization2) GetAccesses() []CreateOauthTokenOrganizationAccess {
	if c == nil {
		return []CreateOauthTokenOrganizationAccess{}
	}
	return c.Accesses
}

type CreateOauthTokenBranch1 struct {
	// the name of the branch
	Name string `json:"name"`
	// the id of the branch
	ID string `json:"id"`
	// the name of the database the branch belongs to
	Database string `json:"database"`
	// the name of the organization the branch belongs to
	Organization string `json:"organization"`
	// the planetscale app url for the branch
	URL string `json:"url"`
}

func (c *CreateOauthTokenBranch1) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenBranch1) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenBranch1) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateOauthTokenBranch1) GetOrganization() string {
	if c == nil {
		return ""
	}
	return c.Organization
}

func (c *CreateOauthTokenBranch1) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type CreateOauthTokenBranchAccess struct {
	// The name of the access scope
	Name string `json:"name"`
	// The scope description
	Description string `json:"description"`
}

func (c *CreateOauthTokenBranchAccess) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenBranchAccess) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

type CreateOauthTokenBranch2 struct {
	Branches []CreateOauthTokenBranch1      `json:"branches"`
	Accesses []CreateOauthTokenBranchAccess `json:"accesses"`
}

func (c *CreateOauthTokenBranch2) GetBranches() []CreateOauthTokenBranch1 {
	if c == nil {
		return []CreateOauthTokenBranch1{}
	}
	return c.Branches
}

func (c *CreateOauthTokenBranch2) GetAccesses() []CreateOauthTokenBranchAccess {
	if c == nil {
		return []CreateOauthTokenBranchAccess{}
	}
	return c.Accesses
}

type CreateOauthTokenUser1 struct {
	// the name of the user
	Name string `json:"name"`
	// the id of the user
	ID string `json:"id"`
}

func (c *CreateOauthTokenUser1) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenUser1) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateOauthTokenUserAccess struct {
	// The name of the access scope
	Name string `json:"name"`
	// The scope description
	Description string `json:"description"`
}

func (c *CreateOauthTokenUserAccess) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenUserAccess) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

type CreateOauthTokenUser2 struct {
	Users    []CreateOauthTokenUser1      `json:"users"`
	Accesses []CreateOauthTokenUserAccess `json:"accesses"`
}

func (c *CreateOauthTokenUser2) GetUsers() []CreateOauthTokenUser1 {
	if c == nil {
		return []CreateOauthTokenUser1{}
	}
	return c.Users
}

func (c *CreateOauthTokenUser2) GetAccesses() []CreateOauthTokenUserAccess {
	if c == nil {
		return []CreateOauthTokenUserAccess{}
	}
	return c.Accesses
}

type CreateOauthTokenOauthAccessesByResource struct {
	Database     CreateOauthTokenDatabase2     `json:"database"`
	Organization CreateOauthTokenOrganization2 `json:"organization"`
	Branch       CreateOauthTokenBranch2       `json:"branch"`
	User         CreateOauthTokenUser2         `json:"user"`
}

func (c *CreateOauthTokenOauthAccessesByResource) GetDatabase() CreateOauthTokenDatabase2 {
	if c == nil {
		return CreateOauthTokenDatabase2{}
	}
	return c.Database
}

func (c *CreateOauthTokenOauthAccessesByResource) GetOrganization() CreateOauthTokenOrganization2 {
	if c == nil {
		return CreateOauthTokenOrganization2{}
	}
	return c.Organization
}

func (c *CreateOauthTokenOauthAccessesByResource) GetBranch() CreateOauthTokenBranch2 {
	if c == nil {
		return CreateOauthTokenBranch2{}
	}
	return c.Branch
}

func (c *CreateOauthTokenOauthAccessesByResource) GetUser() CreateOauthTokenUser2 {
	if c == nil {
		return CreateOauthTokenUser2{}
	}
	return c.User
}

// CreateOauthTokenResponseBody - Returns the created OAuth token
type CreateOauthTokenResponseBody struct {
	// The ID of the service token
	ID string `json:"id"`
	// The name of the service token
	Name string `json:"name"`
	// The display name of the service token
	DisplayName string `json:"display_name"`
	// The plain text token. Available only after create.
	Token string `json:"token"`
	// The plain text refresh token. Available only after create.
	PlainTextRefreshToken string `json:"plain_text_refresh_token"`
	// The image source for the avatar of the service token
	AvatarURL string `json:"avatar_url"`
	// When the service token was created
	CreatedAt string `json:"created_at"`
	// When the service token was last updated
	UpdatedAt string `json:"updated_at"`
	// When the service token will expire
	ExpiresAt string `json:"expires_at"`
	// When the service token was last used
	LastUsedAt string `json:"last_used_at"`
	// The ID of the actor on whose behalf the service token was created
	ActorID string `json:"actor_id"`
	// The name of the actor on whose behalf the service token was created
	ActorDisplayName string `json:"actor_display_name"`
	// The type of the actor on whose behalf the service token was created
	ActorType               string                                  `json:"actor_type"`
	ServiceTokenAccesses    []CreateOauthTokenServiceTokenAccess    `json:"service_token_accesses"`
	OauthAccessesByResource CreateOauthTokenOauthAccessesByResource `json:"oauth_accesses_by_resource"`
}

func (c *CreateOauthTokenResponseBody) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateOauthTokenResponseBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOauthTokenResponseBody) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CreateOauthTokenResponseBody) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CreateOauthTokenResponseBody) GetPlainTextRefreshToken() string {
	if c == nil {
		return ""
	}
	return c.PlainTextRefreshToken
}

func (c *CreateOauthTokenResponseBody) GetAvatarURL() string {
	if c == nil {
		return ""
	}
	return c.AvatarURL
}

func (c *CreateOauthTokenResponseBody) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateOauthTokenResponseBody) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateOauthTokenResponseBody) GetExpiresAt() string {
	if c == nil {
		return ""
	}
	return c.ExpiresAt
}

func (c *CreateOauthTokenResponseBody) GetLastUsedAt() string {
	if c == nil {
		return ""
	}
	return c.LastUsedAt
}

func (c *CreateOauthTokenResponseBody) GetActorID() string {
	if c == nil {
		return ""
	}
	return c.ActorID
}

func (c *CreateOauthTokenResponseBody) GetActorDisplayName() string {
	if c == nil {
		return ""
	}
	return c.ActorDisplayName
}

func (c *CreateOauthTokenResponseBody) GetActorType() string {
	if c == nil {
		return ""
	}
	return c.ActorType
}

func (c *CreateOauthTokenResponseBody) GetServiceTokenAccesses() []CreateOauthTokenServiceTokenAccess {
	if c == nil {
		return []CreateOauthTokenServiceTokenAccess{}
	}
	return c.ServiceTokenAccesses
}

func (c *CreateOauthTokenResponseBody) GetOauthAccessesByResource() CreateOauthTokenOauthAccessesByResource {
	if c == nil {
		return CreateOauthTokenOauthAccessesByResource{}
	}
	return c.OauthAccessesByResource
}

type CreateOauthTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the created OAuth token
	Object *CreateOauthTokenResponseBody
}

func (c CreateOauthTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOauthTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateOauthTokenResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOauthTokenResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOauthTokenResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOauthTokenResponse) GetObject() *CreateOauthTokenResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
