// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6b1a6995c582

package operations

import (
	"net/http"
)

type DeletePostgresBackupPolicyRequest struct {
	// The ID of the backup policy
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization name slug from `list_organizations`. Example: `acme`.
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Database name slug from `list_databases`. Example: `app-db`.
	Database string `pathParam:"style=simple,explode=false,name=database"`
}

func (d *DeletePostgresBackupPolicyRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeletePostgresBackupPolicyRequest) GetOrganization() string {
	if d == nil {
		return ""
	}
	return d.Organization
}

func (d *DeletePostgresBackupPolicyRequest) GetDatabase() string {
	if d == nil {
		return ""
	}
	return d.Database
}

type DeletePostgresBackupPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeletePostgresBackupPolicyResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeletePostgresBackupPolicyResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeletePostgresBackupPolicyResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
