// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOrganizationTeamRequest struct {
	// The name of the organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The slug of the team
	Team string `pathParam:"style=simple,explode=false,name=team"`
}

func (d *DeleteOrganizationTeamRequest) GetOrganization() string {
	if d == nil {
		return ""
	}
	return d.Organization
}

func (d *DeleteOrganizationTeamRequest) GetTeam() string {
	if d == nil {
		return ""
	}
	return d.Team
}

type DeleteOrganizationTeamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteOrganizationTeamResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteOrganizationTeamResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteOrganizationTeamResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
