// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteServiceTokenRequest struct {
	// The name of the organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The ID of the service token
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteServiceTokenRequest) GetOrganization() string {
	if d == nil {
		return ""
	}
	return d.Organization
}

func (d *DeleteServiceTokenRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteServiceTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteServiceTokenResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteServiceTokenResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteServiceTokenResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
