// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDatabasePostgresCidrRequest struct {
	// The name of the organization the database belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The ID of the IP restriction entry
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteDatabasePostgresCidrRequest) GetOrganization() string {
	if d == nil {
		return ""
	}
	return d.Organization
}

func (d *DeleteDatabasePostgresCidrRequest) GetDatabase() string {
	if d == nil {
		return ""
	}
	return d.Database
}

func (d *DeleteDatabasePostgresCidrRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteDatabasePostgresCidrResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteDatabasePostgresCidrResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteDatabasePostgresCidrResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteDatabasePostgresCidrResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
