// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type DemoteBranchRequest struct {
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

func (d *DemoteBranchRequest) GetOrganization() string {
	if d == nil {
		return ""
	}
	return d.Organization
}

func (d *DemoteBranchRequest) GetDatabase() string {
	if d == nil {
		return ""
	}
	return d.Database
}

func (d *DemoteBranchRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

// DemoteBranchKind - The kind of branch
type DemoteBranchKind string

const (
	DemoteBranchKindMysql      DemoteBranchKind = "mysql"
	DemoteBranchKindPostgresql DemoteBranchKind = "postgresql"
)

func (e DemoteBranchKind) ToPointer() *DemoteBranchKind {
	return &e
}
func (e *DemoteBranchKind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mysql":
		fallthrough
	case "postgresql":
		*e = DemoteBranchKind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemoteBranchKind: %v", v)
	}
}

// DemoteBranchState - The current state of the branch
type DemoteBranchState string

const (
	DemoteBranchStatePending         DemoteBranchState = "pending"
	DemoteBranchStateSleepInProgress DemoteBranchState = "sleep_in_progress"
	DemoteBranchStateSleeping        DemoteBranchState = "sleeping"
	DemoteBranchStateAwakening       DemoteBranchState = "awakening"
	DemoteBranchStateReady           DemoteBranchState = "ready"
)

func (e DemoteBranchState) ToPointer() *DemoteBranchState {
	return &e
}
func (e *DemoteBranchState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "sleep_in_progress":
		fallthrough
	case "sleeping":
		fallthrough
	case "awakening":
		fallthrough
	case "ready":
		*e = DemoteBranchState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DemoteBranchState: %v", v)
	}
}

type DemoteBranchActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (d *DemoteBranchActor) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DemoteBranchActor) GetDisplayName() string {
	if d == nil {
		return ""
	}
	return d.DisplayName
}

func (d *DemoteBranchActor) GetAvatarURL() string {
	if d == nil {
		return ""
	}
	return d.AvatarURL
}

type DemoteBranchRestoredFromBranch struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (d *DemoteBranchRestoredFromBranch) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DemoteBranchRestoredFromBranch) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DemoteBranchRestoredFromBranch) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *DemoteBranchRestoredFromBranch) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *DemoteBranchRestoredFromBranch) GetDeletedAt() string {
	if d == nil {
		return ""
	}
	return d.DeletedAt
}

type DemoteBranchRegionData struct {
	// The ID of the region
	ID string `json:"id"`
	// Provider for the region (ex. AWS)
	Provider string `json:"provider"`
	// Whether or not the region is currently active
	Enabled bool `json:"enabled"`
	// Public IP addresses for the region
	PublicIPAddresses []string `json:"public_ip_addresses"`
	// Name of the region
	DisplayName string `json:"display_name"`
	// Location of the region
	Location string `json:"location"`
	// The slug of the region
	Slug string `json:"slug"`
	// True if the region is the default for new branch creation
	CurrentDefault bool `json:"current_default"`
}

func (d *DemoteBranchRegionData) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DemoteBranchRegionData) GetProvider() string {
	if d == nil {
		return ""
	}
	return d.Provider
}

func (d *DemoteBranchRegionData) GetEnabled() bool {
	if d == nil {
		return false
	}
	return d.Enabled
}

func (d *DemoteBranchRegionData) GetPublicIPAddresses() []string {
	if d == nil {
		return []string{}
	}
	return d.PublicIPAddresses
}

func (d *DemoteBranchRegionData) GetDisplayName() string {
	if d == nil {
		return ""
	}
	return d.DisplayName
}

func (d *DemoteBranchRegionData) GetLocation() string {
	if d == nil {
		return ""
	}
	return d.Location
}

func (d *DemoteBranchRegionData) GetSlug() string {
	if d == nil {
		return ""
	}
	return d.Slug
}

func (d *DemoteBranchRegionData) GetCurrentDefault() bool {
	if d == nil {
		return false
	}
	return d.CurrentDefault
}

// DemoteBranchResponseBody - Returns a development branch
type DemoteBranchResponseBody struct {
	// The ID of the branch
	ID string `json:"id"`
	// The name of the branch
	Name string `json:"name"`
	// When the branch was created
	CreatedAt string `json:"created_at"`
	// When the branch was last updated
	UpdatedAt string `json:"updated_at"`
	// When the branch was deleted
	DeletedAt string `json:"deleted_at"`
	// When a user last marked a backup restore checklist as completed
	RestoreChecklistCompletedAt string `json:"restore_checklist_completed_at"`
	// When the schema for the branch was last updated
	SchemaLastUpdatedAt string `json:"schema_last_updated_at"`
	// The kind of branch
	Kind DemoteBranchKind `json:"kind"`
	// The MySQL address for the branch
	MysqlAddress string `json:"mysql_address"`
	// The address of the MySQL provider for the branch
	MysqlEdgeAddress string `json:"mysql_edge_address"`
	// The current state of the branch
	State DemoteBranchState `json:"state"`
	// True if the branch allows passwords to connect directly to a vtgate, bypassing load balancers
	DirectVtgate bool `json:"direct_vtgate"`
	// The size of the vtgate cluster for the branch
	VtgateSize string `json:"vtgate_size"`
	// The number of vtgate instances in the branch
	VtgateCount float64 `json:"vtgate_count"`
	// The SKU representing the branch's cluster size
	ClusterName string `json:"cluster_name"`
	// IOPS for the cluster
	ClusterIops float64 `json:"cluster_iops"`
	// Whether or not the branch is ready to serve queries
	Ready bool `json:"ready"`
	// Whether or not the schema is ready for queries
	SchemaReady bool `json:"schema_ready"`
	// Whether or not this is a metal database
	Metal bool `json:"metal"`
	// Whether or not the branch is a production branch
	Production bool `json:"production"`
	// Whether or not the branch has safe migrations enabled
	SafeMigrations bool `json:"safe_migrations"`
	// Whether or not the branch is sharded
	Sharded bool `json:"sharded"`
	// The number of shards in the branch
	ShardCount float64 `json:"shard_count"`
	// Whether or not the branch has a stale schema
	StaleSchema        bool                           `json:"stale_schema"`
	Actor              DemoteBranchActor              `json:"actor"`
	RestoredFromBranch DemoteBranchRestoredFromBranch `json:"restored_from_branch"`
	// True if private connections are enabled
	PrivateEdgeConnectivity bool `json:"private_edge_connectivity"`
	// True if the branch has replica servers
	HasReplicas bool `json:"has_replicas"`
	// True if the branch has read-only replica servers
	HasReadOnlyReplicas bool `json:"has_read_only_replicas"`
	// Planetscale app URL for the branch
	HTMLURL string `json:"html_url"`
	// Planetscale API URL for the branch
	URL        string                 `json:"url"`
	RegionData DemoteBranchRegionData `json:"region"`
	// The name of the parent branch from which the branch was created
	ParentBranch string `json:"parent_branch"`
}

func (d *DemoteBranchResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DemoteBranchResponseBody) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DemoteBranchResponseBody) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *DemoteBranchResponseBody) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *DemoteBranchResponseBody) GetDeletedAt() string {
	if d == nil {
		return ""
	}
	return d.DeletedAt
}

func (d *DemoteBranchResponseBody) GetRestoreChecklistCompletedAt() string {
	if d == nil {
		return ""
	}
	return d.RestoreChecklistCompletedAt
}

func (d *DemoteBranchResponseBody) GetSchemaLastUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.SchemaLastUpdatedAt
}

func (d *DemoteBranchResponseBody) GetKind() DemoteBranchKind {
	if d == nil {
		return DemoteBranchKind("")
	}
	return d.Kind
}

func (d *DemoteBranchResponseBody) GetMysqlAddress() string {
	if d == nil {
		return ""
	}
	return d.MysqlAddress
}

func (d *DemoteBranchResponseBody) GetMysqlEdgeAddress() string {
	if d == nil {
		return ""
	}
	return d.MysqlEdgeAddress
}

func (d *DemoteBranchResponseBody) GetState() DemoteBranchState {
	if d == nil {
		return DemoteBranchState("")
	}
	return d.State
}

func (d *DemoteBranchResponseBody) GetDirectVtgate() bool {
	if d == nil {
		return false
	}
	return d.DirectVtgate
}

func (d *DemoteBranchResponseBody) GetVtgateSize() string {
	if d == nil {
		return ""
	}
	return d.VtgateSize
}

func (d *DemoteBranchResponseBody) GetVtgateCount() float64 {
	if d == nil {
		return 0.0
	}
	return d.VtgateCount
}

func (d *DemoteBranchResponseBody) GetClusterName() string {
	if d == nil {
		return ""
	}
	return d.ClusterName
}

func (d *DemoteBranchResponseBody) GetClusterIops() float64 {
	if d == nil {
		return 0.0
	}
	return d.ClusterIops
}

func (d *DemoteBranchResponseBody) GetReady() bool {
	if d == nil {
		return false
	}
	return d.Ready
}

func (d *DemoteBranchResponseBody) GetSchemaReady() bool {
	if d == nil {
		return false
	}
	return d.SchemaReady
}

func (d *DemoteBranchResponseBody) GetMetal() bool {
	if d == nil {
		return false
	}
	return d.Metal
}

func (d *DemoteBranchResponseBody) GetProduction() bool {
	if d == nil {
		return false
	}
	return d.Production
}

func (d *DemoteBranchResponseBody) GetSafeMigrations() bool {
	if d == nil {
		return false
	}
	return d.SafeMigrations
}

func (d *DemoteBranchResponseBody) GetSharded() bool {
	if d == nil {
		return false
	}
	return d.Sharded
}

func (d *DemoteBranchResponseBody) GetShardCount() float64 {
	if d == nil {
		return 0.0
	}
	return d.ShardCount
}

func (d *DemoteBranchResponseBody) GetStaleSchema() bool {
	if d == nil {
		return false
	}
	return d.StaleSchema
}

func (d *DemoteBranchResponseBody) GetActor() DemoteBranchActor {
	if d == nil {
		return DemoteBranchActor{}
	}
	return d.Actor
}

func (d *DemoteBranchResponseBody) GetRestoredFromBranch() DemoteBranchRestoredFromBranch {
	if d == nil {
		return DemoteBranchRestoredFromBranch{}
	}
	return d.RestoredFromBranch
}

func (d *DemoteBranchResponseBody) GetPrivateEdgeConnectivity() bool {
	if d == nil {
		return false
	}
	return d.PrivateEdgeConnectivity
}

func (d *DemoteBranchResponseBody) GetHasReplicas() bool {
	if d == nil {
		return false
	}
	return d.HasReplicas
}

func (d *DemoteBranchResponseBody) GetHasReadOnlyReplicas() bool {
	if d == nil {
		return false
	}
	return d.HasReadOnlyReplicas
}

func (d *DemoteBranchResponseBody) GetHTMLURL() string {
	if d == nil {
		return ""
	}
	return d.HTMLURL
}

func (d *DemoteBranchResponseBody) GetURL() string {
	if d == nil {
		return ""
	}
	return d.URL
}

func (d *DemoteBranchResponseBody) GetRegionData() DemoteBranchRegionData {
	if d == nil {
		return DemoteBranchRegionData{}
	}
	return d.RegionData
}

func (d *DemoteBranchResponseBody) GetParentBranch() string {
	if d == nil {
		return ""
	}
	return d.ParentBranch
}

type DemoteBranchResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a development branch
	Object *DemoteBranchResponseBody
}

func (d DemoteBranchResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DemoteBranchResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (d *DemoteBranchResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DemoteBranchResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DemoteBranchResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DemoteBranchResponse) GetObject() *DemoteBranchResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
