// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type GetBranchChangeRequestRequest struct {
	// The name of the organization that owns this resource
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database that owns this resource
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch that owns this resource
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The ID of the change request
	ChangeRequestID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetBranchChangeRequestRequest) GetOrganization() string {
	if g == nil {
		return ""
	}
	return g.Organization
}

func (g *GetBranchChangeRequestRequest) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

func (g *GetBranchChangeRequestRequest) GetBranch() string {
	if g == nil {
		return ""
	}
	return g.Branch
}

func (g *GetBranchChangeRequestRequest) GetChangeRequestID() string {
	if g == nil {
		return ""
	}
	return g.ChangeRequestID
}

// GetBranchChangeRequestState - The state of the branch change request
type GetBranchChangeRequestState string

const (
	GetBranchChangeRequestStateQueued    GetBranchChangeRequestState = "queued"
	GetBranchChangeRequestStatePending   GetBranchChangeRequestState = "pending"
	GetBranchChangeRequestStateResizing  GetBranchChangeRequestState = "resizing"
	GetBranchChangeRequestStateCanceled  GetBranchChangeRequestState = "canceled"
	GetBranchChangeRequestStateCompleted GetBranchChangeRequestState = "completed"
)

func (e GetBranchChangeRequestState) ToPointer() *GetBranchChangeRequestState {
	return &e
}
func (e *GetBranchChangeRequestState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "queued":
		fallthrough
	case "pending":
		fallthrough
	case "resizing":
		fallthrough
	case "canceled":
		fallthrough
	case "completed":
		*e = GetBranchChangeRequestState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetBranchChangeRequestState: %v", v)
	}
}

type GetBranchChangeRequestActor struct {
	// The ID of the actor
	ID string `json:"id"`
}

func (g *GetBranchChangeRequestActor) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetBranchChangeRequestResponseBody - Returns a branch change request
type GetBranchChangeRequestResponseBody struct {
	// The ID of the branch change request
	ChangeRequestID string `json:"id"`
	// The state of the branch change request
	State GetBranchChangeRequestState `json:"state"`
	Actor GetBranchChangeRequestActor `json:"actor"`
	// The SKU representing the branch cluster
	ClusterName string `json:"cluster_name"`
}

func (g *GetBranchChangeRequestResponseBody) GetChangeRequestID() string {
	if g == nil {
		return ""
	}
	return g.ChangeRequestID
}

func (g *GetBranchChangeRequestResponseBody) GetState() GetBranchChangeRequestState {
	if g == nil {
		return GetBranchChangeRequestState("")
	}
	return g.State
}

func (g *GetBranchChangeRequestResponseBody) GetActor() GetBranchChangeRequestActor {
	if g == nil {
		return GetBranchChangeRequestActor{}
	}
	return g.Actor
}

func (g *GetBranchChangeRequestResponseBody) GetClusterName() string {
	if g == nil {
		return ""
	}
	return g.ClusterName
}

type GetBranchChangeRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a branch change request
	Object *GetBranchChangeRequestResponseBody
}

func (g GetBranchChangeRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetBranchChangeRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetBranchChangeRequestResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetBranchChangeRequestResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetBranchChangeRequestResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetBranchChangeRequestResponse) GetObject() *GetBranchChangeRequestResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
