// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type GetDedicatedReadReplicaRequest struct {
	// Organization name slug from `list_organizations`. Example: `acme`.
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Database name slug from `list_databases`. Example: `app-db`.
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// Branch name from `list_branches`. Example: `main`.
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The name of the dedicated read replica.
	DedicatedReadReplica string `pathParam:"style=simple,explode=false,name=dedicated_read_replica"`
}

func (g *GetDedicatedReadReplicaRequest) GetOrganization() string {
	if g == nil {
		return ""
	}
	return g.Organization
}

func (g *GetDedicatedReadReplicaRequest) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

func (g *GetDedicatedReadReplicaRequest) GetBranch() string {
	if g == nil {
		return ""
	}
	return g.Branch
}

func (g *GetDedicatedReadReplicaRequest) GetDedicatedReadReplica() string {
	if g == nil {
		return ""
	}
	return g.DedicatedReadReplica
}

// GetDedicatedReadReplicaStorageType - The storage type
type GetDedicatedReadReplicaStorageType string

const (
	GetDedicatedReadReplicaStorageTypeGp3               GetDedicatedReadReplicaStorageType = "gp3"
	GetDedicatedReadReplicaStorageTypeIo2               GetDedicatedReadReplicaStorageType = "io2"
	GetDedicatedReadReplicaStorageTypePdSsd             GetDedicatedReadReplicaStorageType = "pd_ssd"
	GetDedicatedReadReplicaStorageTypeHyperdiskBalanced GetDedicatedReadReplicaStorageType = "hyperdisk_balanced"
	GetDedicatedReadReplicaStorageTypePremiumV2Lrs      GetDedicatedReadReplicaStorageType = "premium_v2_lrs"
)

func (e GetDedicatedReadReplicaStorageType) ToPointer() *GetDedicatedReadReplicaStorageType {
	return &e
}
func (e *GetDedicatedReadReplicaStorageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "gp3":
		fallthrough
	case "io2":
		fallthrough
	case "pd_ssd":
		fallthrough
	case "hyperdisk_balanced":
		fallthrough
	case "premium_v2_lrs":
		*e = GetDedicatedReadReplicaStorageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDedicatedReadReplicaStorageType: %v", v)
	}
}

// GetDedicatedReadReplicaResponseBody - Returns the dedicated read replica
type GetDedicatedReadReplicaResponseBody struct {
	// The name of the dedicated read replica.
	Name string `json:"name"`
	// The state of the dedicated read replica: pending, ready, or deleting
	State string `json:"state"`
	// The number of instances serving reads in this dedicated read replica.
	Replicas int64 `json:"replicas"`
	// The cluster size SKU, e.g. `PS_10_AWS_ARM`. Defaults to the primary's cluster size.
	ClusterSize string `json:"cluster_name"`
	// The database connection host for the dedicated read replica.
	AccessHostURL string `json:"access_host_url"`
	// The private database connection host for the dedicated read replica.
	PrivateAccessHostURL string `json:"private_access_host_url"`
	// The service name to set up private connectivity for the dedicated read replica.
	PrivateConnectionServiceName *string `json:"private_connection_service_name"`
	// The minimum storage size in bytes
	MinimumStorageBytes *int64 `json:"minimum_storage_bytes"`
	// The maximum storage size in bytes
	MaximumStorageBytes *int64 `json:"maximum_storage_bytes"`
	// Whether storage autoscaling is enabled
	StorageAutoscaling *bool `json:"storage_autoscaling"`
	// The storage type
	StorageType *GetDedicatedReadReplicaStorageType `json:"storage_type"`
	// The storage IOPS
	StorageIops *int64 `json:"storage_iops"`
	// The storage throughput in MiB/s
	StorageThroughputMibs *int64 `json:"storage_throughput_mibs"`
	// When volume modifications will be allowed again
	VolumeModificationsBlockedUntil *string `json:"volume_modifications_blocked_until"`
	// The region slug for the dedicated read replica, e.g. `us-east`. The dedicated read replica can run in a different region than the primary.
	Region string `json:"region_slug"`
}

func (g *GetDedicatedReadReplicaResponseBody) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetDedicatedReadReplicaResponseBody) GetState() string {
	if g == nil {
		return ""
	}
	return g.State
}

func (g *GetDedicatedReadReplicaResponseBody) GetReplicas() int64 {
	if g == nil {
		return 0
	}
	return g.Replicas
}

func (g *GetDedicatedReadReplicaResponseBody) GetClusterSize() string {
	if g == nil {
		return ""
	}
	return g.ClusterSize
}

func (g *GetDedicatedReadReplicaResponseBody) GetAccessHostURL() string {
	if g == nil {
		return ""
	}
	return g.AccessHostURL
}

func (g *GetDedicatedReadReplicaResponseBody) GetPrivateAccessHostURL() string {
	if g == nil {
		return ""
	}
	return g.PrivateAccessHostURL
}

func (g *GetDedicatedReadReplicaResponseBody) GetPrivateConnectionServiceName() *string {
	if g == nil {
		return nil
	}
	return g.PrivateConnectionServiceName
}

func (g *GetDedicatedReadReplicaResponseBody) GetMinimumStorageBytes() *int64 {
	if g == nil {
		return nil
	}
	return g.MinimumStorageBytes
}

func (g *GetDedicatedReadReplicaResponseBody) GetMaximumStorageBytes() *int64 {
	if g == nil {
		return nil
	}
	return g.MaximumStorageBytes
}

func (g *GetDedicatedReadReplicaResponseBody) GetStorageAutoscaling() *bool {
	if g == nil {
		return nil
	}
	return g.StorageAutoscaling
}

func (g *GetDedicatedReadReplicaResponseBody) GetStorageType() *GetDedicatedReadReplicaStorageType {
	if g == nil {
		return nil
	}
	return g.StorageType
}

func (g *GetDedicatedReadReplicaResponseBody) GetStorageIops() *int64 {
	if g == nil {
		return nil
	}
	return g.StorageIops
}

func (g *GetDedicatedReadReplicaResponseBody) GetStorageThroughputMibs() *int64 {
	if g == nil {
		return nil
	}
	return g.StorageThroughputMibs
}

func (g *GetDedicatedReadReplicaResponseBody) GetVolumeModificationsBlockedUntil() *string {
	if g == nil {
		return nil
	}
	return g.VolumeModificationsBlockedUntil
}

func (g *GetDedicatedReadReplicaResponseBody) GetRegion() string {
	if g == nil {
		return ""
	}
	return g.Region
}

type GetDedicatedReadReplicaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the dedicated read replica
	Object *GetDedicatedReadReplicaResponseBody
}

func (g GetDedicatedReadReplicaResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDedicatedReadReplicaResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetDedicatedReadReplicaResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDedicatedReadReplicaResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDedicatedReadReplicaResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDedicatedReadReplicaResponse) GetObject() *GetDedicatedReadReplicaResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
