// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type GetDeployQueueRequest struct {
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
}

func (g *GetDeployQueueRequest) GetOrganization() string {
	if g == nil {
		return ""
	}
	return g.Organization
}

func (g *GetDeployQueueRequest) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

// GetDeployQueueState - The state the deployment is in
type GetDeployQueueState string

const (
	GetDeployQueueStatePending                 GetDeployQueueState = "pending"
	GetDeployQueueStateReady                   GetDeployQueueState = "ready"
	GetDeployQueueStateNoChanges               GetDeployQueueState = "no_changes"
	GetDeployQueueStateQueued                  GetDeployQueueState = "queued"
	GetDeployQueueStateSubmitting              GetDeployQueueState = "submitting"
	GetDeployQueueStateInProgress              GetDeployQueueState = "in_progress"
	GetDeployQueueStatePendingCutover          GetDeployQueueState = "pending_cutover"
	GetDeployQueueStateInProgressVschema       GetDeployQueueState = "in_progress_vschema"
	GetDeployQueueStateInProgressCancel        GetDeployQueueState = "in_progress_cancel"
	GetDeployQueueStateInProgressCutover       GetDeployQueueState = "in_progress_cutover"
	GetDeployQueueStateComplete                GetDeployQueueState = "complete"
	GetDeployQueueStateCompleteCancel          GetDeployQueueState = "complete_cancel"
	GetDeployQueueStateCompleteError           GetDeployQueueState = "complete_error"
	GetDeployQueueStateCompletePendingRevert   GetDeployQueueState = "complete_pending_revert"
	GetDeployQueueStateInProgressRevert        GetDeployQueueState = "in_progress_revert"
	GetDeployQueueStateInProgressRevertVschema GetDeployQueueState = "in_progress_revert_vschema"
	GetDeployQueueStateCompleteRevert          GetDeployQueueState = "complete_revert"
	GetDeployQueueStateCompleteRevertError     GetDeployQueueState = "complete_revert_error"
	GetDeployQueueStateCancelled               GetDeployQueueState = "cancelled"
	GetDeployQueueStateError                   GetDeployQueueState = "error"
)

func (e GetDeployQueueState) ToPointer() *GetDeployQueueState {
	return &e
}
func (e *GetDeployQueueState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "ready":
		fallthrough
	case "no_changes":
		fallthrough
	case "queued":
		fallthrough
	case "submitting":
		fallthrough
	case "in_progress":
		fallthrough
	case "pending_cutover":
		fallthrough
	case "in_progress_vschema":
		fallthrough
	case "in_progress_cancel":
		fallthrough
	case "in_progress_cutover":
		fallthrough
	case "complete":
		fallthrough
	case "complete_cancel":
		fallthrough
	case "complete_error":
		fallthrough
	case "complete_pending_revert":
		fallthrough
	case "in_progress_revert":
		fallthrough
	case "in_progress_revert_vschema":
		fallthrough
	case "complete_revert":
		fallthrough
	case "complete_revert_error":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = GetDeployQueueState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeployQueueState: %v", v)
	}
}

// GetDeployQueueDeployOperationState - The state of the deploy operation
type GetDeployQueueDeployOperationState string

const (
	GetDeployQueueDeployOperationStatePending    GetDeployQueueDeployOperationState = "pending"
	GetDeployQueueDeployOperationStateQueued     GetDeployQueueDeployOperationState = "queued"
	GetDeployQueueDeployOperationStateInProgress GetDeployQueueDeployOperationState = "in_progress"
	GetDeployQueueDeployOperationStateComplete   GetDeployQueueDeployOperationState = "complete"
	GetDeployQueueDeployOperationStateCancelled  GetDeployQueueDeployOperationState = "cancelled"
	GetDeployQueueDeployOperationStateError      GetDeployQueueDeployOperationState = "error"
)

func (e GetDeployQueueDeployOperationState) ToPointer() *GetDeployQueueDeployOperationState {
	return &e
}
func (e *GetDeployQueueDeployOperationState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "queued":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = GetDeployQueueDeployOperationState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeployQueueDeployOperationState: %v", v)
	}
}

type GetDeployQueueDeployOperation struct {
	// The ID for the deploy operation
	ID string `json:"id"`
	// The state of the deploy operation
	State GetDeployQueueDeployOperationState `json:"state"`
	// The keyspace modified by the deploy operation
	KeyspaceName string `json:"keyspace_name"`
	// The name of the table modifed by the deploy operation
	TableName string `json:"table_name"`
	// The operation name of the deploy operation
	OperationName string `json:"operation_name"`
	// The estimated seconds until completion for the deploy operation
	EtaSeconds float64 `json:"eta_seconds"`
	// The percent completion for the deploy operation
	ProgressPercentage float64 `json:"progress_percentage"`
	// A link to documentation explaining the deploy error, if present
	DeployErrorDocsURL string `json:"deploy_error_docs_url"`
	// The DDL statement for the deploy operation
	DdlStatement string `json:"ddl_statement"`
	// A syntax-highlighted DDL statement for the deploy operation
	SyntaxHighlightedDdl string `json:"syntax_highlighted_ddl"`
	// When the deploy operation was created
	CreatedAt string `json:"created_at"`
	// When the deploy operation was last updated
	UpdatedAt string `json:"updated_at"`
	// When the deploy operation was last throttled
	ThrottledAt string `json:"throttled_at"`
	// Whether or not the deploy operation is capable of dropping data
	CanDropData bool `json:"can_drop_data"`
	// Whether or not the table modified by the deploy operation is currently locked
	TableLocked bool `json:"table_locked"`
	// Whether or not the table modified by the deploy operation was recently used
	TableRecentlyUsed bool `json:"table_recently_used"`
	// When the table modified by the deploy operation was last used
	TableRecentlyUsedAt string `json:"table_recently_used_at"`
	// Names of foreign keys removed by this operation
	RemovedForeignKeyNames []string `json:"removed_foreign_key_names"`
	// Deploy errors for the deploy operation
	DeployErrors string `json:"deploy_errors"`
}

func (g *GetDeployQueueDeployOperation) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueDeployOperation) GetState() GetDeployQueueDeployOperationState {
	if g == nil {
		return GetDeployQueueDeployOperationState("")
	}
	return g.State
}

func (g *GetDeployQueueDeployOperation) GetKeyspaceName() string {
	if g == nil {
		return ""
	}
	return g.KeyspaceName
}

func (g *GetDeployQueueDeployOperation) GetTableName() string {
	if g == nil {
		return ""
	}
	return g.TableName
}

func (g *GetDeployQueueDeployOperation) GetOperationName() string {
	if g == nil {
		return ""
	}
	return g.OperationName
}

func (g *GetDeployQueueDeployOperation) GetEtaSeconds() float64 {
	if g == nil {
		return 0.0
	}
	return g.EtaSeconds
}

func (g *GetDeployQueueDeployOperation) GetProgressPercentage() float64 {
	if g == nil {
		return 0.0
	}
	return g.ProgressPercentage
}

func (g *GetDeployQueueDeployOperation) GetDeployErrorDocsURL() string {
	if g == nil {
		return ""
	}
	return g.DeployErrorDocsURL
}

func (g *GetDeployQueueDeployOperation) GetDdlStatement() string {
	if g == nil {
		return ""
	}
	return g.DdlStatement
}

func (g *GetDeployQueueDeployOperation) GetSyntaxHighlightedDdl() string {
	if g == nil {
		return ""
	}
	return g.SyntaxHighlightedDdl
}

func (g *GetDeployQueueDeployOperation) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetDeployQueueDeployOperation) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetDeployQueueDeployOperation) GetThrottledAt() string {
	if g == nil {
		return ""
	}
	return g.ThrottledAt
}

func (g *GetDeployQueueDeployOperation) GetCanDropData() bool {
	if g == nil {
		return false
	}
	return g.CanDropData
}

func (g *GetDeployQueueDeployOperation) GetTableLocked() bool {
	if g == nil {
		return false
	}
	return g.TableLocked
}

func (g *GetDeployQueueDeployOperation) GetTableRecentlyUsed() bool {
	if g == nil {
		return false
	}
	return g.TableRecentlyUsed
}

func (g *GetDeployQueueDeployOperation) GetTableRecentlyUsedAt() string {
	if g == nil {
		return ""
	}
	return g.TableRecentlyUsedAt
}

func (g *GetDeployQueueDeployOperation) GetRemovedForeignKeyNames() []string {
	if g == nil {
		return []string{}
	}
	return g.RemovedForeignKeyNames
}

func (g *GetDeployQueueDeployOperation) GetDeployErrors() string {
	if g == nil {
		return ""
	}
	return g.DeployErrors
}

// GetDeployQueueDeployOperationSummaryState - The state of the deploy operation summary
type GetDeployQueueDeployOperationSummaryState string

const (
	GetDeployQueueDeployOperationSummaryStatePending    GetDeployQueueDeployOperationSummaryState = "pending"
	GetDeployQueueDeployOperationSummaryStateInProgress GetDeployQueueDeployOperationSummaryState = "in_progress"
	GetDeployQueueDeployOperationSummaryStateComplete   GetDeployQueueDeployOperationSummaryState = "complete"
	GetDeployQueueDeployOperationSummaryStateCancelled  GetDeployQueueDeployOperationSummaryState = "cancelled"
	GetDeployQueueDeployOperationSummaryStateError      GetDeployQueueDeployOperationSummaryState = "error"
)

func (e GetDeployQueueDeployOperationSummaryState) ToPointer() *GetDeployQueueDeployOperationSummaryState {
	return &e
}
func (e *GetDeployQueueDeployOperationSummaryState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = GetDeployQueueDeployOperationSummaryState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeployQueueDeployOperationSummaryState: %v", v)
	}
}

// GetDeployQueueOperationState - The state of the deploy operation
type GetDeployQueueOperationState string

const (
	GetDeployQueueOperationStatePending    GetDeployQueueOperationState = "pending"
	GetDeployQueueOperationStateQueued     GetDeployQueueOperationState = "queued"
	GetDeployQueueOperationStateInProgress GetDeployQueueOperationState = "in_progress"
	GetDeployQueueOperationStateComplete   GetDeployQueueOperationState = "complete"
	GetDeployQueueOperationStateCancelled  GetDeployQueueOperationState = "cancelled"
	GetDeployQueueOperationStateError      GetDeployQueueOperationState = "error"
)

func (e GetDeployQueueOperationState) ToPointer() *GetDeployQueueOperationState {
	return &e
}
func (e *GetDeployQueueOperationState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "queued":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = GetDeployQueueOperationState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDeployQueueOperationState: %v", v)
	}
}

type GetDeployQueueOperation struct {
	// The ID for the deploy operation
	ID string `json:"id"`
	// The shard the deploy operation is being performed on
	Shard string `json:"shard"`
	// The state of the deploy operation
	State GetDeployQueueOperationState `json:"state"`
	// The percent completion for the deploy operation
	ProgressPercentage float64 `json:"progress_percentage"`
	// The estimated seconds until completion for the deploy operation
	EtaSeconds int64 `json:"eta_seconds"`
}

func (g *GetDeployQueueOperation) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueOperation) GetShard() string {
	if g == nil {
		return ""
	}
	return g.Shard
}

func (g *GetDeployQueueOperation) GetState() GetDeployQueueOperationState {
	if g == nil {
		return GetDeployQueueOperationState("")
	}
	return g.State
}

func (g *GetDeployQueueOperation) GetProgressPercentage() float64 {
	if g == nil {
		return 0.0
	}
	return g.ProgressPercentage
}

func (g *GetDeployQueueOperation) GetEtaSeconds() int64 {
	if g == nil {
		return 0
	}
	return g.EtaSeconds
}

type GetDeployQueueDeployOperationSummary struct {
	// The ID for the deploy operation summary
	ID string `json:"id"`
	// When the deploy operation summary was created
	CreatedAt string `json:"created_at"`
	// Deploy errors for the deploy operation summary
	DeployErrors string `json:"deploy_errors"`
	// The DDL statement for the deploy operation summary
	DdlStatement string `json:"ddl_statement"`
	// The estimated seconds until completion for the deploy operation summary
	EtaSeconds int64 `json:"eta_seconds"`
	// The keyspace modified by the deploy operation summary
	KeyspaceName string `json:"keyspace_name"`
	// The operation name of the deploy operation summary
	OperationName string `json:"operation_name"`
	// The percent completion for the deploy operation summary
	ProgressPercentage float64 `json:"progress_percentage"`
	// The state of the deploy operation summary
	State GetDeployQueueDeployOperationSummaryState `json:"state"`
	// A syntax-highlighted DDL statement for the deploy operation summary
	SyntaxHighlightedDdl string `json:"syntax_highlighted_ddl"`
	// The name of the table modifed by the deploy operation summary
	TableName string `json:"table_name"`
	// When the table modified by the deploy operation summary was last used
	TableRecentlyUsedAt string `json:"table_recently_used_at"`
	// When the deploy operation summary was last throttled
	ThrottledAt string `json:"throttled_at"`
	// Names of foreign keys removed by this operation summary
	RemovedForeignKeyNames []string `json:"removed_foreign_key_names"`
	// The number of shards in the keyspace modified by the deploy operation summary
	ShardCount int64 `json:"shard_count"`
	// Names of shards in the keyspace modified by the deploy operation summary
	ShardNames []string `json:"shard_names"`
	// Whether or not the deploy operation summary is capable of dropping data
	CanDropData bool `json:"can_drop_data"`
	// Whether or not the table modified by the deploy operation summary was recently used
	TableRecentlyUsed bool `json:"table_recently_used"`
	// Whether or not the keyspace modified by the deploy operation summary is sharded
	Sharded    bool                      `json:"sharded"`
	Operations []GetDeployQueueOperation `json:"operations"`
}

func (g *GetDeployQueueDeployOperationSummary) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueDeployOperationSummary) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetDeployQueueDeployOperationSummary) GetDeployErrors() string {
	if g == nil {
		return ""
	}
	return g.DeployErrors
}

func (g *GetDeployQueueDeployOperationSummary) GetDdlStatement() string {
	if g == nil {
		return ""
	}
	return g.DdlStatement
}

func (g *GetDeployQueueDeployOperationSummary) GetEtaSeconds() int64 {
	if g == nil {
		return 0
	}
	return g.EtaSeconds
}

func (g *GetDeployQueueDeployOperationSummary) GetKeyspaceName() string {
	if g == nil {
		return ""
	}
	return g.KeyspaceName
}

func (g *GetDeployQueueDeployOperationSummary) GetOperationName() string {
	if g == nil {
		return ""
	}
	return g.OperationName
}

func (g *GetDeployQueueDeployOperationSummary) GetProgressPercentage() float64 {
	if g == nil {
		return 0.0
	}
	return g.ProgressPercentage
}

func (g *GetDeployQueueDeployOperationSummary) GetState() GetDeployQueueDeployOperationSummaryState {
	if g == nil {
		return GetDeployQueueDeployOperationSummaryState("")
	}
	return g.State
}

func (g *GetDeployQueueDeployOperationSummary) GetSyntaxHighlightedDdl() string {
	if g == nil {
		return ""
	}
	return g.SyntaxHighlightedDdl
}

func (g *GetDeployQueueDeployOperationSummary) GetTableName() string {
	if g == nil {
		return ""
	}
	return g.TableName
}

func (g *GetDeployQueueDeployOperationSummary) GetTableRecentlyUsedAt() string {
	if g == nil {
		return ""
	}
	return g.TableRecentlyUsedAt
}

func (g *GetDeployQueueDeployOperationSummary) GetThrottledAt() string {
	if g == nil {
		return ""
	}
	return g.ThrottledAt
}

func (g *GetDeployQueueDeployOperationSummary) GetRemovedForeignKeyNames() []string {
	if g == nil {
		return []string{}
	}
	return g.RemovedForeignKeyNames
}

func (g *GetDeployQueueDeployOperationSummary) GetShardCount() int64 {
	if g == nil {
		return 0
	}
	return g.ShardCount
}

func (g *GetDeployQueueDeployOperationSummary) GetShardNames() []string {
	if g == nil {
		return []string{}
	}
	return g.ShardNames
}

func (g *GetDeployQueueDeployOperationSummary) GetCanDropData() bool {
	if g == nil {
		return false
	}
	return g.CanDropData
}

func (g *GetDeployQueueDeployOperationSummary) GetTableRecentlyUsed() bool {
	if g == nil {
		return false
	}
	return g.TableRecentlyUsed
}

func (g *GetDeployQueueDeployOperationSummary) GetSharded() bool {
	if g == nil {
		return false
	}
	return g.Sharded
}

func (g *GetDeployQueueDeployOperationSummary) GetOperations() []GetDeployQueueOperation {
	if g == nil {
		return []GetDeployQueueOperation{}
	}
	return g.Operations
}

type GetDeployQueueActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (g *GetDeployQueueActor) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueActor) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetDeployQueueActor) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

type GetDeployQueueCutoverActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (g *GetDeployQueueCutoverActor) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueCutoverActor) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetDeployQueueCutoverActor) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

type GetDeployQueueCancelledActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (g *GetDeployQueueCancelledActor) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueCancelledActor) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetDeployQueueCancelledActor) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

type GetDeployQueueData struct {
	// The ID of the deployment
	ID string `json:"id"`
	// Whether or not to automatically cutover once deployment is finished
	AutoCutover bool `json:"auto_cutover"`
	// Whether or not to automatically delete the head branch once deployment is finished
	AutoDeleteBranch bool `json:"auto_delete_branch"`
	// When the deployment was created
	CreatedAt string `json:"created_at"`
	// When the cutover for the deployment was initiated
	CutoverAt string `json:"cutover_at"`
	// Whether or not the deployment cutover will expire soon
	CutoverExpiring bool `json:"cutover_expiring"`
	// Deploy check errors for the deployment
	DeployCheckErrors string `json:"deploy_check_errors"`
	// When the deployment was finished
	FinishedAt string `json:"finished_at"`
	// When the deployment was queued
	QueuedAt string `json:"queued_at"`
	// When the deployment was ready for cutover
	ReadyToCutoverAt string `json:"ready_to_cutover_at"`
	// When the deployment was started
	StartedAt string `json:"started_at"`
	// The state the deployment is in
	State GetDeployQueueState `json:"state"`
	// When the deployment was submitted
	SubmittedAt string `json:"submitted_at"`
	// When the deployment was last updated
	UpdatedAt string `json:"updated_at"`
	// The name of the base branch the deployment will be merged into
	IntoBranch string `json:"into_branch"`
	// The number of the deploy request associated with this deployment
	DeployRequestNumber int64 `json:"deploy_request_number"`
	// Whether the deployment is deployable
	Deployable bool `json:"deployable"`
	// The deployments ahead of this one in the queue
	PrecedingDeployments     []map[string]any                       `json:"preceding_deployments"`
	DeployOperations         []GetDeployQueueDeployOperation        `json:"deploy_operations"`
	DeployOperationSummaries []GetDeployQueueDeployOperationSummary `json:"deploy_operation_summaries"`
	// Schema lint errors preventing the deployment from completing
	LintErrors []map[string]any `json:"lint_errors"`
	// The schema dependencies that must be satisfied
	SequentialDiffDependencies []map[string]any `json:"sequential_diff_dependencies"`
	// Lookup Vitess index operations
	LookupVindexOperations []map[string]any `json:"lookup_vindex_operations"`
	// Deployment throttling configurations
	ThrottlerConfigurations []map[string]any `json:"throttler_configurations"`
	// The request to revert the schema operations in this deployment
	DeploymentRevertRequest map[string]any               `json:"deployment_revert_request"`
	Actor                   GetDeployQueueActor          `json:"actor"`
	CutoverActor            GetDeployQueueCutoverActor   `json:"cutover_actor"`
	CancelledActor          GetDeployQueueCancelledActor `json:"cancelled_actor"`
	// When the schema was last updated for the deployment
	SchemaLastUpdatedAt string `json:"schema_last_updated_at"`
	// Whether or not the deployment has a table locked
	TableLocked bool `json:"table_locked"`
	// The name of he table that is locked by the deployment
	LockedTableName string `json:"locked_table_name"`
	// Whether or not the deployment is an instant DDL deployment
	InstantDdl bool `json:"instant_ddl"`
	// Whether or not the deployment is eligible for instant DDL
	InstantDdlEligible bool `json:"instant_ddl_eligible"`
}

func (g *GetDeployQueueData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeployQueueData) GetAutoCutover() bool {
	if g == nil {
		return false
	}
	return g.AutoCutover
}

func (g *GetDeployQueueData) GetAutoDeleteBranch() bool {
	if g == nil {
		return false
	}
	return g.AutoDeleteBranch
}

func (g *GetDeployQueueData) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetDeployQueueData) GetCutoverAt() string {
	if g == nil {
		return ""
	}
	return g.CutoverAt
}

func (g *GetDeployQueueData) GetCutoverExpiring() bool {
	if g == nil {
		return false
	}
	return g.CutoverExpiring
}

func (g *GetDeployQueueData) GetDeployCheckErrors() string {
	if g == nil {
		return ""
	}
	return g.DeployCheckErrors
}

func (g *GetDeployQueueData) GetFinishedAt() string {
	if g == nil {
		return ""
	}
	return g.FinishedAt
}

func (g *GetDeployQueueData) GetQueuedAt() string {
	if g == nil {
		return ""
	}
	return g.QueuedAt
}

func (g *GetDeployQueueData) GetReadyToCutoverAt() string {
	if g == nil {
		return ""
	}
	return g.ReadyToCutoverAt
}

func (g *GetDeployQueueData) GetStartedAt() string {
	if g == nil {
		return ""
	}
	return g.StartedAt
}

func (g *GetDeployQueueData) GetState() GetDeployQueueState {
	if g == nil {
		return GetDeployQueueState("")
	}
	return g.State
}

func (g *GetDeployQueueData) GetSubmittedAt() string {
	if g == nil {
		return ""
	}
	return g.SubmittedAt
}

func (g *GetDeployQueueData) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetDeployQueueData) GetIntoBranch() string {
	if g == nil {
		return ""
	}
	return g.IntoBranch
}

func (g *GetDeployQueueData) GetDeployRequestNumber() int64 {
	if g == nil {
		return 0
	}
	return g.DeployRequestNumber
}

func (g *GetDeployQueueData) GetDeployable() bool {
	if g == nil {
		return false
	}
	return g.Deployable
}

func (g *GetDeployQueueData) GetPrecedingDeployments() []map[string]any {
	if g == nil {
		return []map[string]any{}
	}
	return g.PrecedingDeployments
}

func (g *GetDeployQueueData) GetDeployOperations() []GetDeployQueueDeployOperation {
	if g == nil {
		return []GetDeployQueueDeployOperation{}
	}
	return g.DeployOperations
}

func (g *GetDeployQueueData) GetDeployOperationSummaries() []GetDeployQueueDeployOperationSummary {
	if g == nil {
		return []GetDeployQueueDeployOperationSummary{}
	}
	return g.DeployOperationSummaries
}

func (g *GetDeployQueueData) GetLintErrors() []map[string]any {
	if g == nil {
		return []map[string]any{}
	}
	return g.LintErrors
}

func (g *GetDeployQueueData) GetSequentialDiffDependencies() []map[string]any {
	if g == nil {
		return []map[string]any{}
	}
	return g.SequentialDiffDependencies
}

func (g *GetDeployQueueData) GetLookupVindexOperations() []map[string]any {
	if g == nil {
		return []map[string]any{}
	}
	return g.LookupVindexOperations
}

func (g *GetDeployQueueData) GetThrottlerConfigurations() []map[string]any {
	if g == nil {
		return []map[string]any{}
	}
	return g.ThrottlerConfigurations
}

func (g *GetDeployQueueData) GetDeploymentRevertRequest() map[string]any {
	if g == nil {
		return map[string]any{}
	}
	return g.DeploymentRevertRequest
}

func (g *GetDeployQueueData) GetActor() GetDeployQueueActor {
	if g == nil {
		return GetDeployQueueActor{}
	}
	return g.Actor
}

func (g *GetDeployQueueData) GetCutoverActor() GetDeployQueueCutoverActor {
	if g == nil {
		return GetDeployQueueCutoverActor{}
	}
	return g.CutoverActor
}

func (g *GetDeployQueueData) GetCancelledActor() GetDeployQueueCancelledActor {
	if g == nil {
		return GetDeployQueueCancelledActor{}
	}
	return g.CancelledActor
}

func (g *GetDeployQueueData) GetSchemaLastUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.SchemaLastUpdatedAt
}

func (g *GetDeployQueueData) GetTableLocked() bool {
	if g == nil {
		return false
	}
	return g.TableLocked
}

func (g *GetDeployQueueData) GetLockedTableName() string {
	if g == nil {
		return ""
	}
	return g.LockedTableName
}

func (g *GetDeployQueueData) GetInstantDdl() bool {
	if g == nil {
		return false
	}
	return g.InstantDdl
}

func (g *GetDeployQueueData) GetInstantDdlEligible() bool {
	if g == nil {
		return false
	}
	return g.InstantDdlEligible
}

// GetDeployQueueResponseBody - Returns the deploy queue for a database
type GetDeployQueueResponseBody struct {
	// The current page number
	CurrentPage int64 `json:"current_page"`
	// The next page number
	NextPage int64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage int64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string               `json:"prev_page_url"`
	Data        []GetDeployQueueData `json:"data"`
}

func (g *GetDeployQueueResponseBody) GetCurrentPage() int64 {
	if g == nil {
		return 0
	}
	return g.CurrentPage
}

func (g *GetDeployQueueResponseBody) GetNextPage() int64 {
	if g == nil {
		return 0
	}
	return g.NextPage
}

func (g *GetDeployQueueResponseBody) GetNextPageURL() string {
	if g == nil {
		return ""
	}
	return g.NextPageURL
}

func (g *GetDeployQueueResponseBody) GetPrevPage() int64 {
	if g == nil {
		return 0
	}
	return g.PrevPage
}

func (g *GetDeployQueueResponseBody) GetPrevPageURL() string {
	if g == nil {
		return ""
	}
	return g.PrevPageURL
}

func (g *GetDeployQueueResponseBody) GetData() []GetDeployQueueData {
	if g == nil {
		return []GetDeployQueueData{}
	}
	return g.Data
}

type GetDeployQueueResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the deploy queue for a database
	Object *GetDeployQueueResponseBody
}

func (g GetDeployQueueResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeployQueueResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (g *GetDeployQueueResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDeployQueueResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDeployQueueResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDeployQueueResponse) GetObject() *GetDeployQueueResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
