// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/types"
	"net/http"
)

type GetNekiSidecarParametersRequest struct {
	// Organization name slug from `list_organizations`. Example: `acme`.
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Database name slug from `list_databases`. Example: `app-db`.
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// Branch name from `list_branches`. Example: `main`.
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The configuration profile name.
	Sidecar string `pathParam:"style=simple,explode=false,name=sidecar"`
	// Include internal parameters. Terraform always excludes them.
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	internal *bool `const:"false" queryParam:"style=form,explode=true,name=internal"`
	// Desired effective parameter values nested by namespace. The SDK hook uses the prior Terraform value for reconciliation and removes this query parameter before sending the API request.
	Parameters map[string]map[string]string `queryParam:"serialization=json,name=parameters"`
}

func (g GetNekiSidecarParametersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetNekiSidecarParametersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetNekiSidecarParametersRequest) GetOrganization() string {
	if g == nil {
		return ""
	}
	return g.Organization
}

func (g *GetNekiSidecarParametersRequest) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

func (g *GetNekiSidecarParametersRequest) GetBranch() string {
	if g == nil {
		return ""
	}
	return g.Branch
}

func (g *GetNekiSidecarParametersRequest) GetSidecar() string {
	if g == nil {
		return ""
	}
	return g.Sidecar
}

func (g *GetNekiSidecarParametersRequest) GetInternal() *bool {
	return types.Pointer(false)
}

func (g *GetNekiSidecarParametersRequest) GetParameters() map[string]map[string]string {
	if g == nil {
		return nil
	}
	return g.Parameters
}

// GetNekiSidecarParametersResponseBody - Returns reconciled effective sidecar parameter values for Terraform.
type GetNekiSidecarParametersResponseBody struct {
	// Managed effective sidecar parameter values nested by namespace. Remote non-default values are adopted during reads.
	Parameters map[string]map[string]string `json:"parameters"`
}

func (g *GetNekiSidecarParametersResponseBody) GetParameters() map[string]map[string]string {
	if g == nil {
		return nil
	}
	return g.Parameters
}

type GetNekiSidecarParametersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns reconciled effective sidecar parameter values for Terraform.
	Object *GetNekiSidecarParametersResponseBody
}

func (g GetNekiSidecarParametersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetNekiSidecarParametersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetNekiSidecarParametersResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNekiSidecarParametersResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNekiSidecarParametersResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNekiSidecarParametersResponse) GetObject() *GetNekiSidecarParametersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
