// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type GetOrganizationTeamRequest struct {
	// The name of the organization
	OrganizationName string `pathParam:"style=simple,explode=false,name=organization_name"`
	// The slug of the team
	TeamSlug string `pathParam:"style=simple,explode=false,name=team_slug"`
}

func (g *GetOrganizationTeamRequest) GetOrganizationName() string {
	if g == nil {
		return ""
	}
	return g.OrganizationName
}

func (g *GetOrganizationTeamRequest) GetTeamSlug() string {
	if g == nil {
		return ""
	}
	return g.TeamSlug
}

type GetOrganizationTeamCreator struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (g *GetOrganizationTeamCreator) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetOrganizationTeamCreator) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetOrganizationTeamCreator) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

type GetOrganizationTeamDefaultOrganization struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (g *GetOrganizationTeamDefaultOrganization) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetOrganizationTeamDefaultOrganization) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetOrganizationTeamDefaultOrganization) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetOrganizationTeamDefaultOrganization) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetOrganizationTeamDefaultOrganization) GetDeletedAt() string {
	if g == nil {
		return ""
	}
	return g.DeletedAt
}

type GetOrganizationTeamMember struct {
	// The ID of the user
	ID string `json:"id"`
	// The display name of the user
	DisplayName string `json:"display_name"`
	// The name of the user
	Name string `json:"name"`
	// The email of the user
	Email string `json:"email"`
	// The URL source of the user's avatar
	AvatarURL string `json:"avatar_url"`
	// When the user was created
	CreatedAt string `json:"created_at"`
	// When the user was last updated
	UpdatedAt string `json:"updated_at"`
	// Whether or not the user has configured two factor authentication
	TwoFactorAuthConfigured bool                                   `json:"two_factor_auth_configured"`
	DefaultOrganization     GetOrganizationTeamDefaultOrganization `json:"default_organization"`
	// Whether or not the user is managed by SSO
	Sso bool `json:"sso"`
	// Whether or not the user is managed by an authentication provider
	Managed bool `json:"managed"`
	// Whether or not the user is managed by a SSO directory
	DirectoryManaged bool `json:"directory_managed"`
	// Whether or not the user is verified by email
	EmailVerified bool `json:"email_verified"`
}

func (g *GetOrganizationTeamMember) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetOrganizationTeamMember) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetOrganizationTeamMember) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetOrganizationTeamMember) GetEmail() string {
	if g == nil {
		return ""
	}
	return g.Email
}

func (g *GetOrganizationTeamMember) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

func (g *GetOrganizationTeamMember) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetOrganizationTeamMember) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetOrganizationTeamMember) GetTwoFactorAuthConfigured() bool {
	if g == nil {
		return false
	}
	return g.TwoFactorAuthConfigured
}

func (g *GetOrganizationTeamMember) GetDefaultOrganization() GetOrganizationTeamDefaultOrganization {
	if g == nil {
		return GetOrganizationTeamDefaultOrganization{}
	}
	return g.DefaultOrganization
}

func (g *GetOrganizationTeamMember) GetSso() bool {
	if g == nil {
		return false
	}
	return g.Sso
}

func (g *GetOrganizationTeamMember) GetManaged() bool {
	if g == nil {
		return false
	}
	return g.Managed
}

func (g *GetOrganizationTeamMember) GetDirectoryManaged() bool {
	if g == nil {
		return false
	}
	return g.DirectoryManaged
}

func (g *GetOrganizationTeamMember) GetEmailVerified() bool {
	if g == nil {
		return false
	}
	return g.EmailVerified
}

type GetOrganizationTeamDatabase struct {
	// The ID of the database
	ID string `json:"id"`
	// The name of the database
	Name string `json:"name"`
	// The URL to the database API endpoint
	URL string `json:"url"`
	// The URL to retrieve this database's branches via the API
	BranchesURL string `json:"branches_url"`
}

func (g *GetOrganizationTeamDatabase) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetOrganizationTeamDatabase) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetOrganizationTeamDatabase) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

func (g *GetOrganizationTeamDatabase) GetBranchesURL() string {
	if g == nil {
		return ""
	}
	return g.BranchesURL
}

// GetOrganizationTeamResponseBody - Returns the team details including members and databases
type GetOrganizationTeamResponseBody struct {
	// The ID of the team
	ID string `json:"id"`
	// The display name of the team
	DisplayName string                        `json:"display_name"`
	Creator     GetOrganizationTeamCreator    `json:"creator"`
	Members     []GetOrganizationTeamMember   `json:"members"`
	Databases   []GetOrganizationTeamDatabase `json:"databases"`
	// The name of the team
	Name string `json:"name"`
	// The slug of the team
	Slug string `json:"slug"`
	// When the team was created
	CreatedAt string `json:"created_at"`
	// When the team was last updated
	UpdatedAt string `json:"updated_at"`
	// The description of the team
	Description string `json:"description"`
	// Whether the team is managed through SSO/directory services
	Managed bool `json:"managed"`
}

func (g *GetOrganizationTeamResponseBody) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetOrganizationTeamResponseBody) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetOrganizationTeamResponseBody) GetCreator() GetOrganizationTeamCreator {
	if g == nil {
		return GetOrganizationTeamCreator{}
	}
	return g.Creator
}

func (g *GetOrganizationTeamResponseBody) GetMembers() []GetOrganizationTeamMember {
	if g == nil {
		return []GetOrganizationTeamMember{}
	}
	return g.Members
}

func (g *GetOrganizationTeamResponseBody) GetDatabases() []GetOrganizationTeamDatabase {
	if g == nil {
		return []GetOrganizationTeamDatabase{}
	}
	return g.Databases
}

func (g *GetOrganizationTeamResponseBody) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetOrganizationTeamResponseBody) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

func (g *GetOrganizationTeamResponseBody) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetOrganizationTeamResponseBody) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetOrganizationTeamResponseBody) GetDescription() string {
	if g == nil {
		return ""
	}
	return g.Description
}

func (g *GetOrganizationTeamResponseBody) GetManaged() bool {
	if g == nil {
		return false
	}
	return g.Managed
}

type GetOrganizationTeamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the team details including members and databases
	Object *GetOrganizationTeamResponseBody
}

func (g GetOrganizationTeamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOrganizationTeamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (g *GetOrganizationTeamResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetOrganizationTeamResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetOrganizationTeamResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetOrganizationTeamResponse) GetObject() *GetOrganizationTeamResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
