// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type GetRoleRequest struct {
	// The name of the organization that owns this resource
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database that owns this resource
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch that owns this resource
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The ID of the role
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetRoleRequest) GetOrganization() string {
	if g == nil {
		return ""
	}
	return g.Organization
}

func (g *GetRoleRequest) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

func (g *GetRoleRequest) GetBranch() string {
	if g == nil {
		return ""
	}
	return g.Branch
}

func (g *GetRoleRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetRoleInheritedRole string

const (
	GetRoleInheritedRolePscaleManaged            GetRoleInheritedRole = "pscale_managed"
	GetRoleInheritedRolePgCheckpoint             GetRoleInheritedRole = "pg_checkpoint"
	GetRoleInheritedRolePgCreateSubscription     GetRoleInheritedRole = "pg_create_subscription"
	GetRoleInheritedRolePgMaintain               GetRoleInheritedRole = "pg_maintain"
	GetRoleInheritedRolePgMonitor                GetRoleInheritedRole = "pg_monitor"
	GetRoleInheritedRolePgReadAllData            GetRoleInheritedRole = "pg_read_all_data"
	GetRoleInheritedRolePgReadAllSettings        GetRoleInheritedRole = "pg_read_all_settings"
	GetRoleInheritedRolePgReadAllStats           GetRoleInheritedRole = "pg_read_all_stats"
	GetRoleInheritedRolePgSignalBackend          GetRoleInheritedRole = "pg_signal_backend"
	GetRoleInheritedRolePgStatScanTables         GetRoleInheritedRole = "pg_stat_scan_tables"
	GetRoleInheritedRolePgUseReservedConnections GetRoleInheritedRole = "pg_use_reserved_connections"
	GetRoleInheritedRolePgWriteAllData           GetRoleInheritedRole = "pg_write_all_data"
	GetRoleInheritedRolePostgres                 GetRoleInheritedRole = "postgres"
)

func (e GetRoleInheritedRole) ToPointer() *GetRoleInheritedRole {
	return &e
}
func (e *GetRoleInheritedRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pscale_managed":
		fallthrough
	case "pg_checkpoint":
		fallthrough
	case "pg_create_subscription":
		fallthrough
	case "pg_maintain":
		fallthrough
	case "pg_monitor":
		fallthrough
	case "pg_read_all_data":
		fallthrough
	case "pg_read_all_settings":
		fallthrough
	case "pg_read_all_stats":
		fallthrough
	case "pg_signal_backend":
		fallthrough
	case "pg_stat_scan_tables":
		fallthrough
	case "pg_use_reserved_connections":
		fallthrough
	case "pg_write_all_data":
		fallthrough
	case "postgres":
		*e = GetRoleInheritedRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetRoleInheritedRole: %v", v)
	}
}

type GetRoleBranchData struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (g *GetRoleBranchData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRoleBranchData) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetRoleBranchData) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetRoleBranchData) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetRoleBranchData) GetDeletedAt() string {
	if g == nil {
		return ""
	}
	return g.DeletedAt
}

type GetRoleActorData struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (g *GetRoleActorData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRoleActorData) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetRoleActorData) GetAvatarURL() string {
	if g == nil {
		return ""
	}
	return g.AvatarURL
}

// GetRoleResponseBody - Returns a role
type GetRoleResponseBody struct {
	// The ID of the role
	ID string `json:"id"`
	// The name of the role
	Name string `json:"name"`
	// The database connection string
	AccessHostURL string `json:"access_host_url"`
	// The database connection string for private connections
	PrivateAccessHostURL string `json:"private_access_host_url"`
	// The service name to set up private connectivity
	PrivateConnectionServiceName string `json:"private_connection_service_name"`
	// The database user name
	Username string `json:"username"`
	// The database name
	DatabaseName string `json:"database_name"`
	// When the role was created
	CreatedAt string `json:"created_at"`
	// When the role was updated
	UpdatedAt string `json:"updated_at"`
	// When the role was deleted
	DeletedAt string `json:"deleted_at"`
	// When the role expires
	ExpiresAt string `json:"expires_at"`
	// When the role was dropped
	DroppedAt string `json:"dropped_at"`
	// When the role was disabled
	DisabledAt string `json:"disabled_at"`
	// Error message available when dropping the role fails
	DropFailed string `json:"drop_failed"`
	// True if the credentials are expired
	Expired bool `json:"expired"`
	// Whether the role is the default postgres user
	Default bool `json:"default"`
	// Number of seconds before the credentials expire
	TTL int64 `json:"ttl"`
	// Database roles these credentials inherit
	InheritedRoles []GetRoleInheritedRole `json:"inherited_roles"`
	BranchData     GetRoleBranchData      `json:"branch"`
	ActorData      GetRoleActorData       `json:"actor"`
}

func (g *GetRoleResponseBody) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRoleResponseBody) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetRoleResponseBody) GetAccessHostURL() string {
	if g == nil {
		return ""
	}
	return g.AccessHostURL
}

func (g *GetRoleResponseBody) GetPrivateAccessHostURL() string {
	if g == nil {
		return ""
	}
	return g.PrivateAccessHostURL
}

func (g *GetRoleResponseBody) GetPrivateConnectionServiceName() string {
	if g == nil {
		return ""
	}
	return g.PrivateConnectionServiceName
}

func (g *GetRoleResponseBody) GetUsername() string {
	if g == nil {
		return ""
	}
	return g.Username
}

func (g *GetRoleResponseBody) GetDatabaseName() string {
	if g == nil {
		return ""
	}
	return g.DatabaseName
}

func (g *GetRoleResponseBody) GetCreatedAt() string {
	if g == nil {
		return ""
	}
	return g.CreatedAt
}

func (g *GetRoleResponseBody) GetUpdatedAt() string {
	if g == nil {
		return ""
	}
	return g.UpdatedAt
}

func (g *GetRoleResponseBody) GetDeletedAt() string {
	if g == nil {
		return ""
	}
	return g.DeletedAt
}

func (g *GetRoleResponseBody) GetExpiresAt() string {
	if g == nil {
		return ""
	}
	return g.ExpiresAt
}

func (g *GetRoleResponseBody) GetDroppedAt() string {
	if g == nil {
		return ""
	}
	return g.DroppedAt
}

func (g *GetRoleResponseBody) GetDisabledAt() string {
	if g == nil {
		return ""
	}
	return g.DisabledAt
}

func (g *GetRoleResponseBody) GetDropFailed() string {
	if g == nil {
		return ""
	}
	return g.DropFailed
}

func (g *GetRoleResponseBody) GetExpired() bool {
	if g == nil {
		return false
	}
	return g.Expired
}

func (g *GetRoleResponseBody) GetDefault() bool {
	if g == nil {
		return false
	}
	return g.Default
}

func (g *GetRoleResponseBody) GetTTL() int64 {
	if g == nil {
		return 0
	}
	return g.TTL
}

func (g *GetRoleResponseBody) GetInheritedRoles() []GetRoleInheritedRole {
	if g == nil {
		return []GetRoleInheritedRole{}
	}
	return g.InheritedRoles
}

func (g *GetRoleResponseBody) GetBranchData() GetRoleBranchData {
	if g == nil {
		return GetRoleBranchData{}
	}
	return g.BranchData
}

func (g *GetRoleResponseBody) GetActorData() GetRoleActorData {
	if g == nil {
		return GetRoleActorData{}
	}
	return g.ActorData
}

type GetRoleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a role
	Object *GetRoleResponseBody
}

func (g GetRoleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRoleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRoleResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRoleResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRoleResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRoleResponse) GetObject() *GetRoleResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
