// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type GetVitessBackupPolicyRequest struct {
	// The ID of the backup policy
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization name slug from `list_organizations`. Example: `acme`.
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Database name slug from `list_databases`. Example: `app-db`.
	Database string `pathParam:"style=simple,explode=false,name=database"`
}

func (g *GetVitessBackupPolicyRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetVitessBackupPolicyRequest) GetOrganization() string {
	if g == nil {
		return ""
	}
	return g.Organization
}

func (g *GetVitessBackupPolicyRequest) GetDatabase() string {
	if g == nil {
		return ""
	}
	return g.Database
}

// GetVitessBackupPolicyTarget - Whether the policy is for production or development branches
type GetVitessBackupPolicyTarget string

const (
	GetVitessBackupPolicyTargetProduction  GetVitessBackupPolicyTarget = "production"
	GetVitessBackupPolicyTargetDevelopment GetVitessBackupPolicyTarget = "development"
)

func (e GetVitessBackupPolicyTarget) ToPointer() *GetVitessBackupPolicyTarget {
	return &e
}
func (e *GetVitessBackupPolicyTarget) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "production":
		fallthrough
	case "development":
		*e = GetVitessBackupPolicyTarget(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetVitessBackupPolicyTarget: %v", v)
	}
}

// GetVitessBackupPolicyResponseBody - Returns a backup policy
type GetVitessBackupPolicyResponseBody struct {
	// The ID of the backup policy
	ID string `json:"id"`
	// The display name of the backup policy
	DisplayName string `json:"display_name"`
	// The name of the backup policy
	Name string `json:"name"`
	// Whether the policy is for production or development branches
	Target GetVitessBackupPolicyTarget `json:"target"`
	// A number value for the retention period of the backup policy
	RetentionValue int64 `json:"retention_value"`
	// The unit for the retention period of the backup policy
	RetentionUnit string `json:"retention_unit"`
	// A number value for the frequency of the backup policy
	FrequencyValue int64 `json:"frequency_value"`
	// The unit for the frequency of the backup policy
	FrequencyUnit string `json:"frequency_unit"`
	// The time of day that the backup is scheduled, in HH:MM format
	ScheduleTime string `json:"schedule_time"`
	// Day of the week that the backup is scheduled. 0 is Sunday, 6 is Saturday
	ScheduleDay *int64 `json:"schedule_day"`
	// Week of the month that the backup is scheduled. 0 is the first week, 3 is the fourth week
	ScheduleWeek *int64 `json:"schedule_week"`
	// When the backup was last run
	LastRanAt *string `json:"last_ran_at"`
	// When the backup will next run
	NextRunAt *string `json:"next_run_at"`
	// Whether the policy is a required system backup
	Required bool `json:"required"`
}

func (g *GetVitessBackupPolicyResponseBody) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetVitessBackupPolicyResponseBody) GetDisplayName() string {
	if g == nil {
		return ""
	}
	return g.DisplayName
}

func (g *GetVitessBackupPolicyResponseBody) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetVitessBackupPolicyResponseBody) GetTarget() GetVitessBackupPolicyTarget {
	if g == nil {
		return GetVitessBackupPolicyTarget("")
	}
	return g.Target
}

func (g *GetVitessBackupPolicyResponseBody) GetRetentionValue() int64 {
	if g == nil {
		return 0
	}
	return g.RetentionValue
}

func (g *GetVitessBackupPolicyResponseBody) GetRetentionUnit() string {
	if g == nil {
		return ""
	}
	return g.RetentionUnit
}

func (g *GetVitessBackupPolicyResponseBody) GetFrequencyValue() int64 {
	if g == nil {
		return 0
	}
	return g.FrequencyValue
}

func (g *GetVitessBackupPolicyResponseBody) GetFrequencyUnit() string {
	if g == nil {
		return ""
	}
	return g.FrequencyUnit
}

func (g *GetVitessBackupPolicyResponseBody) GetScheduleTime() string {
	if g == nil {
		return ""
	}
	return g.ScheduleTime
}

func (g *GetVitessBackupPolicyResponseBody) GetScheduleDay() *int64 {
	if g == nil {
		return nil
	}
	return g.ScheduleDay
}

func (g *GetVitessBackupPolicyResponseBody) GetScheduleWeek() *int64 {
	if g == nil {
		return nil
	}
	return g.ScheduleWeek
}

func (g *GetVitessBackupPolicyResponseBody) GetLastRanAt() *string {
	if g == nil {
		return nil
	}
	return g.LastRanAt
}

func (g *GetVitessBackupPolicyResponseBody) GetNextRunAt() *string {
	if g == nil {
		return nil
	}
	return g.NextRunAt
}

func (g *GetVitessBackupPolicyResponseBody) GetRequired() bool {
	if g == nil {
		return false
	}
	return g.Required
}

type GetVitessBackupPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a backup policy
	Object *GetVitessBackupPolicyResponseBody
}

func (g GetVitessBackupPolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetVitessBackupPolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetVitessBackupPolicyResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetVitessBackupPolicyResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetVitessBackupPolicyResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetVitessBackupPolicyResponse) GetObject() *GetVitessBackupPolicyResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
