// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListDeployOperationsRequest struct {
	// The number of the deploy request
	Number int64 `pathParam:"style=simple,explode=false,name=number"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// If provided, specifies the page offset of returned results
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *int64 `default:"25" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListDeployOperationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDeployOperationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"number", "organization", "database"}); err != nil {
		return err
	}
	return nil
}

func (l *ListDeployOperationsRequest) GetNumber() int64 {
	if l == nil {
		return 0
	}
	return l.Number
}

func (l *ListDeployOperationsRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListDeployOperationsRequest) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

func (l *ListDeployOperationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListDeployOperationsRequest) GetPerPage() *int64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

// ListDeployOperationsState - The state of the deploy operation
type ListDeployOperationsState string

const (
	ListDeployOperationsStatePending    ListDeployOperationsState = "pending"
	ListDeployOperationsStateQueued     ListDeployOperationsState = "queued"
	ListDeployOperationsStateInProgress ListDeployOperationsState = "in_progress"
	ListDeployOperationsStateComplete   ListDeployOperationsState = "complete"
	ListDeployOperationsStateCancelled  ListDeployOperationsState = "cancelled"
	ListDeployOperationsStateError      ListDeployOperationsState = "error"
)

func (e ListDeployOperationsState) ToPointer() *ListDeployOperationsState {
	return &e
}
func (e *ListDeployOperationsState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "queued":
		fallthrough
	case "in_progress":
		fallthrough
	case "complete":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = ListDeployOperationsState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListDeployOperationsState: %v", v)
	}
}

type ListDeployOperationsData struct {
	// The ID for the deploy operation
	ID string `json:"id"`
	// The state of the deploy operation
	State ListDeployOperationsState `json:"state"`
	// The keyspace modified by the deploy operation
	KeyspaceName string `json:"keyspace_name"`
	// The name of the table modifed by the deploy operation
	TableName string `json:"table_name"`
	// The operation name of the deploy operation
	OperationName string `json:"operation_name"`
	// The estimated seconds until completion for the deploy operation
	EtaSeconds float64 `json:"eta_seconds"`
	// The percent completion for the deploy operation
	ProgressPercentage float64 `json:"progress_percentage"`
	// A link to documentation explaining the deploy error, if present
	DeployErrorDocsURL string `json:"deploy_error_docs_url"`
	// The DDL statement for the deploy operation
	DdlStatement string `json:"ddl_statement"`
	// A syntax-highlighted DDL statement for the deploy operation
	SyntaxHighlightedDdl string `json:"syntax_highlighted_ddl"`
	// When the deploy operation was created
	CreatedAt string `json:"created_at"`
	// When the deploy operation was last updated
	UpdatedAt string `json:"updated_at"`
	// When the deploy operation was last throttled
	ThrottledAt string `json:"throttled_at"`
	// Whether or not the deploy operation is capable of dropping data
	CanDropData bool `json:"can_drop_data"`
	// Whether or not the table modified by the deploy operation is currently locked
	TableLocked bool `json:"table_locked"`
	// Whether or not the table modified by the deploy operation was recently used
	TableRecentlyUsed bool `json:"table_recently_used"`
	// When the table modified by the deploy operation was last used
	TableRecentlyUsedAt string `json:"table_recently_used_at"`
	// Names of foreign keys removed by this operation
	RemovedForeignKeyNames []string `json:"removed_foreign_key_names"`
	// Deploy errors for the deploy operation
	DeployErrors string `json:"deploy_errors"`
}

func (l *ListDeployOperationsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListDeployOperationsData) GetState() ListDeployOperationsState {
	if l == nil {
		return ListDeployOperationsState("")
	}
	return l.State
}

func (l *ListDeployOperationsData) GetKeyspaceName() string {
	if l == nil {
		return ""
	}
	return l.KeyspaceName
}

func (l *ListDeployOperationsData) GetTableName() string {
	if l == nil {
		return ""
	}
	return l.TableName
}

func (l *ListDeployOperationsData) GetOperationName() string {
	if l == nil {
		return ""
	}
	return l.OperationName
}

func (l *ListDeployOperationsData) GetEtaSeconds() float64 {
	if l == nil {
		return 0.0
	}
	return l.EtaSeconds
}

func (l *ListDeployOperationsData) GetProgressPercentage() float64 {
	if l == nil {
		return 0.0
	}
	return l.ProgressPercentage
}

func (l *ListDeployOperationsData) GetDeployErrorDocsURL() string {
	if l == nil {
		return ""
	}
	return l.DeployErrorDocsURL
}

func (l *ListDeployOperationsData) GetDdlStatement() string {
	if l == nil {
		return ""
	}
	return l.DdlStatement
}

func (l *ListDeployOperationsData) GetSyntaxHighlightedDdl() string {
	if l == nil {
		return ""
	}
	return l.SyntaxHighlightedDdl
}

func (l *ListDeployOperationsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListDeployOperationsData) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListDeployOperationsData) GetThrottledAt() string {
	if l == nil {
		return ""
	}
	return l.ThrottledAt
}

func (l *ListDeployOperationsData) GetCanDropData() bool {
	if l == nil {
		return false
	}
	return l.CanDropData
}

func (l *ListDeployOperationsData) GetTableLocked() bool {
	if l == nil {
		return false
	}
	return l.TableLocked
}

func (l *ListDeployOperationsData) GetTableRecentlyUsed() bool {
	if l == nil {
		return false
	}
	return l.TableRecentlyUsed
}

func (l *ListDeployOperationsData) GetTableRecentlyUsedAt() string {
	if l == nil {
		return ""
	}
	return l.TableRecentlyUsedAt
}

func (l *ListDeployOperationsData) GetRemovedForeignKeyNames() []string {
	if l == nil {
		return []string{}
	}
	return l.RemovedForeignKeyNames
}

func (l *ListDeployOperationsData) GetDeployErrors() string {
	if l == nil {
		return ""
	}
	return l.DeployErrors
}

// ListDeployOperationsResponseBody - Returns deploy operations for the deploy request
type ListDeployOperationsResponseBody struct {
	// The current page number
	CurrentPage int64 `json:"current_page"`
	// The next page number
	NextPage int64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage int64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string                     `json:"prev_page_url"`
	Data        []ListDeployOperationsData `json:"data"`
}

func (l *ListDeployOperationsResponseBody) GetCurrentPage() int64 {
	if l == nil {
		return 0
	}
	return l.CurrentPage
}

func (l *ListDeployOperationsResponseBody) GetNextPage() int64 {
	if l == nil {
		return 0
	}
	return l.NextPage
}

func (l *ListDeployOperationsResponseBody) GetNextPageURL() string {
	if l == nil {
		return ""
	}
	return l.NextPageURL
}

func (l *ListDeployOperationsResponseBody) GetPrevPage() int64 {
	if l == nil {
		return 0
	}
	return l.PrevPage
}

func (l *ListDeployOperationsResponseBody) GetPrevPageURL() string {
	if l == nil {
		return ""
	}
	return l.PrevPageURL
}

func (l *ListDeployOperationsResponseBody) GetData() []ListDeployOperationsData {
	if l == nil {
		return []ListDeployOperationsData{}
	}
	return l.Data
}

type ListDeployOperationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns deploy operations for the deploy request
	Object *ListDeployOperationsResponseBody
}

func (l ListDeployOperationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDeployOperationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (l *ListDeployOperationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListDeployOperationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListDeployOperationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListDeployOperationsResponse) GetObject() *ListDeployOperationsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
