// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListDatabasesRequest struct {
	// Organization name slug from `list_organizations`. Example: `acme`.
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Search term to filter databases by name
	Q *string `queryParam:"style=form,explode=true,name=q"`
	// If provided, specifies the page offset of returned results
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *int64 `default:"25" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListDatabasesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDatabasesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDatabasesRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListDatabasesRequest) GetQ() *string {
	if l == nil {
		return nil
	}
	return l.Q
}

func (l *ListDatabasesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListDatabasesRequest) GetPerPage() *int64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

type ListDatabasesDataSource struct {
	// Hostname of the data source
	Hostname string `json:"hostname"`
	// Port of the data source
	Port int64 `json:"port"`
	// Database name of the data source
	Database string `json:"database"`
}

func (l *ListDatabasesDataSource) GetHostname() string {
	if l == nil {
		return ""
	}
	return l.Hostname
}

func (l *ListDatabasesDataSource) GetPort() int64 {
	if l == nil {
		return 0
	}
	return l.Port
}

func (l *ListDatabasesDataSource) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

type ListDatabasesDataImport struct {
	// State of the data import
	State string `json:"state"`
	// Errors encountered during the import check
	ImportCheckErrors string `json:"import_check_errors"`
	// When the import started
	StartedAt string `json:"started_at"`
	// When the import finished
	FinishedAt string                  `json:"finished_at"`
	DataSource ListDatabasesDataSource `json:"data_source"`
}

func (l *ListDatabasesDataImport) GetState() string {
	if l == nil {
		return ""
	}
	return l.State
}

func (l *ListDatabasesDataImport) GetImportCheckErrors() string {
	if l == nil {
		return ""
	}
	return l.ImportCheckErrors
}

func (l *ListDatabasesDataImport) GetStartedAt() string {
	if l == nil {
		return ""
	}
	return l.StartedAt
}

func (l *ListDatabasesDataImport) GetFinishedAt() string {
	if l == nil {
		return ""
	}
	return l.FinishedAt
}

func (l *ListDatabasesDataImport) GetDataSource() ListDatabasesDataSource {
	if l == nil {
		return ListDatabasesDataSource{}
	}
	return l.DataSource
}

type ListDatabasesRegion struct {
	// The ID of the region
	ID string `json:"id"`
	// Provider for the region (ex. AWS)
	Provider string `json:"provider"`
	// Whether or not the region is currently active
	Enabled bool `json:"enabled"`
	// Public IP addresses for the region
	PublicIPAddresses []string `json:"public_ip_addresses"`
	// Name of the region
	DisplayName string `json:"display_name"`
	// Location of the region
	Location string `json:"location"`
	// The slug of the region
	Slug string `json:"slug"`
	// True if the region is the default for new branch creation
	CurrentDefault bool `json:"current_default"`
}

func (l *ListDatabasesRegion) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListDatabasesRegion) GetProvider() string {
	if l == nil {
		return ""
	}
	return l.Provider
}

func (l *ListDatabasesRegion) GetEnabled() bool {
	if l == nil {
		return false
	}
	return l.Enabled
}

func (l *ListDatabasesRegion) GetPublicIPAddresses() []string {
	if l == nil {
		return []string{}
	}
	return l.PublicIPAddresses
}

func (l *ListDatabasesRegion) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListDatabasesRegion) GetLocation() string {
	if l == nil {
		return ""
	}
	return l.Location
}

func (l *ListDatabasesRegion) GetSlug() string {
	if l == nil {
		return ""
	}
	return l.Slug
}

func (l *ListDatabasesRegion) GetCurrentDefault() bool {
	if l == nil {
		return false
	}
	return l.CurrentDefault
}

// ListDatabasesState - State of the database
type ListDatabasesState string

const (
	ListDatabasesStatePending         ListDatabasesState = "pending"
	ListDatabasesStateImporting       ListDatabasesState = "importing"
	ListDatabasesStateSleepInProgress ListDatabasesState = "sleep_in_progress"
	ListDatabasesStateSleeping        ListDatabasesState = "sleeping"
	ListDatabasesStateAwakening       ListDatabasesState = "awakening"
	ListDatabasesStateImportReady     ListDatabasesState = "import_ready"
	ListDatabasesStateReady           ListDatabasesState = "ready"
)

func (e ListDatabasesState) ToPointer() *ListDatabasesState {
	return &e
}
func (e *ListDatabasesState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "importing":
		fallthrough
	case "sleep_in_progress":
		fallthrough
	case "sleeping":
		fallthrough
	case "awakening":
		fallthrough
	case "import_ready":
		fallthrough
	case "ready":
		*e = ListDatabasesState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListDatabasesState: %v", v)
	}
}

// Kind - The kind of database
type Kind string

const (
	KindMysql      Kind = "mysql"
	KindPostgresql Kind = "postgresql"
)

func (e Kind) ToPointer() *Kind {
	return &e
}
func (e *Kind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mysql":
		fallthrough
	case "postgresql":
		*e = Kind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Kind: %v", v)
	}
}

type ListDatabasesData struct {
	// The ID of the database
	ID string `json:"id"`
	// The URL to the database API endpoint
	URL string `json:"url"`
	// The URL to retrieve this database's branches via the API
	BranchesURL string `json:"branches_url"`
	// The total number of database branches
	BranchesCount int64 `json:"branches_count"`
	// The total number of schema recommendations
	OpenSchemaRecommendationsCount int64 `json:"open_schema_recommendations_count"`
	// The total number of database development branches
	DevelopmentBranchesCount int64 `json:"development_branches_count"`
	// The total number of database production branches
	ProductionBranchesCount int64 `json:"production_branches_count"`
	// The total number of ongoing issues within a database
	IssuesCount int64 `json:"issues_count"`
	// If the database requires multiple admins for deletion
	MultipleAdminsRequiredForDeletion bool `json:"multiple_admins_required_for_deletion"`
	// If the database is ready to be used
	Ready bool `json:"ready"`
	// If the database has reached its backup restored branch limit
	AtBackupRestoreBranchesLimit bool `json:"at_backup_restore_branches_limit"`
	// If the database has reached its development branch limit
	AtDevelopmentBranchUsageLimit bool                    `json:"at_development_branch_usage_limit"`
	DataImport                    ListDatabasesDataImport `json:"data_import"`
	Region                        ListDatabasesRegion     `json:"region"`
	// The URL to see this database's branches in the web UI
	HTMLURL string `json:"html_url"`
	// Name of the database
	Name string `json:"name"`
	// State of the database
	State ListDatabasesState `json:"state"`
	// If the database is sharded
	Sharded bool `json:"sharded"`
	// Number of shards in the default branch
	DefaultBranchShardCount int64 `json:"default_branch_shard_count"`
	// Number of read only regions in the default branch
	DefaultBranchReadOnlyRegionsCount int64 `json:"default_branch_read_only_regions_count"`
	// Number of tables in the default branch schema
	DefaultBranchTableCount int64 `json:"default_branch_table_count"`
	// The default branch for the database
	DefaultBranch string `json:"default_branch"`
	// Whether an approval is required to deploy schema changes to this database
	RequireApprovalForDeploy bool `json:"require_approval_for_deploy"`
	// True if a branch is currently resizing
	Resizing bool `json:"resizing"`
	// True if a branch has a queued resize request
	ResizeQueued bool `json:"resize_queued"`
	// Whether seeding branches with data is enabled for all branches
	AllowDataBranching bool `json:"allow_data_branching"`
	// Whether foreign key constraints are enabled
	ForeignKeysEnabled bool `json:"foreign_keys_enabled"`
	// Whether to automatically manage Rails migrations during deploy requests
	AutomaticMigrations bool `json:"automatic_migrations"`
	// Whether to restrict branch creation to one region
	RestrictBranchRegion bool `json:"restrict_branch_region"`
	// Whether raw SQL queries are collected
	InsightsRawQueries bool `json:"insights_raw_queries"`
	// The database plan
	Plan string `json:"plan"`
	// True if query insights is enabled for the database
	InsightsEnabled bool `json:"insights_enabled"`
	// Whether web console is enabled for production branches
	ProductionBranchWebConsole bool `json:"production_branch_web_console"`
	// Table name to use for copying schema migration data
	MigrationTableName string `json:"migration_table_name"`
	// Framework used for applying migrations
	MigrationFramework string `json:"migration_framework"`
	// When the database was created
	CreatedAt string `json:"created_at"`
	// When the database was last updated
	UpdatedAt string `json:"updated_at"`
	// When the default branch schema was last changed.
	SchemaLastUpdatedAt string `json:"schema_last_updated_at"`
	// The kind of database
	Kind Kind `json:"kind"`
}

func (l *ListDatabasesData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListDatabasesData) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *ListDatabasesData) GetBranchesURL() string {
	if l == nil {
		return ""
	}
	return l.BranchesURL
}

func (l *ListDatabasesData) GetBranchesCount() int64 {
	if l == nil {
		return 0
	}
	return l.BranchesCount
}

func (l *ListDatabasesData) GetOpenSchemaRecommendationsCount() int64 {
	if l == nil {
		return 0
	}
	return l.OpenSchemaRecommendationsCount
}

func (l *ListDatabasesData) GetDevelopmentBranchesCount() int64 {
	if l == nil {
		return 0
	}
	return l.DevelopmentBranchesCount
}

func (l *ListDatabasesData) GetProductionBranchesCount() int64 {
	if l == nil {
		return 0
	}
	return l.ProductionBranchesCount
}

func (l *ListDatabasesData) GetIssuesCount() int64 {
	if l == nil {
		return 0
	}
	return l.IssuesCount
}

func (l *ListDatabasesData) GetMultipleAdminsRequiredForDeletion() bool {
	if l == nil {
		return false
	}
	return l.MultipleAdminsRequiredForDeletion
}

func (l *ListDatabasesData) GetReady() bool {
	if l == nil {
		return false
	}
	return l.Ready
}

func (l *ListDatabasesData) GetAtBackupRestoreBranchesLimit() bool {
	if l == nil {
		return false
	}
	return l.AtBackupRestoreBranchesLimit
}

func (l *ListDatabasesData) GetAtDevelopmentBranchUsageLimit() bool {
	if l == nil {
		return false
	}
	return l.AtDevelopmentBranchUsageLimit
}

func (l *ListDatabasesData) GetDataImport() ListDatabasesDataImport {
	if l == nil {
		return ListDatabasesDataImport{}
	}
	return l.DataImport
}

func (l *ListDatabasesData) GetRegion() ListDatabasesRegion {
	if l == nil {
		return ListDatabasesRegion{}
	}
	return l.Region
}

func (l *ListDatabasesData) GetHTMLURL() string {
	if l == nil {
		return ""
	}
	return l.HTMLURL
}

func (l *ListDatabasesData) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListDatabasesData) GetState() ListDatabasesState {
	if l == nil {
		return ListDatabasesState("")
	}
	return l.State
}

func (l *ListDatabasesData) GetSharded() bool {
	if l == nil {
		return false
	}
	return l.Sharded
}

func (l *ListDatabasesData) GetDefaultBranchShardCount() int64 {
	if l == nil {
		return 0
	}
	return l.DefaultBranchShardCount
}

func (l *ListDatabasesData) GetDefaultBranchReadOnlyRegionsCount() int64 {
	if l == nil {
		return 0
	}
	return l.DefaultBranchReadOnlyRegionsCount
}

func (l *ListDatabasesData) GetDefaultBranchTableCount() int64 {
	if l == nil {
		return 0
	}
	return l.DefaultBranchTableCount
}

func (l *ListDatabasesData) GetDefaultBranch() string {
	if l == nil {
		return ""
	}
	return l.DefaultBranch
}

func (l *ListDatabasesData) GetRequireApprovalForDeploy() bool {
	if l == nil {
		return false
	}
	return l.RequireApprovalForDeploy
}

func (l *ListDatabasesData) GetResizing() bool {
	if l == nil {
		return false
	}
	return l.Resizing
}

func (l *ListDatabasesData) GetResizeQueued() bool {
	if l == nil {
		return false
	}
	return l.ResizeQueued
}

func (l *ListDatabasesData) GetAllowDataBranching() bool {
	if l == nil {
		return false
	}
	return l.AllowDataBranching
}

func (l *ListDatabasesData) GetForeignKeysEnabled() bool {
	if l == nil {
		return false
	}
	return l.ForeignKeysEnabled
}

func (l *ListDatabasesData) GetAutomaticMigrations() bool {
	if l == nil {
		return false
	}
	return l.AutomaticMigrations
}

func (l *ListDatabasesData) GetRestrictBranchRegion() bool {
	if l == nil {
		return false
	}
	return l.RestrictBranchRegion
}

func (l *ListDatabasesData) GetInsightsRawQueries() bool {
	if l == nil {
		return false
	}
	return l.InsightsRawQueries
}

func (l *ListDatabasesData) GetPlan() string {
	if l == nil {
		return ""
	}
	return l.Plan
}

func (l *ListDatabasesData) GetInsightsEnabled() bool {
	if l == nil {
		return false
	}
	return l.InsightsEnabled
}

func (l *ListDatabasesData) GetProductionBranchWebConsole() bool {
	if l == nil {
		return false
	}
	return l.ProductionBranchWebConsole
}

func (l *ListDatabasesData) GetMigrationTableName() string {
	if l == nil {
		return ""
	}
	return l.MigrationTableName
}

func (l *ListDatabasesData) GetMigrationFramework() string {
	if l == nil {
		return ""
	}
	return l.MigrationFramework
}

func (l *ListDatabasesData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListDatabasesData) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListDatabasesData) GetSchemaLastUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.SchemaLastUpdatedAt
}

func (l *ListDatabasesData) GetKind() Kind {
	if l == nil {
		return Kind("")
	}
	return l.Kind
}

// ListDatabasesResponseBody - Retrieves the databases for an organization
type ListDatabasesResponseBody struct {
	// The current page number
	CurrentPage int64 `json:"current_page"`
	// The next page number
	NextPage int64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage int64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string              `json:"prev_page_url"`
	Data        []ListDatabasesData `json:"data"`
}

func (l *ListDatabasesResponseBody) GetCurrentPage() int64 {
	if l == nil {
		return 0
	}
	return l.CurrentPage
}

func (l *ListDatabasesResponseBody) GetNextPage() int64 {
	if l == nil {
		return 0
	}
	return l.NextPage
}

func (l *ListDatabasesResponseBody) GetNextPageURL() string {
	if l == nil {
		return ""
	}
	return l.NextPageURL
}

func (l *ListDatabasesResponseBody) GetPrevPage() int64 {
	if l == nil {
		return 0
	}
	return l.PrevPage
}

func (l *ListDatabasesResponseBody) GetPrevPageURL() string {
	if l == nil {
		return ""
	}
	return l.PrevPageURL
}

func (l *ListDatabasesResponseBody) GetData() []ListDatabasesData {
	if l == nil {
		return []ListDatabasesData{}
	}
	return l.Data
}

type ListDatabasesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Retrieves the databases for an organization
	Object *ListDatabasesResponseBody

	Next func() (*ListDatabasesResponse, error)
}

func (l ListDatabasesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDatabasesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDatabasesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListDatabasesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListDatabasesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListDatabasesResponse) GetObject() *ListDatabasesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
