// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListReadOnlyRegionsRequest struct {
	// The name of the organization the database belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// If provided, specifies the page offset of returned results
	Page *float64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `default:"25" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListReadOnlyRegionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListReadOnlyRegionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"organization", "database"}); err != nil {
		return err
	}
	return nil
}

func (l *ListReadOnlyRegionsRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListReadOnlyRegionsRequest) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

func (l *ListReadOnlyRegionsRequest) GetPage() *float64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListReadOnlyRegionsRequest) GetPerPage() *float64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

type ListReadOnlyRegionsActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (l *ListReadOnlyRegionsActor) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListReadOnlyRegionsActor) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListReadOnlyRegionsActor) GetAvatarURL() string {
	if l == nil {
		return ""
	}
	return l.AvatarURL
}

type ListReadOnlyRegionsRegion struct {
	// The ID of the region
	ID string `json:"id"`
	// Provider for the region (ex. AWS)
	Provider string `json:"provider"`
	// Whether or not the region is currently active
	Enabled bool `json:"enabled"`
	// Public IP addresses for the region
	PublicIPAddresses []string `json:"public_ip_addresses"`
	// Name of the region
	DisplayName string `json:"display_name"`
	// Location of the region
	Location string `json:"location"`
	// The slug of the region
	Slug string `json:"slug"`
	// True if the region is the default for new branch creation
	CurrentDefault bool `json:"current_default"`
}

func (l *ListReadOnlyRegionsRegion) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListReadOnlyRegionsRegion) GetProvider() string {
	if l == nil {
		return ""
	}
	return l.Provider
}

func (l *ListReadOnlyRegionsRegion) GetEnabled() bool {
	if l == nil {
		return false
	}
	return l.Enabled
}

func (l *ListReadOnlyRegionsRegion) GetPublicIPAddresses() []string {
	if l == nil {
		return []string{}
	}
	return l.PublicIPAddresses
}

func (l *ListReadOnlyRegionsRegion) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListReadOnlyRegionsRegion) GetLocation() string {
	if l == nil {
		return ""
	}
	return l.Location
}

func (l *ListReadOnlyRegionsRegion) GetSlug() string {
	if l == nil {
		return ""
	}
	return l.Slug
}

func (l *ListReadOnlyRegionsRegion) GetCurrentDefault() bool {
	if l == nil {
		return false
	}
	return l.CurrentDefault
}

type ListReadOnlyRegionsData struct {
	// The ID of the read-only region
	ID string `json:"id"`
	// The name of the read-only region
	DisplayName string `json:"display_name"`
	// When the read-only region was created
	CreatedAt string `json:"created_at"`
	// When the read-only region was last updated
	UpdatedAt string `json:"updated_at"`
	// When the read-only region was ready to serve queries
	ReadyAt string `json:"ready_at"`
	// Whether or not the read-only region is ready to serve queries
	Ready  bool                      `json:"ready"`
	Actor  ListReadOnlyRegionsActor  `json:"actor"`
	Region ListReadOnlyRegionsRegion `json:"region"`
}

func (l *ListReadOnlyRegionsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListReadOnlyRegionsData) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListReadOnlyRegionsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListReadOnlyRegionsData) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListReadOnlyRegionsData) GetReadyAt() string {
	if l == nil {
		return ""
	}
	return l.ReadyAt
}

func (l *ListReadOnlyRegionsData) GetReady() bool {
	if l == nil {
		return false
	}
	return l.Ready
}

func (l *ListReadOnlyRegionsData) GetActor() ListReadOnlyRegionsActor {
	if l == nil {
		return ListReadOnlyRegionsActor{}
	}
	return l.Actor
}

func (l *ListReadOnlyRegionsData) GetRegion() ListReadOnlyRegionsRegion {
	if l == nil {
		return ListReadOnlyRegionsRegion{}
	}
	return l.Region
}

// ListReadOnlyRegionsResponseBody - List of the database's read-only regions
type ListReadOnlyRegionsResponseBody struct {
	// The current page number
	CurrentPage int64 `json:"current_page"`
	// The next page number
	NextPage int64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage int64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string                    `json:"prev_page_url"`
	Data        []ListReadOnlyRegionsData `json:"data"`
}

func (l *ListReadOnlyRegionsResponseBody) GetCurrentPage() int64 {
	if l == nil {
		return 0
	}
	return l.CurrentPage
}

func (l *ListReadOnlyRegionsResponseBody) GetNextPage() int64 {
	if l == nil {
		return 0
	}
	return l.NextPage
}

func (l *ListReadOnlyRegionsResponseBody) GetNextPageURL() string {
	if l == nil {
		return ""
	}
	return l.NextPageURL
}

func (l *ListReadOnlyRegionsResponseBody) GetPrevPage() int64 {
	if l == nil {
		return 0
	}
	return l.PrevPage
}

func (l *ListReadOnlyRegionsResponseBody) GetPrevPageURL() string {
	if l == nil {
		return ""
	}
	return l.PrevPageURL
}

func (l *ListReadOnlyRegionsResponseBody) GetData() []ListReadOnlyRegionsData {
	if l == nil {
		return []ListReadOnlyRegionsData{}
	}
	return l.Data
}

type ListReadOnlyRegionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of the database's read-only regions
	Object *ListReadOnlyRegionsResponseBody
}

func (l ListReadOnlyRegionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListReadOnlyRegionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (l *ListReadOnlyRegionsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListReadOnlyRegionsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListReadOnlyRegionsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListReadOnlyRegionsResponse) GetObject() *ListReadOnlyRegionsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
