// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListBouncersRequest struct {
	// The name of the organization that owns this resource
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database that owns this resource
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch that owns this resource
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// If provided, specifies the page offset of returned results
	Page *float64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `default:"25" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListBouncersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBouncersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"organization", "database", "branch"}); err != nil {
		return err
	}
	return nil
}

func (l *ListBouncersRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListBouncersRequest) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

func (l *ListBouncersRequest) GetBranch() string {
	if l == nil {
		return ""
	}
	return l.Branch
}

func (l *ListBouncersRequest) GetPage() *float64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListBouncersRequest) GetPerPage() *float64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

type ListBouncersSku struct {
	// The name of the Postgres bouncer SKU
	Name string `json:"name"`
	// The display name
	DisplayName string `json:"display_name"`
	// The CPU allocation
	CPU string `json:"cpu"`
	// The amount of memory in bytes
	RAM int64 `json:"ram"`
	// The sort order of the Postgres bouncer SKU
	SortOrder int64 `json:"sort_order"`
}

func (l *ListBouncersSku) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBouncersSku) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBouncersSku) GetCPU() string {
	if l == nil {
		return ""
	}
	return l.CPU
}

func (l *ListBouncersSku) GetRAM() int64 {
	if l == nil {
		return 0
	}
	return l.RAM
}

func (l *ListBouncersSku) GetSortOrder() int64 {
	if l == nil {
		return 0
	}
	return l.SortOrder
}

// ListBouncersTarget - The instance type the bouncer targets
type ListBouncersTarget string

const (
	ListBouncersTargetPrimary           ListBouncersTarget = "primary"
	ListBouncersTargetReplica           ListBouncersTarget = "replica"
	ListBouncersTargetReplicaAzAffinity ListBouncersTarget = "replica_az_affinity"
)

func (e ListBouncersTarget) ToPointer() *ListBouncersTarget {
	return &e
}
func (e *ListBouncersTarget) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "primary":
		fallthrough
	case "replica":
		fallthrough
	case "replica_az_affinity":
		*e = ListBouncersTarget(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListBouncersTarget: %v", v)
	}
}

type ListBouncersActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (l *ListBouncersActor) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBouncersActor) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBouncersActor) GetAvatarURL() string {
	if l == nil {
		return ""
	}
	return l.AvatarURL
}

type ListBouncersBranch struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (l *ListBouncersBranch) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBouncersBranch) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBouncersBranch) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListBouncersBranch) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListBouncersBranch) GetDeletedAt() string {
	if l == nil {
		return ""
	}
	return l.DeletedAt
}

// ListBouncersNamespace - The namespace of the parameter
type ListBouncersNamespace string

const (
	ListBouncersNamespacePgbouncer ListBouncersNamespace = "pgbouncer"
)

func (e ListBouncersNamespace) ToPointer() *ListBouncersNamespace {
	return &e
}
func (e *ListBouncersNamespace) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pgbouncer":
		*e = ListBouncersNamespace(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListBouncersNamespace: %v", v)
	}
}

// ListBouncersParameterType - The type of the parameter
type ListBouncersParameterType string

const (
	ListBouncersParameterTypeArray    ListBouncersParameterType = "array"
	ListBouncersParameterTypeBoolean  ListBouncersParameterType = "boolean"
	ListBouncersParameterTypeBytes    ListBouncersParameterType = "bytes"
	ListBouncersParameterTypeFloat    ListBouncersParameterType = "float"
	ListBouncersParameterTypeInteger  ListBouncersParameterType = "integer"
	ListBouncersParameterTypeInternal ListBouncersParameterType = "internal"
	ListBouncersParameterTypeSeconds  ListBouncersParameterType = "seconds"
	ListBouncersParameterTypeSelect   ListBouncersParameterType = "select"
	ListBouncersParameterTypeString   ListBouncersParameterType = "string"
	ListBouncersParameterTypeTime     ListBouncersParameterType = "time"
)

func (e ListBouncersParameterType) ToPointer() *ListBouncersParameterType {
	return &e
}
func (e *ListBouncersParameterType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "array":
		fallthrough
	case "boolean":
		fallthrough
	case "bytes":
		fallthrough
	case "float":
		fallthrough
	case "integer":
		fallthrough
	case "internal":
		fallthrough
	case "seconds":
		fallthrough
	case "select":
		fallthrough
	case "string":
		fallthrough
	case "time":
		*e = ListBouncersParameterType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListBouncersParameterType: %v", v)
	}
}

type ListBouncersActorPgbouncer struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (l *ListBouncersActorPgbouncer) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBouncersActorPgbouncer) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBouncersActorPgbouncer) GetAvatarURL() string {
	if l == nil {
		return ""
	}
	return l.AvatarURL
}

type ListBouncersParameter struct {
	// The ID of the parameter
	ID string `json:"id"`
	// The namespace of the parameter
	Namespace ListBouncersNamespace `json:"namespace"`
	// The name of the parameter
	Name string `json:"name"`
	// The display name of the parameter
	DisplayName string `json:"display_name"`
	// The category of the parameter
	Category string `json:"category"`
	// The description of the parameter
	Description string `json:"description"`
	// The type of the parameter
	ParameterType ListBouncersParameterType `json:"parameter_type"`
	// The default value of the parameter
	DefaultValue string `json:"default_value"`
	// The configured value of the parameter
	Value string `json:"value"`
	// Whether the parameter is required
	Required bool `json:"required"`
	// When the parameter was created
	CreatedAt string `json:"created_at"`
	// When the parameter was last updated
	UpdatedAt string `json:"updated_at"`
	// True if processes require a server restart on change
	Restart bool `json:"restart"`
	// The maximum value of the parameter
	Max float64 `json:"max"`
	// The minimum value of the parameter
	Min float64 `json:"min"`
	// The step change of the parameter
	Step float64 `json:"step"`
	// The URL of the parameter
	URL string `json:"url"`
	// Valid options for the parameter value
	Options []string                   `json:"options"`
	Actor   ListBouncersActorPgbouncer `json:"actor"`
}

func (l *ListBouncersParameter) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBouncersParameter) GetNamespace() ListBouncersNamespace {
	if l == nil {
		return ListBouncersNamespace("")
	}
	return l.Namespace
}

func (l *ListBouncersParameter) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBouncersParameter) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBouncersParameter) GetCategory() string {
	if l == nil {
		return ""
	}
	return l.Category
}

func (l *ListBouncersParameter) GetDescription() string {
	if l == nil {
		return ""
	}
	return l.Description
}

func (l *ListBouncersParameter) GetParameterType() ListBouncersParameterType {
	if l == nil {
		return ListBouncersParameterType("")
	}
	return l.ParameterType
}

func (l *ListBouncersParameter) GetDefaultValue() string {
	if l == nil {
		return ""
	}
	return l.DefaultValue
}

func (l *ListBouncersParameter) GetValue() string {
	if l == nil {
		return ""
	}
	return l.Value
}

func (l *ListBouncersParameter) GetRequired() bool {
	if l == nil {
		return false
	}
	return l.Required
}

func (l *ListBouncersParameter) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListBouncersParameter) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListBouncersParameter) GetRestart() bool {
	if l == nil {
		return false
	}
	return l.Restart
}

func (l *ListBouncersParameter) GetMax() float64 {
	if l == nil {
		return 0.0
	}
	return l.Max
}

func (l *ListBouncersParameter) GetMin() float64 {
	if l == nil {
		return 0.0
	}
	return l.Min
}

func (l *ListBouncersParameter) GetStep() float64 {
	if l == nil {
		return 0.0
	}
	return l.Step
}

func (l *ListBouncersParameter) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *ListBouncersParameter) GetOptions() []string {
	if l == nil {
		return []string{}
	}
	return l.Options
}

func (l *ListBouncersParameter) GetActor() ListBouncersActorPgbouncer {
	if l == nil {
		return ListBouncersActorPgbouncer{}
	}
	return l.Actor
}

type ListBouncersData struct {
	// The ID of the bouncer
	ID string `json:"id"`
	// The name of the bouncer
	Name string          `json:"name"`
	Sku  ListBouncersSku `json:"sku"`
	// The instance type the bouncer targets
	Target ListBouncersTarget `json:"target"`
	// The count of replicas in each cell
	ReplicasPerCell int64 `json:"replicas_per_cell"`
	// When the bouncer was created
	CreatedAt string `json:"created_at"`
	// When the bouncer was updated
	UpdatedAt string `json:"updated_at"`
	// When the bouncer was deleted
	DeletedAt  string                  `json:"deleted_at"`
	Actor      ListBouncersActor       `json:"actor"`
	Branch     ListBouncersBranch      `json:"branch"`
	Parameters []ListBouncersParameter `json:"parameters"`
}

func (l *ListBouncersData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBouncersData) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBouncersData) GetSku() ListBouncersSku {
	if l == nil {
		return ListBouncersSku{}
	}
	return l.Sku
}

func (l *ListBouncersData) GetTarget() ListBouncersTarget {
	if l == nil {
		return ListBouncersTarget("")
	}
	return l.Target
}

func (l *ListBouncersData) GetReplicasPerCell() int64 {
	if l == nil {
		return 0
	}
	return l.ReplicasPerCell
}

func (l *ListBouncersData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListBouncersData) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListBouncersData) GetDeletedAt() string {
	if l == nil {
		return ""
	}
	return l.DeletedAt
}

func (l *ListBouncersData) GetActor() ListBouncersActor {
	if l == nil {
		return ListBouncersActor{}
	}
	return l.Actor
}

func (l *ListBouncersData) GetBranch() ListBouncersBranch {
	if l == nil {
		return ListBouncersBranch{}
	}
	return l.Branch
}

func (l *ListBouncersData) GetParameters() []ListBouncersParameter {
	if l == nil {
		return []ListBouncersParameter{}
	}
	return l.Parameters
}

// ListBouncersResponseBody - Returns bouncers
type ListBouncersResponseBody struct {
	// The current page number
	CurrentPage int64 `json:"current_page"`
	// The next page number
	NextPage int64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage int64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string             `json:"prev_page_url"`
	Data        []ListBouncersData `json:"data"`
}

func (l *ListBouncersResponseBody) GetCurrentPage() int64 {
	if l == nil {
		return 0
	}
	return l.CurrentPage
}

func (l *ListBouncersResponseBody) GetNextPage() int64 {
	if l == nil {
		return 0
	}
	return l.NextPage
}

func (l *ListBouncersResponseBody) GetNextPageURL() string {
	if l == nil {
		return ""
	}
	return l.NextPageURL
}

func (l *ListBouncersResponseBody) GetPrevPage() int64 {
	if l == nil {
		return 0
	}
	return l.PrevPage
}

func (l *ListBouncersResponseBody) GetPrevPageURL() string {
	if l == nil {
		return ""
	}
	return l.PrevPageURL
}

func (l *ListBouncersResponseBody) GetData() []ListBouncersData {
	if l == nil {
		return []ListBouncersData{}
	}
	return l.Data
}

type ListBouncersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns bouncers
	Object *ListBouncersResponseBody
}

func (l ListBouncersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBouncersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (l *ListBouncersResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListBouncersResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListBouncersResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListBouncersResponse) GetObject() *ListBouncersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
