// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListBranchBouncerResizeRequestsRequest struct {
	// The name of the organization that owns this resource
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database that owns this resource
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch that owns this resource
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// If provided, specifies the page offset of returned results
	Page *float64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `default:"25" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListBranchBouncerResizeRequestsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBranchBouncerResizeRequestsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"organization", "database", "branch"}); err != nil {
		return err
	}
	return nil
}

func (l *ListBranchBouncerResizeRequestsRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListBranchBouncerResizeRequestsRequest) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

func (l *ListBranchBouncerResizeRequestsRequest) GetBranch() string {
	if l == nil {
		return ""
	}
	return l.Branch
}

func (l *ListBranchBouncerResizeRequestsRequest) GetPage() *float64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListBranchBouncerResizeRequestsRequest) GetPerPage() *float64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

// ListBranchBouncerResizeRequestsState - The state of the bouncer resize
type ListBranchBouncerResizeRequestsState string

const (
	ListBranchBouncerResizeRequestsStatePending   ListBranchBouncerResizeRequestsState = "pending"
	ListBranchBouncerResizeRequestsStateResizing  ListBranchBouncerResizeRequestsState = "resizing"
	ListBranchBouncerResizeRequestsStateCanceled  ListBranchBouncerResizeRequestsState = "canceled"
	ListBranchBouncerResizeRequestsStateCompleted ListBranchBouncerResizeRequestsState = "completed"
)

func (e ListBranchBouncerResizeRequestsState) ToPointer() *ListBranchBouncerResizeRequestsState {
	return &e
}
func (e *ListBranchBouncerResizeRequestsState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "resizing":
		fallthrough
	case "canceled":
		fallthrough
	case "completed":
		*e = ListBranchBouncerResizeRequestsState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListBranchBouncerResizeRequestsState: %v", v)
	}
}

type ListBranchBouncerResizeRequestsActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (l *ListBranchBouncerResizeRequestsActor) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBranchBouncerResizeRequestsActor) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBranchBouncerResizeRequestsActor) GetAvatarURL() string {
	if l == nil {
		return ""
	}
	return l.AvatarURL
}

type ListBranchBouncerResizeRequestsBouncer struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (l *ListBranchBouncerResizeRequestsBouncer) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBranchBouncerResizeRequestsBouncer) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBranchBouncerResizeRequestsBouncer) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListBranchBouncerResizeRequestsBouncer) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListBranchBouncerResizeRequestsBouncer) GetDeletedAt() string {
	if l == nil {
		return ""
	}
	return l.DeletedAt
}

type ListBranchBouncerResizeRequestsSku struct {
	// The name of the Postgres bouncer SKU
	Name string `json:"name"`
	// The display name
	DisplayName string `json:"display_name"`
	// The CPU allocation
	CPU string `json:"cpu"`
	// The amount of memory in bytes
	RAM float64 `json:"ram"`
	// The sort order of the Postgres bouncer SKU
	SortOrder float64 `json:"sort_order"`
}

func (l *ListBranchBouncerResizeRequestsSku) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBranchBouncerResizeRequestsSku) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBranchBouncerResizeRequestsSku) GetCPU() string {
	if l == nil {
		return ""
	}
	return l.CPU
}

func (l *ListBranchBouncerResizeRequestsSku) GetRAM() float64 {
	if l == nil {
		return 0.0
	}
	return l.RAM
}

func (l *ListBranchBouncerResizeRequestsSku) GetSortOrder() float64 {
	if l == nil {
		return 0.0
	}
	return l.SortOrder
}

type ListBranchBouncerResizeRequestsPreviousSku struct {
	// The name of the Postgres bouncer SKU
	Name string `json:"name"`
	// The display name
	DisplayName string `json:"display_name"`
	// The CPU allocation
	CPU string `json:"cpu"`
	// The amount of memory in bytes
	RAM float64 `json:"ram"`
	// The sort order of the Postgres bouncer SKU
	SortOrder float64 `json:"sort_order"`
}

func (l *ListBranchBouncerResizeRequestsPreviousSku) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListBranchBouncerResizeRequestsPreviousSku) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListBranchBouncerResizeRequestsPreviousSku) GetCPU() string {
	if l == nil {
		return ""
	}
	return l.CPU
}

func (l *ListBranchBouncerResizeRequestsPreviousSku) GetRAM() float64 {
	if l == nil {
		return 0.0
	}
	return l.RAM
}

func (l *ListBranchBouncerResizeRequestsPreviousSku) GetSortOrder() float64 {
	if l == nil {
		return 0.0
	}
	return l.SortOrder
}

type ListBranchBouncerResizeRequestsData struct {
	// The ID of the bouncer resize
	ID string `json:"id"`
	// The state of the bouncer resize
	State ListBranchBouncerResizeRequestsState `json:"state"`
	// The number of replicas per cell for the bouncer after the resize
	ReplicasPerCell float64 `json:"replicas_per_cell"`
	// The bouncer parameters
	Parameters map[string]any `json:"parameters"`
	// The number of replicas per cell for the bouncer before the resize
	PreviousReplicasPerCell float64 `json:"previous_replicas_per_cell"`
	// The previous bouncer parameters
	PreviousParameters map[string]any `json:"previous_parameters"`
	// The time the bouncer resize started
	StartedAt string `json:"started_at"`
	// The time the bouncer resize completed
	CompletedAt string `json:"completed_at"`
	// The time the bouncer resize was created
	CreatedAt string `json:"created_at"`
	// The time the bouncer resize was last updated
	UpdatedAt   string                                     `json:"updated_at"`
	Actor       ListBranchBouncerResizeRequestsActor       `json:"actor"`
	Bouncer     ListBranchBouncerResizeRequestsBouncer     `json:"bouncer"`
	Sku         ListBranchBouncerResizeRequestsSku         `json:"sku"`
	PreviousSku ListBranchBouncerResizeRequestsPreviousSku `json:"previous_sku"`
}

func (l *ListBranchBouncerResizeRequestsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListBranchBouncerResizeRequestsData) GetState() ListBranchBouncerResizeRequestsState {
	if l == nil {
		return ListBranchBouncerResizeRequestsState("")
	}
	return l.State
}

func (l *ListBranchBouncerResizeRequestsData) GetReplicasPerCell() float64 {
	if l == nil {
		return 0.0
	}
	return l.ReplicasPerCell
}

func (l *ListBranchBouncerResizeRequestsData) GetParameters() map[string]any {
	if l == nil {
		return map[string]any{}
	}
	return l.Parameters
}

func (l *ListBranchBouncerResizeRequestsData) GetPreviousReplicasPerCell() float64 {
	if l == nil {
		return 0.0
	}
	return l.PreviousReplicasPerCell
}

func (l *ListBranchBouncerResizeRequestsData) GetPreviousParameters() map[string]any {
	if l == nil {
		return map[string]any{}
	}
	return l.PreviousParameters
}

func (l *ListBranchBouncerResizeRequestsData) GetStartedAt() string {
	if l == nil {
		return ""
	}
	return l.StartedAt
}

func (l *ListBranchBouncerResizeRequestsData) GetCompletedAt() string {
	if l == nil {
		return ""
	}
	return l.CompletedAt
}

func (l *ListBranchBouncerResizeRequestsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListBranchBouncerResizeRequestsData) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListBranchBouncerResizeRequestsData) GetActor() ListBranchBouncerResizeRequestsActor {
	if l == nil {
		return ListBranchBouncerResizeRequestsActor{}
	}
	return l.Actor
}

func (l *ListBranchBouncerResizeRequestsData) GetBouncer() ListBranchBouncerResizeRequestsBouncer {
	if l == nil {
		return ListBranchBouncerResizeRequestsBouncer{}
	}
	return l.Bouncer
}

func (l *ListBranchBouncerResizeRequestsData) GetSku() ListBranchBouncerResizeRequestsSku {
	if l == nil {
		return ListBranchBouncerResizeRequestsSku{}
	}
	return l.Sku
}

func (l *ListBranchBouncerResizeRequestsData) GetPreviousSku() ListBranchBouncerResizeRequestsPreviousSku {
	if l == nil {
		return ListBranchBouncerResizeRequestsPreviousSku{}
	}
	return l.PreviousSku
}

// ListBranchBouncerResizeRequestsResponseBody - Returns bouncer resize requests
type ListBranchBouncerResizeRequestsResponseBody struct {
	// The current page number
	CurrentPage float64 `json:"current_page"`
	// The next page number
	NextPage float64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage float64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string                                `json:"prev_page_url"`
	Data        []ListBranchBouncerResizeRequestsData `json:"data"`
}

func (l *ListBranchBouncerResizeRequestsResponseBody) GetCurrentPage() float64 {
	if l == nil {
		return 0.0
	}
	return l.CurrentPage
}

func (l *ListBranchBouncerResizeRequestsResponseBody) GetNextPage() float64 {
	if l == nil {
		return 0.0
	}
	return l.NextPage
}

func (l *ListBranchBouncerResizeRequestsResponseBody) GetNextPageURL() string {
	if l == nil {
		return ""
	}
	return l.NextPageURL
}

func (l *ListBranchBouncerResizeRequestsResponseBody) GetPrevPage() float64 {
	if l == nil {
		return 0.0
	}
	return l.PrevPage
}

func (l *ListBranchBouncerResizeRequestsResponseBody) GetPrevPageURL() string {
	if l == nil {
		return ""
	}
	return l.PrevPageURL
}

func (l *ListBranchBouncerResizeRequestsResponseBody) GetData() []ListBranchBouncerResizeRequestsData {
	if l == nil {
		return []ListBranchBouncerResizeRequestsData{}
	}
	return l.Data
}

type ListBranchBouncerResizeRequestsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns bouncer resize requests
	Object *ListBranchBouncerResizeRequestsResponseBody
}

func (l ListBranchBouncerResizeRequestsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListBranchBouncerResizeRequestsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (l *ListBranchBouncerResizeRequestsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListBranchBouncerResizeRequestsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListBranchBouncerResizeRequestsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListBranchBouncerResizeRequestsResponse) GetObject() *ListBranchBouncerResizeRequestsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
