// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListOauthApplicationsRequest struct {
	// The name of the organization the OAuth applications belong to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// If provided, specifies the page offset of returned results
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *int64 `default:"25" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListOauthApplicationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOauthApplicationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"organization"}); err != nil {
		return err
	}
	return nil
}

func (l *ListOauthApplicationsRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListOauthApplicationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListOauthApplicationsRequest) GetPerPage() *int64 {
	if l == nil {
		return nil
	}
	return l.PerPage
}

type ListOauthApplicationsData struct {
	// The ID of the app
	ID string `json:"id"`
	// The name of the app
	Name string `json:"name"`
	// The redirect URI of the OAuth application
	RedirectURI string `json:"redirect_uri"`
	// The domain of the OAuth application. Used for verification of a valid redirect uri
	Domain string `json:"domain"`
	// When the OAuth application was created
	CreatedAt string `json:"created_at"`
	// When the OAuth application was last updated
	UpdatedAt string `json:"updated_at"`
	// The scopes that the OAuth application requires on a user account
	Scopes []string `json:"scopes"`
	// The image source for the OAuth application's avatar
	Avatar string `json:"avatar"`
	// The OAuth application's unique client id
	ClientID string `json:"client_id"`
	// The number of tokens issued by the OAuth application
	Tokens int64 `json:"tokens"`
}

func (l *ListOauthApplicationsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListOauthApplicationsData) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListOauthApplicationsData) GetRedirectURI() string {
	if l == nil {
		return ""
	}
	return l.RedirectURI
}

func (l *ListOauthApplicationsData) GetDomain() string {
	if l == nil {
		return ""
	}
	return l.Domain
}

func (l *ListOauthApplicationsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListOauthApplicationsData) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListOauthApplicationsData) GetScopes() []string {
	if l == nil {
		return []string{}
	}
	return l.Scopes
}

func (l *ListOauthApplicationsData) GetAvatar() string {
	if l == nil {
		return ""
	}
	return l.Avatar
}

func (l *ListOauthApplicationsData) GetClientID() string {
	if l == nil {
		return ""
	}
	return l.ClientID
}

func (l *ListOauthApplicationsData) GetTokens() int64 {
	if l == nil {
		return 0
	}
	return l.Tokens
}

// ListOauthApplicationsResponseBody - Returns a list of the organization's oauth applications
type ListOauthApplicationsResponseBody struct {
	// The current page number
	CurrentPage int64 `json:"current_page"`
	// The next page number
	NextPage int64 `json:"next_page"`
	// The next page of results
	NextPageURL string `json:"next_page_url"`
	// The previous page number
	PrevPage int64 `json:"prev_page"`
	// The previous page of results
	PrevPageURL string                      `json:"prev_page_url"`
	Data        []ListOauthApplicationsData `json:"data"`
}

func (l *ListOauthApplicationsResponseBody) GetCurrentPage() int64 {
	if l == nil {
		return 0
	}
	return l.CurrentPage
}

func (l *ListOauthApplicationsResponseBody) GetNextPage() int64 {
	if l == nil {
		return 0
	}
	return l.NextPage
}

func (l *ListOauthApplicationsResponseBody) GetNextPageURL() string {
	if l == nil {
		return ""
	}
	return l.NextPageURL
}

func (l *ListOauthApplicationsResponseBody) GetPrevPage() int64 {
	if l == nil {
		return 0
	}
	return l.PrevPage
}

func (l *ListOauthApplicationsResponseBody) GetPrevPageURL() string {
	if l == nil {
		return ""
	}
	return l.PrevPageURL
}

func (l *ListOauthApplicationsResponseBody) GetData() []ListOauthApplicationsData {
	if l == nil {
		return []ListOauthApplicationsData{}
	}
	return l.Data
}

type ListOauthApplicationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a list of the organization's oauth applications
	Object *ListOauthApplicationsResponseBody
}

func (l ListOauthApplicationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOauthApplicationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (l *ListOauthApplicationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOauthApplicationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOauthApplicationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOauthApplicationsResponse) GetObject() *ListOauthApplicationsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
