// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListParametersRequest struct {
	// The name of the organization that owns this resource
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database that owns this resource
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch that owns this resource
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
}

func (l *ListParametersRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListParametersRequest) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

func (l *ListParametersRequest) GetBranch() string {
	if l == nil {
		return ""
	}
	return l.Branch
}

// ListParametersNamespace - The namespace of the parameter
type ListParametersNamespace string

const (
	ListParametersNamespacePatroni   ListParametersNamespace = "patroni"
	ListParametersNamespacePgconf    ListParametersNamespace = "pgconf"
	ListParametersNamespacePgbouncer ListParametersNamespace = "pgbouncer"
)

func (e ListParametersNamespace) ToPointer() *ListParametersNamespace {
	return &e
}
func (e *ListParametersNamespace) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "patroni":
		fallthrough
	case "pgconf":
		fallthrough
	case "pgbouncer":
		*e = ListParametersNamespace(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListParametersNamespace: %v", v)
	}
}

// ListParametersParameterType - The type of the parameter
type ListParametersParameterType string

const (
	ListParametersParameterTypeArray    ListParametersParameterType = "array"
	ListParametersParameterTypeBoolean  ListParametersParameterType = "boolean"
	ListParametersParameterTypeBytes    ListParametersParameterType = "bytes"
	ListParametersParameterTypeFloat    ListParametersParameterType = "float"
	ListParametersParameterTypeInteger  ListParametersParameterType = "integer"
	ListParametersParameterTypeInternal ListParametersParameterType = "internal"
	ListParametersParameterTypeSeconds  ListParametersParameterType = "seconds"
	ListParametersParameterTypeSelect   ListParametersParameterType = "select"
	ListParametersParameterTypeString   ListParametersParameterType = "string"
	ListParametersParameterTypeTime     ListParametersParameterType = "time"
)

func (e ListParametersParameterType) ToPointer() *ListParametersParameterType {
	return &e
}
func (e *ListParametersParameterType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "array":
		fallthrough
	case "boolean":
		fallthrough
	case "bytes":
		fallthrough
	case "float":
		fallthrough
	case "integer":
		fallthrough
	case "internal":
		fallthrough
	case "seconds":
		fallthrough
	case "select":
		fallthrough
	case "string":
		fallthrough
	case "time":
		*e = ListParametersParameterType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListParametersParameterType: %v", v)
	}
}

type ListParametersActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (l *ListParametersActor) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListParametersActor) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListParametersActor) GetAvatarURL() string {
	if l == nil {
		return ""
	}
	return l.AvatarURL
}

type ListParametersResponseBody struct {
	// The ID of the parameter
	ID string `json:"id"`
	// The name of the parameter
	Name string `json:"name"`
	// The display name of the parameter
	DisplayName string `json:"display_name"`
	// The namespace of the parameter
	Namespace ListParametersNamespace `json:"namespace"`
	// The category of the parameter
	Category string `json:"category"`
	// The description of the parameter
	Description string `json:"description"`
	// Configures an extension
	Extension bool `json:"extension"`
	// The internal state of the parameter
	Internal bool `json:"internal"`
	// The type of the parameter
	ParameterType ListParametersParameterType `json:"parameter_type"`
	// The default value of the parameter
	DefaultValue string `json:"default_value"`
	// The configured value of the parameter
	Value string `json:"value"`
	// Whether the parameter is required
	Required bool `json:"required"`
	// When the parameter was created
	CreatedAt string `json:"created_at"`
	// When the parameter was last updated
	UpdatedAt string `json:"updated_at"`
	// True if processes require a server restart on change
	Restart bool `json:"restart"`
	// The maximum value of the parameter
	Max float64 `json:"max"`
	// The minimum value of the parameter
	Min float64 `json:"min"`
	// The step change of the parameter
	Step float64 `json:"step"`
	// The URL of the parameter
	URL string `json:"url"`
	// Valid options for the parameter value
	Options []string            `json:"options"`
	Actor   ListParametersActor `json:"actor"`
}

func (l *ListParametersResponseBody) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListParametersResponseBody) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListParametersResponseBody) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListParametersResponseBody) GetNamespace() ListParametersNamespace {
	if l == nil {
		return ListParametersNamespace("")
	}
	return l.Namespace
}

func (l *ListParametersResponseBody) GetCategory() string {
	if l == nil {
		return ""
	}
	return l.Category
}

func (l *ListParametersResponseBody) GetDescription() string {
	if l == nil {
		return ""
	}
	return l.Description
}

func (l *ListParametersResponseBody) GetExtension() bool {
	if l == nil {
		return false
	}
	return l.Extension
}

func (l *ListParametersResponseBody) GetInternal() bool {
	if l == nil {
		return false
	}
	return l.Internal
}

func (l *ListParametersResponseBody) GetParameterType() ListParametersParameterType {
	if l == nil {
		return ListParametersParameterType("")
	}
	return l.ParameterType
}

func (l *ListParametersResponseBody) GetDefaultValue() string {
	if l == nil {
		return ""
	}
	return l.DefaultValue
}

func (l *ListParametersResponseBody) GetValue() string {
	if l == nil {
		return ""
	}
	return l.Value
}

func (l *ListParametersResponseBody) GetRequired() bool {
	if l == nil {
		return false
	}
	return l.Required
}

func (l *ListParametersResponseBody) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListParametersResponseBody) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListParametersResponseBody) GetRestart() bool {
	if l == nil {
		return false
	}
	return l.Restart
}

func (l *ListParametersResponseBody) GetMax() float64 {
	if l == nil {
		return 0.0
	}
	return l.Max
}

func (l *ListParametersResponseBody) GetMin() float64 {
	if l == nil {
		return 0.0
	}
	return l.Min
}

func (l *ListParametersResponseBody) GetStep() float64 {
	if l == nil {
		return 0.0
	}
	return l.Step
}

func (l *ListParametersResponseBody) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *ListParametersResponseBody) GetOptions() []string {
	if l == nil {
		return []string{}
	}
	return l.Options
}

func (l *ListParametersResponseBody) GetActor() ListParametersActor {
	if l == nil {
		return ListParametersActor{}
	}
	return l.Actor
}

type ListParametersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns cluster parameters
	ResponseBodies []ListParametersResponseBody
}

func (l ListParametersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListParametersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListParametersResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListParametersResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListParametersResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListParametersResponse) GetResponseBodies() []ListParametersResponseBody {
	if l == nil {
		return nil
	}
	return l.ResponseBodies
}
