// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type ListGeneratedQueryPatternsReportsRequest struct {
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
}

func (l *ListGeneratedQueryPatternsReportsRequest) GetOrganization() string {
	if l == nil {
		return ""
	}
	return l.Organization
}

func (l *ListGeneratedQueryPatternsReportsRequest) GetDatabase() string {
	if l == nil {
		return ""
	}
	return l.Database
}

func (l *ListGeneratedQueryPatternsReportsRequest) GetBranch() string {
	if l == nil {
		return ""
	}
	return l.Branch
}

// ListGeneratedQueryPatternsReportsState - The state of the download
type ListGeneratedQueryPatternsReportsState string

const (
	ListGeneratedQueryPatternsReportsStatePending   ListGeneratedQueryPatternsReportsState = "pending"
	ListGeneratedQueryPatternsReportsStateCompleted ListGeneratedQueryPatternsReportsState = "completed"
	ListGeneratedQueryPatternsReportsStateFailed    ListGeneratedQueryPatternsReportsState = "failed"
)

func (e ListGeneratedQueryPatternsReportsState) ToPointer() *ListGeneratedQueryPatternsReportsState {
	return &e
}
func (e *ListGeneratedQueryPatternsReportsState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "completed":
		fallthrough
	case "failed":
		*e = ListGeneratedQueryPatternsReportsState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListGeneratedQueryPatternsReportsState: %v", v)
	}
}

type ListGeneratedQueryPatternsReportsActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (l *ListGeneratedQueryPatternsReportsActor) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGeneratedQueryPatternsReportsActor) GetDisplayName() string {
	if l == nil {
		return ""
	}
	return l.DisplayName
}

func (l *ListGeneratedQueryPatternsReportsActor) GetAvatarURL() string {
	if l == nil {
		return ""
	}
	return l.AvatarURL
}

type ListGeneratedQueryPatternsReportsData struct {
	// The ID of the query patterns download
	ID string `json:"id"`
	// The state of the download
	State ListGeneratedQueryPatternsReportsState `json:"state"`
	// When the download was created
	CreatedAt string `json:"created_at"`
	// When the download was finished
	FinishedAt string `json:"finished_at"`
	// The URL to access the query patterns download
	URL string `json:"url"`
	// The URL to download the query patterns file
	DownloadURL string                                 `json:"download_url"`
	Actor       ListGeneratedQueryPatternsReportsActor `json:"actor"`
}

func (l *ListGeneratedQueryPatternsReportsData) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListGeneratedQueryPatternsReportsData) GetState() ListGeneratedQueryPatternsReportsState {
	if l == nil {
		return ListGeneratedQueryPatternsReportsState("")
	}
	return l.State
}

func (l *ListGeneratedQueryPatternsReportsData) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListGeneratedQueryPatternsReportsData) GetFinishedAt() string {
	if l == nil {
		return ""
	}
	return l.FinishedAt
}

func (l *ListGeneratedQueryPatternsReportsData) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *ListGeneratedQueryPatternsReportsData) GetDownloadURL() string {
	if l == nil {
		return ""
	}
	return l.DownloadURL
}

func (l *ListGeneratedQueryPatternsReportsData) GetActor() ListGeneratedQueryPatternsReportsActor {
	if l == nil {
		return ListGeneratedQueryPatternsReportsActor{}
	}
	return l.Actor
}

// ListGeneratedQueryPatternsReportsResponseBody - Returns the generated query patterns reports
type ListGeneratedQueryPatternsReportsResponseBody struct {
	// Whether there is a next page of results
	HasNext bool `json:"has_next"`
	// Whether there is a previous page of results
	HasPrev bool `json:"has_prev"`
	// The ID of the first object in the current results
	CursorStart string `json:"cursor_start"`
	// The ID of the last object in the current results
	CursorEnd string                                  `json:"cursor_end"`
	Data      []ListGeneratedQueryPatternsReportsData `json:"data"`
}

func (l *ListGeneratedQueryPatternsReportsResponseBody) GetHasNext() bool {
	if l == nil {
		return false
	}
	return l.HasNext
}

func (l *ListGeneratedQueryPatternsReportsResponseBody) GetHasPrev() bool {
	if l == nil {
		return false
	}
	return l.HasPrev
}

func (l *ListGeneratedQueryPatternsReportsResponseBody) GetCursorStart() string {
	if l == nil {
		return ""
	}
	return l.CursorStart
}

func (l *ListGeneratedQueryPatternsReportsResponseBody) GetCursorEnd() string {
	if l == nil {
		return ""
	}
	return l.CursorEnd
}

func (l *ListGeneratedQueryPatternsReportsResponseBody) GetData() []ListGeneratedQueryPatternsReportsData {
	if l == nil {
		return []ListGeneratedQueryPatternsReportsData{}
	}
	return l.Data
}

type ListGeneratedQueryPatternsReportsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the generated query patterns reports
	Object *ListGeneratedQueryPatternsReportsResponseBody
}

func (l ListGeneratedQueryPatternsReportsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListGeneratedQueryPatternsReportsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (l *ListGeneratedQueryPatternsReportsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListGeneratedQueryPatternsReportsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListGeneratedQueryPatternsReportsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListGeneratedQueryPatternsReportsResponse) GetObject() *ListGeneratedQueryPatternsReportsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
