// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type UpdateNekiSidecarRequestBody struct {
	// Desired effective sidecar parameter values nested by namespace, e.g. { sidecar = { pool-capacity = "100" } }. When configured, Terraform sends the complete map and resets omitted customer-configurable parameters to their defaults. The API identifies Terraform requests by the provider User-Agent.
	Parameters map[string]map[string]string `json:"parameters,omitzero"`
}

func (u UpdateNekiSidecarRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateNekiSidecarRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateNekiSidecarRequestBody) GetParameters() map[string]map[string]string {
	if u == nil {
		return nil
	}
	return u.Parameters
}

type UpdateNekiSidecarRequest struct {
	// Organization name slug from `list_organizations`. Example: `acme`.
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// Database name slug from `list_databases`. Example: `app-db`.
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// Branch name from `list_branches`. Example: `main`.
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The name of the shard configuration profile that owns the sidecar. The API also accepts a sidecar ID here, but Terraform stores the profile name returned by the API, so configure the profile name.
	ConfigurationProfile string                        `pathParam:"style=simple,explode=false,name=sidecar"`
	Body                 *UpdateNekiSidecarRequestBody `request:"mediaType=application/json"`
}

func (u UpdateNekiSidecarRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateNekiSidecarRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateNekiSidecarRequest) GetOrganization() string {
	if u == nil {
		return ""
	}
	return u.Organization
}

func (u *UpdateNekiSidecarRequest) GetDatabase() string {
	if u == nil {
		return ""
	}
	return u.Database
}

func (u *UpdateNekiSidecarRequest) GetBranch() string {
	if u == nil {
		return ""
	}
	return u.Branch
}

func (u *UpdateNekiSidecarRequest) GetConfigurationProfile() string {
	if u == nil {
		return ""
	}
	return u.ConfigurationProfile
}

func (u *UpdateNekiSidecarRequest) GetBody() *UpdateNekiSidecarRequestBody {
	if u == nil {
		return nil
	}
	return u.Body
}

// UpdateNekiSidecarState - The current state of the sidecar
type UpdateNekiSidecarState string

const (
	UpdateNekiSidecarStatePending  UpdateNekiSidecarState = "pending"
	UpdateNekiSidecarStateApplying UpdateNekiSidecarState = "applying"
	UpdateNekiSidecarStateReady    UpdateNekiSidecarState = "ready"
)

func (e UpdateNekiSidecarState) ToPointer() *UpdateNekiSidecarState {
	return &e
}
func (e *UpdateNekiSidecarState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "applying":
		fallthrough
	case "ready":
		*e = UpdateNekiSidecarState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateNekiSidecarState: %v", v)
	}
}

// UpdateNekiSidecarResponseBody - Returns the sidecar
type UpdateNekiSidecarResponseBody struct {
	// The ID of the sidecar
	ID string `json:"id"`
	// The name of the shard configuration profile the sidecar belongs to
	ConfigurationProfile string `json:"configuration_profile"`
	// The current state of the sidecar
	State UpdateNekiSidecarState `json:"state"`
}

func (u *UpdateNekiSidecarResponseBody) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateNekiSidecarResponseBody) GetConfigurationProfile() string {
	if u == nil {
		return ""
	}
	return u.ConfigurationProfile
}

func (u *UpdateNekiSidecarResponseBody) GetState() UpdateNekiSidecarState {
	if u == nil {
		return UpdateNekiSidecarState("")
	}
	return u.State
}

type UpdateNekiSidecarResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the sidecar
	Object *UpdateNekiSidecarResponseBody
}

func (u UpdateNekiSidecarResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateNekiSidecarResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateNekiSidecarResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateNekiSidecarResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateNekiSidecarResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateNekiSidecarResponse) GetObject() *UpdateNekiSidecarResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
