// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type UpdatePostgresDatabaseRequestBody struct {
	// The name to update the database to
	Name *string `json:"name,omitzero"`
	// Whether or not deploy requests must be approved by a database administrator other than the request creator
	RequireApprovalForDeploy *bool `json:"require_approval_for_deploy,omitzero"`
	// Whether or not to limit branch creation to the same region as the one selected during database creation.
	RestrictBranchRegion *bool `json:"restrict_branch_region,omitzero"`
	// Whether or not full queries should be collected from the database
	InsightsRawQueries *bool `json:"insights_raw_queries,omitzero"`
	// Whether or not the web console can be used on the production branch of the database
	ProductionBranchWebConsole *bool `json:"production_branch_web_console,omitzero"`
	// The default branch of the database
	DefaultBranch *string `json:"default_branch,omitzero"`
}

func (u *UpdatePostgresDatabaseRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdatePostgresDatabaseRequestBody) GetRequireApprovalForDeploy() *bool {
	if u == nil {
		return nil
	}
	return u.RequireApprovalForDeploy
}

func (u *UpdatePostgresDatabaseRequestBody) GetRestrictBranchRegion() *bool {
	if u == nil {
		return nil
	}
	return u.RestrictBranchRegion
}

func (u *UpdatePostgresDatabaseRequestBody) GetInsightsRawQueries() *bool {
	if u == nil {
		return nil
	}
	return u.InsightsRawQueries
}

func (u *UpdatePostgresDatabaseRequestBody) GetProductionBranchWebConsole() *bool {
	if u == nil {
		return nil
	}
	return u.ProductionBranchWebConsole
}

func (u *UpdatePostgresDatabaseRequestBody) GetDefaultBranch() *string {
	if u == nil {
		return nil
	}
	return u.DefaultBranch
}

type UpdatePostgresDatabaseRequest struct {
	// The name of the organization the database belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The ID of the database
	Database string                             `pathParam:"style=simple,explode=false,name=database"`
	Body     *UpdatePostgresDatabaseRequestBody `request:"mediaType=application/json"`
}

func (u UpdatePostgresDatabaseRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePostgresDatabaseRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"organization", "database"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePostgresDatabaseRequest) GetOrganization() string {
	if u == nil {
		return ""
	}
	return u.Organization
}

func (u *UpdatePostgresDatabaseRequest) GetDatabase() string {
	if u == nil {
		return ""
	}
	return u.Database
}

func (u *UpdatePostgresDatabaseRequest) GetBody() *UpdatePostgresDatabaseRequestBody {
	if u == nil {
		return nil
	}
	return u.Body
}

// UpdatePostgresDatabaseResponseBody - Returns the updated database
type UpdatePostgresDatabaseResponseBody struct {
	// The ID of the database
	ID *string `json:"id,omitzero"`
}

func (u *UpdatePostgresDatabaseResponseBody) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

type UpdatePostgresDatabaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the updated database
	Object *UpdatePostgresDatabaseResponseBody
}

func (u UpdatePostgresDatabaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePostgresDatabaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePostgresDatabaseResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePostgresDatabaseResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePostgresDatabaseResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdatePostgresDatabaseResponse) GetObject() *UpdatePostgresDatabaseResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
