// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type UpdatePasswordRequestBody struct {
	// The name for the password
	Name *string `json:"name,omitzero"`
	// List of IP addresses or CIDR ranges that can use this password
	Cidrs []string `json:"cidrs,omitzero"`
}

func (u UpdatePasswordRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePasswordRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePasswordRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdatePasswordRequestBody) GetCidrs() []string {
	if u == nil {
		return nil
	}
	return u.Cidrs
}

type UpdatePasswordRequest struct {
	// The name of the organization the password belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database the password belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch the password belongs to
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The ID of the password
	ID   string                     `pathParam:"style=simple,explode=false,name=id"`
	Body *UpdatePasswordRequestBody `request:"mediaType=application/json"`
}

func (u UpdatePasswordRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePasswordRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"organization", "database", "branch", "id"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePasswordRequest) GetOrganization() string {
	if u == nil {
		return ""
	}
	return u.Organization
}

func (u *UpdatePasswordRequest) GetDatabase() string {
	if u == nil {
		return ""
	}
	return u.Database
}

func (u *UpdatePasswordRequest) GetBranch() string {
	if u == nil {
		return ""
	}
	return u.Branch
}

func (u *UpdatePasswordRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePasswordRequest) GetBody() *UpdatePasswordRequestBody {
	if u == nil {
		return nil
	}
	return u.Body
}

// UpdatePasswordRole - The role for the password
type UpdatePasswordRole string

const (
	UpdatePasswordRoleReader     UpdatePasswordRole = "reader"
	UpdatePasswordRoleWriter     UpdatePasswordRole = "writer"
	UpdatePasswordRoleAdmin      UpdatePasswordRole = "admin"
	UpdatePasswordRoleReadwriter UpdatePasswordRole = "readwriter"
)

func (e UpdatePasswordRole) ToPointer() *UpdatePasswordRole {
	return &e
}
func (e *UpdatePasswordRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "reader":
		fallthrough
	case "writer":
		fallthrough
	case "admin":
		fallthrough
	case "readwriter":
		*e = UpdatePasswordRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdatePasswordRole: %v", v)
	}
}

type UpdatePasswordActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (u *UpdatePasswordActor) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePasswordActor) GetDisplayName() string {
	if u == nil {
		return ""
	}
	return u.DisplayName
}

func (u *UpdatePasswordActor) GetAvatarURL() string {
	if u == nil {
		return ""
	}
	return u.AvatarURL
}

type UpdatePasswordRegion struct {
	// The ID of the region
	ID string `json:"id"`
	// Provider for the region (ex. AWS)
	Provider string `json:"provider"`
	// Whether or not the region is currently active
	Enabled bool `json:"enabled"`
	// Public IP addresses for the region
	PublicIPAddresses []string `json:"public_ip_addresses"`
	// Name of the region
	DisplayName string `json:"display_name"`
	// Location of the region
	Location string `json:"location"`
	// The slug of the region
	Slug string `json:"slug"`
	// True if the region is the default for new branch creation
	CurrentDefault bool `json:"current_default"`
}

func (u *UpdatePasswordRegion) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePasswordRegion) GetProvider() string {
	if u == nil {
		return ""
	}
	return u.Provider
}

func (u *UpdatePasswordRegion) GetEnabled() bool {
	if u == nil {
		return false
	}
	return u.Enabled
}

func (u *UpdatePasswordRegion) GetPublicIPAddresses() []string {
	if u == nil {
		return []string{}
	}
	return u.PublicIPAddresses
}

func (u *UpdatePasswordRegion) GetDisplayName() string {
	if u == nil {
		return ""
	}
	return u.DisplayName
}

func (u *UpdatePasswordRegion) GetLocation() string {
	if u == nil {
		return ""
	}
	return u.Location
}

func (u *UpdatePasswordRegion) GetSlug() string {
	if u == nil {
		return ""
	}
	return u.Slug
}

func (u *UpdatePasswordRegion) GetCurrentDefault() bool {
	if u == nil {
		return false
	}
	return u.CurrentDefault
}

type UpdatePasswordDatabaseBranch struct {
	// The name for the branch
	Name string `json:"name"`
	// The ID for the branch
	ID string `json:"id"`
	// Whether or not the branch is a production branch
	Production bool `json:"production"`
	// The address of the MySQL provider for the branch
	MysqlEdgeAddress string `json:"mysql_edge_address"`
	// True if private connectivity is enabled
	PrivateEdgeConnectivity bool `json:"private_edge_connectivity"`
}

func (u *UpdatePasswordDatabaseBranch) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdatePasswordDatabaseBranch) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePasswordDatabaseBranch) GetProduction() bool {
	if u == nil {
		return false
	}
	return u.Production
}

func (u *UpdatePasswordDatabaseBranch) GetMysqlEdgeAddress() string {
	if u == nil {
		return ""
	}
	return u.MysqlEdgeAddress
}

func (u *UpdatePasswordDatabaseBranch) GetPrivateEdgeConnectivity() bool {
	if u == nil {
		return false
	}
	return u.PrivateEdgeConnectivity
}

// UpdatePasswordResponseBody - Returns the updated password
type UpdatePasswordResponseBody struct {
	// The ID for the password
	ID string `json:"id"`
	// The display name for the password
	Name string `json:"name"`
	// The role for the password
	Role UpdatePasswordRole `json:"role"`
	// List of IP addresses or CIDR ranges that can use this password
	Cidrs []string `json:"cidrs"`
	// When the password was created
	CreatedAt string `json:"created_at"`
	// When the password was deleted
	DeletedAt string `json:"deleted_at"`
	// When the password will expire
	ExpiresAt string `json:"expires_at"`
	// When the password was last used to execute a query
	LastUsedAt string `json:"last_used_at"`
	// True if the credentials are expired
	Expired bool `json:"expired"`
	// True if the credentials connect directly to a vtgate, bypassing load balancers
	DirectVtgate bool `json:"direct_vtgate"`
	// The list of hosts in each availability zone providing direct access to a vtgate
	DirectVtgateAddresses []string `json:"direct_vtgate_addresses"`
	// Time to live (in seconds) for the password. The password will be invalid when TTL has passed
	TTLSeconds float64 `json:"ttl_seconds"`
	// The host URL for the password
	AccessHostURL string `json:"access_host_url"`
	// The regional host URL
	AccessHostRegionalURL string `json:"access_host_regional_url"`
	// The read-only replica host URLs
	AccessHostRegionalUrls []string             `json:"access_host_regional_urls"`
	Actor                  UpdatePasswordActor  `json:"actor"`
	Region                 UpdatePasswordRegion `json:"region"`
	// The username for the password
	Username string `json:"username"`
	// The plain text password, available only after create
	PlainText string `json:"plain_text"`
	// Whether or not the password is for a read replica
	Replica bool `json:"replica"`
	// Whether or not the password can be renewed
	Renewable      bool                         `json:"renewable"`
	DatabaseBranch UpdatePasswordDatabaseBranch `json:"database_branch"`
}

func (u *UpdatePasswordResponseBody) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePasswordResponseBody) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdatePasswordResponseBody) GetRole() UpdatePasswordRole {
	if u == nil {
		return UpdatePasswordRole("")
	}
	return u.Role
}

func (u *UpdatePasswordResponseBody) GetCidrs() []string {
	if u == nil {
		return []string{}
	}
	return u.Cidrs
}

func (u *UpdatePasswordResponseBody) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdatePasswordResponseBody) GetDeletedAt() string {
	if u == nil {
		return ""
	}
	return u.DeletedAt
}

func (u *UpdatePasswordResponseBody) GetExpiresAt() string {
	if u == nil {
		return ""
	}
	return u.ExpiresAt
}

func (u *UpdatePasswordResponseBody) GetLastUsedAt() string {
	if u == nil {
		return ""
	}
	return u.LastUsedAt
}

func (u *UpdatePasswordResponseBody) GetExpired() bool {
	if u == nil {
		return false
	}
	return u.Expired
}

func (u *UpdatePasswordResponseBody) GetDirectVtgate() bool {
	if u == nil {
		return false
	}
	return u.DirectVtgate
}

func (u *UpdatePasswordResponseBody) GetDirectVtgateAddresses() []string {
	if u == nil {
		return []string{}
	}
	return u.DirectVtgateAddresses
}

func (u *UpdatePasswordResponseBody) GetTTLSeconds() float64 {
	if u == nil {
		return 0.0
	}
	return u.TTLSeconds
}

func (u *UpdatePasswordResponseBody) GetAccessHostURL() string {
	if u == nil {
		return ""
	}
	return u.AccessHostURL
}

func (u *UpdatePasswordResponseBody) GetAccessHostRegionalURL() string {
	if u == nil {
		return ""
	}
	return u.AccessHostRegionalURL
}

func (u *UpdatePasswordResponseBody) GetAccessHostRegionalUrls() []string {
	if u == nil {
		return []string{}
	}
	return u.AccessHostRegionalUrls
}

func (u *UpdatePasswordResponseBody) GetActor() UpdatePasswordActor {
	if u == nil {
		return UpdatePasswordActor{}
	}
	return u.Actor
}

func (u *UpdatePasswordResponseBody) GetRegion() UpdatePasswordRegion {
	if u == nil {
		return UpdatePasswordRegion{}
	}
	return u.Region
}

func (u *UpdatePasswordResponseBody) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *UpdatePasswordResponseBody) GetPlainText() string {
	if u == nil {
		return ""
	}
	return u.PlainText
}

func (u *UpdatePasswordResponseBody) GetReplica() bool {
	if u == nil {
		return false
	}
	return u.Replica
}

func (u *UpdatePasswordResponseBody) GetRenewable() bool {
	if u == nil {
		return false
	}
	return u.Renewable
}

func (u *UpdatePasswordResponseBody) GetDatabaseBranch() UpdatePasswordDatabaseBranch {
	if u == nil {
		return UpdatePasswordDatabaseBranch{}
	}
	return u.DatabaseBranch
}

type UpdatePasswordResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the updated password
	Object *UpdatePasswordResponseBody
}

func (u UpdatePasswordResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePasswordResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePasswordResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePasswordResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePasswordResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdatePasswordResponse) GetObject() *UpdatePasswordResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
