// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"net/http"
)

type UpdateBouncerResizeRequestRequestBody struct {
	// The bouncer size SKU name (e.g., 'PGB_5', 'PGB_10', 'PGB_20', 'PGB_40', 'PGB_80', 'PGB_160'). Defaults to 'PGB_5'.
	BouncerSize *string `json:"bouncer_size,omitzero"`
	// The number of PgBouncers per availability zone. Defaults to 1.
	ReplicasPerCell *int64 `json:"replicas_per_cell,omitzero"`
	// Bouncer configuration parameters nested by namespace (e.g., {"pgbouncer": {"default_pool_size": "100"}}). Use the 'List cluster parameters' endpoint to retrieve available parameters. Only parameters with namespace 'pgbouncer' can be updated.
	Parameters map[string]any `json:"parameters,omitzero"`
}

func (u UpdateBouncerResizeRequestRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateBouncerResizeRequestRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateBouncerResizeRequestRequestBody) GetBouncerSize() *string {
	if u == nil {
		return nil
	}
	return u.BouncerSize
}

func (u *UpdateBouncerResizeRequestRequestBody) GetReplicasPerCell() *int64 {
	if u == nil {
		return nil
	}
	return u.ReplicasPerCell
}

func (u *UpdateBouncerResizeRequestRequestBody) GetParameters() map[string]any {
	if u == nil {
		return nil
	}
	return u.Parameters
}

type UpdateBouncerResizeRequestRequest struct {
	// The name of the organization that owns this resource
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The name of the database that owns this resource
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch that owns this resource
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The name of the bouncer
	Bouncer string                                 `pathParam:"style=simple,explode=false,name=bouncer"`
	Body    *UpdateBouncerResizeRequestRequestBody `request:"mediaType=application/json"`
}

func (u UpdateBouncerResizeRequestRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateBouncerResizeRequestRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"organization", "database", "branch", "bouncer"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateBouncerResizeRequestRequest) GetOrganization() string {
	if u == nil {
		return ""
	}
	return u.Organization
}

func (u *UpdateBouncerResizeRequestRequest) GetDatabase() string {
	if u == nil {
		return ""
	}
	return u.Database
}

func (u *UpdateBouncerResizeRequestRequest) GetBranch() string {
	if u == nil {
		return ""
	}
	return u.Branch
}

func (u *UpdateBouncerResizeRequestRequest) GetBouncer() string {
	if u == nil {
		return ""
	}
	return u.Bouncer
}

func (u *UpdateBouncerResizeRequestRequest) GetBody() *UpdateBouncerResizeRequestRequestBody {
	if u == nil {
		return nil
	}
	return u.Body
}

// UpdateBouncerResizeRequestState - The state of the bouncer resize
type UpdateBouncerResizeRequestState string

const (
	UpdateBouncerResizeRequestStatePending   UpdateBouncerResizeRequestState = "pending"
	UpdateBouncerResizeRequestStateResizing  UpdateBouncerResizeRequestState = "resizing"
	UpdateBouncerResizeRequestStateCanceled  UpdateBouncerResizeRequestState = "canceled"
	UpdateBouncerResizeRequestStateCompleted UpdateBouncerResizeRequestState = "completed"
)

func (e UpdateBouncerResizeRequestState) ToPointer() *UpdateBouncerResizeRequestState {
	return &e
}
func (e *UpdateBouncerResizeRequestState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "resizing":
		fallthrough
	case "canceled":
		fallthrough
	case "completed":
		*e = UpdateBouncerResizeRequestState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateBouncerResizeRequestState: %v", v)
	}
}

type UpdateBouncerResizeRequestActor struct {
	// The ID of the actor
	ID string `json:"id"`
	// The name of the actor
	DisplayName string `json:"display_name"`
	// The URL of the actor's avatar
	AvatarURL string `json:"avatar_url"`
}

func (u *UpdateBouncerResizeRequestActor) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBouncerResizeRequestActor) GetDisplayName() string {
	if u == nil {
		return ""
	}
	return u.DisplayName
}

func (u *UpdateBouncerResizeRequestActor) GetAvatarURL() string {
	if u == nil {
		return ""
	}
	return u.AvatarURL
}

type UpdateBouncerResizeRequestBouncer struct {
	// The ID for the resource
	ID string `json:"id"`
	// The name for the resource
	Name string `json:"name"`
	// When the resource was created
	CreatedAt string `json:"created_at"`
	// When the resource was last updated
	UpdatedAt string `json:"updated_at"`
	// When the resource was deleted, if deleted
	DeletedAt string `json:"deleted_at"`
}

func (u *UpdateBouncerResizeRequestBouncer) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBouncerResizeRequestBouncer) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateBouncerResizeRequestBouncer) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateBouncerResizeRequestBouncer) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateBouncerResizeRequestBouncer) GetDeletedAt() string {
	if u == nil {
		return ""
	}
	return u.DeletedAt
}

type UpdateBouncerResizeRequestSku struct {
	// The name of the Postgres bouncer SKU
	Name string `json:"name"`
	// The display name
	DisplayName string `json:"display_name"`
	// The CPU allocation
	CPU string `json:"cpu"`
	// The amount of memory in bytes
	RAM int64 `json:"ram"`
	// The sort order of the Postgres bouncer SKU
	SortOrder int64 `json:"sort_order"`
}

func (u *UpdateBouncerResizeRequestSku) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateBouncerResizeRequestSku) GetDisplayName() string {
	if u == nil {
		return ""
	}
	return u.DisplayName
}

func (u *UpdateBouncerResizeRequestSku) GetCPU() string {
	if u == nil {
		return ""
	}
	return u.CPU
}

func (u *UpdateBouncerResizeRequestSku) GetRAM() int64 {
	if u == nil {
		return 0
	}
	return u.RAM
}

func (u *UpdateBouncerResizeRequestSku) GetSortOrder() int64 {
	if u == nil {
		return 0
	}
	return u.SortOrder
}

type UpdateBouncerResizeRequestPreviousSku struct {
	// The name of the Postgres bouncer SKU
	Name string `json:"name"`
	// The display name
	DisplayName string `json:"display_name"`
	// The CPU allocation
	CPU string `json:"cpu"`
	// The amount of memory in bytes
	RAM int64 `json:"ram"`
	// The sort order of the Postgres bouncer SKU
	SortOrder int64 `json:"sort_order"`
}

func (u *UpdateBouncerResizeRequestPreviousSku) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateBouncerResizeRequestPreviousSku) GetDisplayName() string {
	if u == nil {
		return ""
	}
	return u.DisplayName
}

func (u *UpdateBouncerResizeRequestPreviousSku) GetCPU() string {
	if u == nil {
		return ""
	}
	return u.CPU
}

func (u *UpdateBouncerResizeRequestPreviousSku) GetRAM() int64 {
	if u == nil {
		return 0
	}
	return u.RAM
}

func (u *UpdateBouncerResizeRequestPreviousSku) GetSortOrder() int64 {
	if u == nil {
		return 0
	}
	return u.SortOrder
}

// UpdateBouncerResizeRequestResponseBody - Returns bouncer resize request
type UpdateBouncerResizeRequestResponseBody struct {
	// The ID of the bouncer resize
	ID string `json:"id"`
	// The state of the bouncer resize
	State UpdateBouncerResizeRequestState `json:"state"`
	// The number of replicas per cell for the bouncer after the resize
	ReplicasPerCell int64 `json:"replicas_per_cell"`
	// The bouncer parameters
	Parameters map[string]any `json:"parameters"`
	// The number of replicas per cell for the bouncer before the resize
	PreviousReplicasPerCell int64 `json:"previous_replicas_per_cell"`
	// The previous bouncer parameters
	PreviousParameters map[string]any `json:"previous_parameters"`
	// The time the bouncer resize started
	StartedAt string `json:"started_at"`
	// The time the bouncer resize completed
	CompletedAt string `json:"completed_at"`
	// The time the bouncer resize was created
	CreatedAt string `json:"created_at"`
	// The time the bouncer resize was last updated
	UpdatedAt   string                                `json:"updated_at"`
	Actor       UpdateBouncerResizeRequestActor       `json:"actor"`
	Bouncer     UpdateBouncerResizeRequestBouncer     `json:"bouncer"`
	Sku         UpdateBouncerResizeRequestSku         `json:"sku"`
	PreviousSku UpdateBouncerResizeRequestPreviousSku `json:"previous_sku"`
}

func (u *UpdateBouncerResizeRequestResponseBody) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBouncerResizeRequestResponseBody) GetState() UpdateBouncerResizeRequestState {
	if u == nil {
		return UpdateBouncerResizeRequestState("")
	}
	return u.State
}

func (u *UpdateBouncerResizeRequestResponseBody) GetReplicasPerCell() int64 {
	if u == nil {
		return 0
	}
	return u.ReplicasPerCell
}

func (u *UpdateBouncerResizeRequestResponseBody) GetParameters() map[string]any {
	if u == nil {
		return map[string]any{}
	}
	return u.Parameters
}

func (u *UpdateBouncerResizeRequestResponseBody) GetPreviousReplicasPerCell() int64 {
	if u == nil {
		return 0
	}
	return u.PreviousReplicasPerCell
}

func (u *UpdateBouncerResizeRequestResponseBody) GetPreviousParameters() map[string]any {
	if u == nil {
		return map[string]any{}
	}
	return u.PreviousParameters
}

func (u *UpdateBouncerResizeRequestResponseBody) GetStartedAt() string {
	if u == nil {
		return ""
	}
	return u.StartedAt
}

func (u *UpdateBouncerResizeRequestResponseBody) GetCompletedAt() string {
	if u == nil {
		return ""
	}
	return u.CompletedAt
}

func (u *UpdateBouncerResizeRequestResponseBody) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateBouncerResizeRequestResponseBody) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateBouncerResizeRequestResponseBody) GetActor() UpdateBouncerResizeRequestActor {
	if u == nil {
		return UpdateBouncerResizeRequestActor{}
	}
	return u.Actor
}

func (u *UpdateBouncerResizeRequestResponseBody) GetBouncer() UpdateBouncerResizeRequestBouncer {
	if u == nil {
		return UpdateBouncerResizeRequestBouncer{}
	}
	return u.Bouncer
}

func (u *UpdateBouncerResizeRequestResponseBody) GetSku() UpdateBouncerResizeRequestSku {
	if u == nil {
		return UpdateBouncerResizeRequestSku{}
	}
	return u.Sku
}

func (u *UpdateBouncerResizeRequestResponseBody) GetPreviousSku() UpdateBouncerResizeRequestPreviousSku {
	if u == nil {
		return UpdateBouncerResizeRequestPreviousSku{}
	}
	return u.PreviousSku
}

type UpdateBouncerResizeRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns bouncer resize request
	Object *UpdateBouncerResizeRequestResponseBody
}

func (u UpdateBouncerResizeRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateBouncerResizeRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateBouncerResizeRequestResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateBouncerResizeRequestResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateBouncerResizeRequestResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateBouncerResizeRequestResponse) GetObject() *UpdateBouncerResizeRequestResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
