// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NekiShard struct {
	// The ID of the shard
	ID string `json:"id"`
	// The name of the shard
	Name string `json:"name"`
	// The display name of the shard
	DisplayName *string `json:"display_name"`
	// The name of the shard configuration profile
	ConfigurationProfile string `json:"configuration_profile"`
	// When the shard was created
	CreatedAt string `json:"created_at"`
	// Whether the shard has been created on the cluster
	Ready bool `json:"ready"`
	// Whether the shard is the authoritative shard of the cluster
	Authoritative bool `json:"authoritative"`
}

func (n *NekiShard) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NekiShard) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NekiShard) GetDisplayName() *string {
	if n == nil {
		return nil
	}
	return n.DisplayName
}

func (n *NekiShard) GetConfigurationProfile() string {
	if n == nil {
		return ""
	}
	return n.ConfigurationProfile
}

func (n *NekiShard) GetCreatedAt() string {
	if n == nil {
		return ""
	}
	return n.CreatedAt
}

func (n *NekiShard) GetReady() bool {
	if n == nil {
		return false
	}
	return n.Ready
}

func (n *NekiShard) GetAuthoritative() bool {
	if n == nil {
		return false
	}
	return n.Authoritative
}
