// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/internal/utils"
	"time"
)

type NekiShard struct {
	// The ID of the shard.
	ID string `json:"id"`
	// The internal name of the shard.
	Name string `json:"name"`
	// The display name of the shard.
	DisplayName *string `json:"display_name,omitzero"`
	// The name of the shard configuration profile.
	ConfigurationProfile string    `json:"configuration_profile"`
	CreatedAt            time.Time `json:"created_at"`
	// Whether the shard is ready.
	Ready bool `json:"ready"`
}

func (n NekiShard) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NekiShard) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NekiShard) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *NekiShard) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NekiShard) GetDisplayName() *string {
	if n == nil {
		return nil
	}
	return n.DisplayName
}

func (n *NekiShard) GetConfigurationProfile() string {
	if n == nil {
		return ""
	}
	return n.ConfigurationProfile
}

func (n *NekiShard) GetCreatedAt() time.Time {
	if n == nil {
		return time.Time{}
	}
	return n.CreatedAt
}

func (n *NekiShard) GetReady() bool {
	if n == nil {
		return false
	}
	return n.Ready
}
