workflowVersion: 1.0.0
speakeasyVersion: 1.668.0
sources:
    PlanetScale API:
        inputs:
            - location: schemas/openapi.yaml
        overlays:
            - location: schemas/overlay-terraform.yaml
            - location: schemas/overlay-terraform-branch.yaml
            - location: schemas/overlay-terraform-branch_schema.yaml
            - location: schemas/overlay-terraform-branches.yaml
            - location: schemas/overlay-terraform-database_vitess.yaml
            - location: schemas/overlay-terraform-database_postgres.yaml
            - location: schemas/overlay-terraform-database_default_branch.yaml
            - location: schemas/overlay-terraform-database_regions.yaml
            - location: schemas/overlay-terraform-database_read_only_regions.yaml
            - location: schemas/overlay-terraform-databases.yaml
            - location: schemas/overlay-terraform-organization.yaml
            - location: schemas/overlay-terraform-organization_cluster_size_skus.yaml
            - location: schemas/overlay-terraform-organization_regions.yaml
            - location: schemas/overlay-terraform-organizations.yaml
            - location: schemas/overlay-terraform-password.yaml
            - location: schemas/overlay-terraform-passwords.yaml
            - location: schemas/overlay-terraform-role.yaml
            - location: schemas/overlay-terraform-roles.yaml
            - location: schemas/overlay-terraform-user.yaml
        output: schemas/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/planetscale/dev/planet-scale-api
targets:
    planetscale:
        target: terraform
        source: PlanetScale API
