workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PlanetScale API:
        inputs:
            - location: schemas/openapi.yaml
        overlays:
            - location: schemas/overlay-terraform.yaml
            - location: schemas/overlay-terraform-bouncer.yaml
            - location: schemas/overlay-terraform-branch.yaml
            - location: schemas/overlay-terraform-database.yaml
            - location: schemas/overlay-terraform-databases.yaml
            - location: schemas/overlay-terraform-keyspace.yaml
            - location: schemas/overlay-terraform-organization.yaml
            - location: schemas/overlay-terraform-organizations.yaml
        output: schemas/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-onboarding/onboarding/planet-scale-api
targets:
    planetscale:
        target: terraform
        source: PlanetScale API
