workflowVersion: 1.0.0
speakeasyVersion: 1.680.3
sources:
    PlanetScale API:
        inputs:
            - location: schemas/openapi.yaml
        overlays:
            - location: schemas/overlay-terraform.yaml

            - location: schemas/overlay-terraform-branches.yaml
            - location: schemas/overlay-terraform-postgres-branch.yaml
            - location: schemas/overlay-terraform-vitess-branch.yaml

            - location: schemas/overlay-terraform-database_vitess.yaml
            - location: schemas/overlay-terraform-database_postgres.yaml
            - location: schemas/overlay-terraform-databases.yaml
            - location: schemas/overlay-terraform-organization.yaml
            - location: schemas/overlay-terraform-organizations.yaml
            - location: schemas/overlay-terraform-postgres-branch-role.yaml
            - location: schemas/overlay-terraform-postgres-branch-roles.yaml
            - location: schemas/overlay-terraform-user.yaml
            - location: schemas/overlay-terraform-vitess-branch-password.yaml
            - location: schemas/overlay-terraform-vitess-branch-passwords.yaml

            - location: schemas/overlay-terraform-cleanup.yaml
        output: schemas/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/planetscale/dev/planet-scale-api
targets:
    planetscale:
        target: terraform
        source: PlanetScale API
