#!/usr/bin/env bash

set -euo pipefail

root=$(git rev-parse --show-toplevel)

function main() {
    go run ${root}/internal/cmd/codegen/*.go > ${root}/internal/client/planetscale/planetscale.go
}

main