// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/planetscale/terraform-provider-planetscale/internal/provider/types"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/models/operations"
)

func (r *BackupsDataSourceModel) RefreshFromOperationsListBackupsResponseBody(ctx context.Context, resp *operations.ListBackupsResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if r.Data == nil {
			r.Data = []tfTypes.ListBackupsData{}
		}

		for _, dataItem := range resp.Data {
			var data tfTypes.ListBackupsData

			data.Actor.AvatarURL = types.StringValue(dataItem.Actor.AvatarURL)
			data.Actor.DisplayName = types.StringValue(dataItem.Actor.DisplayName)
			data.Actor.ID = types.StringValue(dataItem.Actor.ID)
			data.BackupPolicy.CreatedAt = types.StringValue(dataItem.BackupPolicy.CreatedAt)
			data.BackupPolicy.FrequencyUnit = types.StringValue(dataItem.BackupPolicy.FrequencyUnit)
			data.BackupPolicy.FrequencyValue = types.Float64Value(dataItem.BackupPolicy.FrequencyValue)
			data.BackupPolicy.ID = types.StringValue(dataItem.BackupPolicy.ID)
			data.BackupPolicy.LastRanAt = types.StringValue(dataItem.BackupPolicy.LastRanAt)
			data.BackupPolicy.Name = types.StringValue(dataItem.BackupPolicy.Name)
			data.BackupPolicy.NextRunAt = types.StringValue(dataItem.BackupPolicy.NextRunAt)
			data.BackupPolicy.Required = types.BoolValue(dataItem.BackupPolicy.Required)
			data.BackupPolicy.RetentionUnit = types.StringValue(dataItem.BackupPolicy.RetentionUnit)
			data.BackupPolicy.RetentionValue = types.Float64Value(dataItem.BackupPolicy.RetentionValue)
			data.BackupPolicy.ScheduleDay = types.StringValue(string(dataItem.BackupPolicy.ScheduleDay))
			data.BackupPolicy.ScheduleTime = types.StringValue(dataItem.BackupPolicy.ScheduleTime)
			data.BackupPolicy.ScheduleWeek = types.StringValue(string(dataItem.BackupPolicy.ScheduleWeek))
			data.BackupPolicy.Target = types.StringValue(string(dataItem.BackupPolicy.Target))
			data.BackupPolicy.UpdatedAt = types.StringValue(dataItem.BackupPolicy.UpdatedAt)
			data.CompletedAt = types.StringValue(dataItem.CompletedAt)
			data.CreatedAt = types.StringValue(dataItem.CreatedAt)
			data.DatabaseBranch.CreatedAt = types.StringValue(dataItem.DatabaseBranch.CreatedAt)
			data.DatabaseBranch.DeletedAt = types.StringValue(dataItem.DatabaseBranch.DeletedAt)
			data.DatabaseBranch.ID = types.StringValue(dataItem.DatabaseBranch.ID)
			data.DatabaseBranch.Name = types.StringValue(dataItem.DatabaseBranch.Name)
			data.DatabaseBranch.UpdatedAt = types.StringValue(dataItem.DatabaseBranch.UpdatedAt)
			data.DeletedAt = types.StringValue(dataItem.DeletedAt)
			data.EstimatedStorageCost = types.Float64Value(dataItem.EstimatedStorageCost)
			data.ExpiresAt = types.StringValue(dataItem.ExpiresAt)
			data.ID = types.StringValue(dataItem.ID)
			data.Name = types.StringValue(dataItem.Name)
			data.Protected = types.BoolValue(dataItem.Protected)
			data.PvcSize = types.Float64Value(dataItem.PvcSize)
			data.Required = types.BoolValue(dataItem.Required)
			if data.RestoredBranches == nil {
				data.RestoredBranches = []tfTypes.ListBackupsRestoredBranch{}
			}

			for _, restoredBranchesItem := range dataItem.RestoredBranches {
				var restoredBranches tfTypes.ListBackupsRestoredBranch

				restoredBranches.CreatedAt = types.StringValue(restoredBranchesItem.CreatedAt)
				restoredBranches.DeletedAt = types.StringValue(restoredBranchesItem.DeletedAt)
				restoredBranches.ID = types.StringValue(restoredBranchesItem.ID)
				restoredBranches.Name = types.StringValue(restoredBranchesItem.Name)
				restoredBranches.UpdatedAt = types.StringValue(restoredBranchesItem.UpdatedAt)

				data.RestoredBranches = append(data.RestoredBranches, restoredBranches)
			}
			data.SchemaSnapshot.CreatedAt = types.StringValue(dataItem.SchemaSnapshot.CreatedAt)
			data.SchemaSnapshot.ID = types.StringValue(dataItem.SchemaSnapshot.ID)
			data.SchemaSnapshot.LintedAt = types.StringValue(dataItem.SchemaSnapshot.LintedAt)
			data.SchemaSnapshot.Name = types.StringValue(dataItem.SchemaSnapshot.Name)
			data.SchemaSnapshot.UpdatedAt = types.StringValue(dataItem.SchemaSnapshot.UpdatedAt)
			data.SchemaSnapshot.URL = types.StringValue(dataItem.SchemaSnapshot.URL)
			data.Size = types.Float64Value(dataItem.Size)
			data.StartedAt = types.StringValue(dataItem.StartedAt)
			data.State = types.StringValue(string(dataItem.State))
			data.UpdatedAt = types.StringValue(dataItem.UpdatedAt)

			r.Data = append(r.Data, data)
		}
	}

	return diags
}

func (r *BackupsDataSourceModel) ToOperationsListBackupsRequest(ctx context.Context) (*operations.ListBackupsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	var branch string
	branch = r.Branch.ValueString()

	all := new(bool)
	if !r.All.IsUnknown() && !r.All.IsNull() {
		*all = r.All.ValueBool()
	} else {
		all = nil
	}
	state := new(operations.QueryParamState)
	if !r.State.IsUnknown() && !r.State.IsNull() {
		*state = operations.QueryParamState(r.State.ValueString())
	} else {
		state = nil
	}
	policy := new(string)
	if !r.Policy.IsUnknown() && !r.Policy.IsNull() {
		*policy = r.Policy.ValueString()
	} else {
		policy = nil
	}
	from := new(string)
	if !r.From.IsUnknown() && !r.From.IsNull() {
		*from = r.From.ValueString()
	} else {
		from = nil
	}
	to := new(string)
	if !r.To.IsUnknown() && !r.To.IsNull() {
		*to = r.To.ValueString()
	} else {
		to = nil
	}
	runningAt := new(string)
	if !r.RunningAt.IsUnknown() && !r.RunningAt.IsNull() {
		*runningAt = r.RunningAt.ValueString()
	} else {
		runningAt = nil
	}
	production := new(bool)
	if !r.Production.IsUnknown() && !r.Production.IsNull() {
		*production = r.Production.ValueBool()
	} else {
		production = nil
	}
	out := operations.ListBackupsRequest{
		Organization: organization,
		Database:     database,
		Branch:       branch,
		All:          all,
		State:        state,
		Policy:       policy,
		From:         from,
		To:           to,
		RunningAt:    runningAt,
		Production:   production,
	}

	return &out, diags
}
