// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/models/operations"
)

func (r *NekiBackupPolicyResourceModel) RefreshFromOperationsCreateNekiBackupPolicyResponseBody(ctx context.Context, resp *operations.CreateNekiBackupPolicyResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.DisplayName = types.StringValue(resp.DisplayName)
		r.FrequencyUnit = types.StringValue(string(resp.FrequencyUnit))
		r.FrequencyValue = types.Int64Value(resp.FrequencyValue)
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.RetentionUnit = types.StringValue(string(resp.RetentionUnit))
		r.RetentionValue = types.Int64Value(resp.RetentionValue)
		r.ScheduleDay = types.Int64PointerValue(resp.ScheduleDay)
		r.ScheduleTime = types.StringValue(resp.ScheduleTime)
		r.ScheduleWeek = types.Int64PointerValue(resp.ScheduleWeek)
		r.Target = types.StringValue(string(resp.Target))
	}

	return diags
}

func (r *NekiBackupPolicyResourceModel) RefreshFromOperationsGetNekiBackupPolicyResponseBody(ctx context.Context, resp *operations.GetNekiBackupPolicyResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.DisplayName = types.StringValue(resp.DisplayName)
		r.FrequencyUnit = types.StringValue(string(resp.FrequencyUnit))
		r.FrequencyValue = types.Int64Value(resp.FrequencyValue)
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.RetentionUnit = types.StringValue(string(resp.RetentionUnit))
		r.RetentionValue = types.Int64Value(resp.RetentionValue)
		r.ScheduleDay = types.Int64PointerValue(resp.ScheduleDay)
		r.ScheduleTime = types.StringValue(resp.ScheduleTime)
		r.ScheduleWeek = types.Int64PointerValue(resp.ScheduleWeek)
		r.Target = types.StringValue(string(resp.Target))
	}

	return diags
}

func (r *NekiBackupPolicyResourceModel) RefreshFromOperationsUpdateNekiBackupPolicyResponseBody(ctx context.Context, resp *operations.UpdateNekiBackupPolicyResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.DisplayName = types.StringValue(resp.DisplayName)
		r.FrequencyUnit = types.StringValue(string(resp.FrequencyUnit))
		r.FrequencyValue = types.Int64Value(resp.FrequencyValue)
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
		r.RetentionUnit = types.StringValue(string(resp.RetentionUnit))
		r.RetentionValue = types.Int64Value(resp.RetentionValue)
		r.ScheduleDay = types.Int64PointerValue(resp.ScheduleDay)
		r.ScheduleTime = types.StringValue(resp.ScheduleTime)
		r.ScheduleWeek = types.Int64PointerValue(resp.ScheduleWeek)
		r.Target = types.StringValue(string(resp.Target))
	}

	return diags
}

func (r *NekiBackupPolicyResourceModel) ToOperationsCreateNekiBackupPolicyRequest(ctx context.Context) (*operations.CreateNekiBackupPolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	body, bodyDiags := r.ToOperationsCreateNekiBackupPolicyRequestBody(ctx)
	diags.Append(bodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreateNekiBackupPolicyRequest{
		Organization: organization,
		Database:     database,
		Body:         body,
	}

	return &out, diags
}

func (r *NekiBackupPolicyResourceModel) ToOperationsCreateNekiBackupPolicyRequestBody(ctx context.Context) (*operations.CreateNekiBackupPolicyRequestBody, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	target := new(operations.CreateNekiBackupPolicyTargetRequest)
	if !r.Target.IsUnknown() && !r.Target.IsNull() {
		*target = operations.CreateNekiBackupPolicyTargetRequest(r.Target.ValueString())
	} else {
		target = nil
	}
	retentionValue := new(int64)
	if !r.RetentionValue.IsUnknown() && !r.RetentionValue.IsNull() {
		*retentionValue = r.RetentionValue.ValueInt64()
	} else {
		retentionValue = nil
	}
	retentionUnit := new(operations.CreateNekiBackupPolicyRetentionUnit)
	if !r.RetentionUnit.IsUnknown() && !r.RetentionUnit.IsNull() {
		*retentionUnit = operations.CreateNekiBackupPolicyRetentionUnit(r.RetentionUnit.ValueString())
	} else {
		retentionUnit = nil
	}
	frequencyValue := new(int64)
	if !r.FrequencyValue.IsUnknown() && !r.FrequencyValue.IsNull() {
		*frequencyValue = r.FrequencyValue.ValueInt64()
	} else {
		frequencyValue = nil
	}
	frequencyUnit := new(operations.CreateNekiBackupPolicyFrequencyUnit)
	if !r.FrequencyUnit.IsUnknown() && !r.FrequencyUnit.IsNull() {
		*frequencyUnit = operations.CreateNekiBackupPolicyFrequencyUnit(r.FrequencyUnit.ValueString())
	} else {
		frequencyUnit = nil
	}
	scheduleTime := new(string)
	if !r.ScheduleTime.IsUnknown() && !r.ScheduleTime.IsNull() {
		*scheduleTime = r.ScheduleTime.ValueString()
	} else {
		scheduleTime = nil
	}
	scheduleDay := new(int64)
	if !r.ScheduleDay.IsUnknown() && !r.ScheduleDay.IsNull() {
		*scheduleDay = r.ScheduleDay.ValueInt64()
	} else {
		scheduleDay = nil
	}
	scheduleWeek := new(int64)
	if !r.ScheduleWeek.IsUnknown() && !r.ScheduleWeek.IsNull() {
		*scheduleWeek = r.ScheduleWeek.ValueInt64()
	} else {
		scheduleWeek = nil
	}
	out := operations.CreateNekiBackupPolicyRequestBody{
		Name:           name,
		Target:         target,
		RetentionValue: retentionValue,
		RetentionUnit:  retentionUnit,
		FrequencyValue: frequencyValue,
		FrequencyUnit:  frequencyUnit,
		ScheduleTime:   scheduleTime,
		ScheduleDay:    scheduleDay,
		ScheduleWeek:   scheduleWeek,
	}

	return &out, diags
}

func (r *NekiBackupPolicyResourceModel) ToOperationsDeleteNekiBackupPolicyRequest(ctx context.Context) (*operations.DeleteNekiBackupPolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	out := operations.DeleteNekiBackupPolicyRequest{
		ID:           id,
		Organization: organization,
		Database:     database,
	}

	return &out, diags
}

func (r *NekiBackupPolicyResourceModel) ToOperationsGetNekiBackupPolicyRequest(ctx context.Context) (*operations.GetNekiBackupPolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	out := operations.GetNekiBackupPolicyRequest{
		ID:           id,
		Organization: organization,
		Database:     database,
	}

	return &out, diags
}

func (r *NekiBackupPolicyResourceModel) ToOperationsUpdateNekiBackupPolicyRequest(ctx context.Context) (*operations.UpdateNekiBackupPolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	body, bodyDiags := r.ToOperationsUpdateNekiBackupPolicyRequestBody(ctx)
	diags.Append(bodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateNekiBackupPolicyRequest{
		ID:           id,
		Organization: organization,
		Database:     database,
		Body:         body,
	}

	return &out, diags
}

func (r *NekiBackupPolicyResourceModel) ToOperationsUpdateNekiBackupPolicyRequestBody(ctx context.Context) (*operations.UpdateNekiBackupPolicyRequestBody, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	target := new(operations.UpdateNekiBackupPolicyTargetRequest)
	if !r.Target.IsUnknown() && !r.Target.IsNull() {
		*target = operations.UpdateNekiBackupPolicyTargetRequest(r.Target.ValueString())
	} else {
		target = nil
	}
	retentionValue := new(int64)
	if !r.RetentionValue.IsUnknown() && !r.RetentionValue.IsNull() {
		*retentionValue = r.RetentionValue.ValueInt64()
	} else {
		retentionValue = nil
	}
	retentionUnit := new(operations.UpdateNekiBackupPolicyRetentionUnit)
	if !r.RetentionUnit.IsUnknown() && !r.RetentionUnit.IsNull() {
		*retentionUnit = operations.UpdateNekiBackupPolicyRetentionUnit(r.RetentionUnit.ValueString())
	} else {
		retentionUnit = nil
	}
	frequencyValue := new(int64)
	if !r.FrequencyValue.IsUnknown() && !r.FrequencyValue.IsNull() {
		*frequencyValue = r.FrequencyValue.ValueInt64()
	} else {
		frequencyValue = nil
	}
	frequencyUnit := new(operations.UpdateNekiBackupPolicyFrequencyUnit)
	if !r.FrequencyUnit.IsUnknown() && !r.FrequencyUnit.IsNull() {
		*frequencyUnit = operations.UpdateNekiBackupPolicyFrequencyUnit(r.FrequencyUnit.ValueString())
	} else {
		frequencyUnit = nil
	}
	scheduleTime := new(string)
	if !r.ScheduleTime.IsUnknown() && !r.ScheduleTime.IsNull() {
		*scheduleTime = r.ScheduleTime.ValueString()
	} else {
		scheduleTime = nil
	}
	scheduleDay := new(int64)
	if !r.ScheduleDay.IsUnknown() && !r.ScheduleDay.IsNull() {
		*scheduleDay = r.ScheduleDay.ValueInt64()
	} else {
		scheduleDay = nil
	}
	scheduleWeek := new(int64)
	if !r.ScheduleWeek.IsUnknown() && !r.ScheduleWeek.IsNull() {
		*scheduleWeek = r.ScheduleWeek.ValueInt64()
	} else {
		scheduleWeek = nil
	}
	out := operations.UpdateNekiBackupPolicyRequestBody{
		Name:           name,
		Target:         target,
		RetentionValue: retentionValue,
		RetentionUnit:  retentionUnit,
		FrequencyValue: frequencyValue,
		FrequencyUnit:  frequencyUnit,
		ScheduleTime:   scheduleTime,
		ScheduleDay:    scheduleDay,
		ScheduleWeek:   scheduleWeek,
	}

	return &out, diags
}
