// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/planetscale/terraform-provider-planetscale/internal/provider/types"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &OrganizationRegionsDataSource{}
var _ datasource.DataSourceWithConfigure = &OrganizationRegionsDataSource{}

func NewOrganizationRegionsDataSource() datasource.DataSource {
	return &OrganizationRegionsDataSource{}
}

// OrganizationRegionsDataSource is the data source implementation.
type OrganizationRegionsDataSource struct {
	// Provider configured SDK client.
	client *sdk.Planetscale
}

// OrganizationRegionsDataSourceModel describes the data model.
type OrganizationRegionsDataSourceModel struct {
	Data []tfTypes.ListRegionsForOrganizationData `tfsdk:"data"`
	Name types.String                             `tfsdk:"name"`
}

// Metadata returns the data source type name.
func (r *OrganizationRegionsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_regions"
}

// Schema defines the schema for the data source.
func (r *OrganizationRegionsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "OrganizationRegions DataSource",

		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"current_default": schema.BoolAttribute{
							Computed:    true,
							Description: `True if the region is the default for new branch creation`,
						},
						"display_name": schema.StringAttribute{
							Computed:    true,
							Description: `Name of the region`,
						},
						"enabled": schema.BoolAttribute{
							Computed:    true,
							Description: `Whether or not the region is currently active`,
						},
						"id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the region`,
						},
						"location": schema.StringAttribute{
							Computed:    true,
							Description: `Location of the region`,
						},
						"provider": schema.StringAttribute{
							Computed:    true,
							Description: `Provider for the region (ex. AWS)`,
						},
						"public_ip_addresses": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
							Description: `Public IP addresses for the region`,
						},
						"slug": schema.StringAttribute{
							Computed:    true,
							Description: `The slug of the region`,
						},
					},
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: `The name of the organization`,
			},
		},
	}
}

func (r *OrganizationRegionsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Planetscale)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Planetscale, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *OrganizationRegionsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *OrganizationRegionsDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsListRegionsForOrganizationRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Organizations.ListRegionsForOrganization(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Object != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.Data = nil
	resp.Diagnostics.Append(data.RefreshFromOperationsListRegionsForOrganizationResponseBody(ctx, res.Object)...)

	if resp.Diagnostics.HasError() {
		return
	}
	for {
		var err error

		res, err = res.Next()

		if err != nil {
			resp.Diagnostics.AddError(fmt.Sprintf("failed to retrieve next page of results: %v", err), debugResponse(res.RawResponse))
			return
		}

		if res == nil {
			break
		}

		resp.Diagnostics.Append(data.RefreshFromOperationsListRegionsForOrganizationResponseBody(ctx, res.Object)...)

		if resp.Diagnostics.HasError() {
			return
		}
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
