// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/models/operations"
)

func (r *PostgresReadOnlyReplicaDataSourceModel) RefreshFromOperationsGetDedicatedReadReplicaResponseBody(ctx context.Context, resp *operations.GetDedicatedReadReplicaResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AccessHostURL = types.StringValue(resp.AccessHostURL)
		r.ClusterSize = types.StringValue(resp.ClusterSize)
		r.Name = types.StringValue(resp.Name)
		r.PrivateAccessHostURL = types.StringValue(resp.PrivateAccessHostURL)
		r.PrivateConnectionServiceName = types.StringPointerValue(resp.PrivateConnectionServiceName)
		r.Region = types.StringValue(resp.Region)
		r.Replicas = types.Int64Value(resp.Replicas)
	}

	return diags
}

func (r *PostgresReadOnlyReplicaDataSourceModel) ToOperationsGetDedicatedReadReplicaRequest(ctx context.Context) (*operations.GetDedicatedReadReplicaRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	var branch string
	branch = r.Branch.ValueString()

	var dedicatedReadReplica string
	dedicatedReadReplica = r.Name.ValueString()

	out := operations.GetDedicatedReadReplicaRequest{
		Organization:         organization,
		Database:             database,
		Branch:               branch,
		DedicatedReadReplica: dedicatedReadReplica,
	}

	return &out, diags
}
