// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/planetscale/terraform-provider-planetscale/internal/provider/types"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &VitessBranchDataSource{}
var _ datasource.DataSourceWithConfigure = &VitessBranchDataSource{}

func NewVitessBranchDataSource() datasource.DataSource {
	return &VitessBranchDataSource{}
}

// VitessBranchDataSource is the data source implementation.
type VitessBranchDataSource struct {
	// Provider configured SDK client.
	client *sdk.PlanetScale
}

// VitessBranchDataSourceModel describes the data model.
type VitessBranchDataSourceModel struct {
	Actor                      *tfTypes.GetVitessBranchActor      `tfsdk:"actor"`
	ClusterSize                types.String                       `tfsdk:"cluster_size"`
	Database                   types.String                       `tfsdk:"database"`
	DeletionProtected          types.Bool                         `tfsdk:"deletion_protected"`
	HTMLURL                    types.String                       `tfsdk:"html_url"`
	ID                         types.String                       `tfsdk:"id"`
	KeyspaceCount              types.Int64                        `tfsdk:"keyspace_count"`
	MysqlAddress               types.String                       `tfsdk:"mysql_address"`
	MysqlEdgeAddress           types.String                       `tfsdk:"mysql_edge_address"`
	Name                       types.String                       `tfsdk:"name"`
	Organization               types.String                       `tfsdk:"organization"`
	ParentBranch               types.String                       `tfsdk:"parent_branch"`
	Ready                      types.Bool                         `tfsdk:"ready"`
	RegionData                 *tfTypes.GetVitessBranchRegionData `tfsdk:"region_data"`
	SafeMigrations             types.Bool                         `tfsdk:"safe_migrations"`
	State                      types.String                       `tfsdk:"state"`
	URL                        types.String                       `tfsdk:"url"`
	VtgateAutoscaling          types.Bool                         `tfsdk:"vtgate_autoscaling"`
	VtgateCount                types.Int64                        `tfsdk:"vtgate_count"`
	VtgateMaxCount             types.Int64                        `tfsdk:"vtgate_max_count"`
	VtgateSize                 types.String                       `tfsdk:"vtgate_size"`
	VtgateTargetCPUUtilization types.Int64                        `tfsdk:"vtgate_target_cpu_utilization"`
}

// Metadata returns the data source type name.
func (r *VitessBranchDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vitess_branch"
}

// Schema defines the schema for the data source.
func (r *VitessBranchDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "VitessBranch DataSource",

		Attributes: map[string]schema.Attribute{
			"actor": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:    true,
						Description: `The ID of the actor`,
					},
				},
			},
			"cluster_size": schema.StringAttribute{
				Computed:    true,
				Description: `The SKU representing the branch's cluster size`,
			},
			"database": schema.StringAttribute{
				Required:    true,
				Description: `Database name slug from ` + "`" + `list_databases` + "`" + `. Example: ` + "`" + `app-db` + "`" + `.`,
			},
			"deletion_protected": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether deletion protection is enabled for the branch`,
			},
			"html_url": schema.StringAttribute{
				Computed:    true,
				Description: `Planetscale app URL for the branch`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `The ID of the branch`,
			},
			"keyspace_count": schema.Int64Attribute{
				Computed:    true,
				Description: `The number of keyspaces in the branch`,
			},
			"mysql_address": schema.StringAttribute{
				Computed:    true,
				Description: `The MySQL address for the branch`,
			},
			"mysql_edge_address": schema.StringAttribute{
				Computed:    true,
				Description: `The address of the MySQL provider for the branch`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `The name of the branch`,
			},
			"organization": schema.StringAttribute{
				Required:    true,
				Description: `Organization name slug from ` + "`" + `list_organizations` + "`" + `. Example: ` + "`" + `acme` + "`" + `.`,
			},
			"parent_branch": schema.StringAttribute{
				Computed:    true,
				Description: `The name of the parent branch from which the branch was created`,
			},
			"ready": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether or not the branch is ready to serve queries`,
			},
			"region_data": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:    true,
						Description: `The ID of the region`,
					},
					"mysql_supported": schema.BoolAttribute{
						Computed:    true,
						Description: `Whether the region supports MySQL/Vitess databases`,
					},
					"postgresql_supported": schema.BoolAttribute{
						Computed:    true,
						Description: `Whether the region supports PostgreSQL databases`,
					},
				},
			},
			"safe_migrations": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether or not the branch has safe migrations enabled`,
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: `The current state of the branch`,
			},
			"url": schema.StringAttribute{
				Computed:    true,
				Description: `Planetscale API URL for the branch`,
			},
			"vtgate_autoscaling": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether VTGate autoscaling is enabled`,
			},
			"vtgate_count": schema.Int64Attribute{
				Computed:    true,
				Description: `The number of vtgate instances in the branch`,
			},
			"vtgate_max_count": schema.Int64Attribute{
				Computed:    true,
				Description: `The maximum number of VTGate instances when autoscaling is enabled`,
			},
			"vtgate_size": schema.StringAttribute{
				Computed:    true,
				Description: `The public SKU representing the VTGate size`,
			},
			"vtgate_target_cpu_utilization": schema.Int64Attribute{
				Computed:    true,
				Description: `The target CPU utilization for VTGate autoscaling`,
			},
		},
	}
}

func (r *VitessBranchDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.PlanetScale)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.PlanetScale, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *VitessBranchDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *VitessBranchDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetVitessBranchRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.DatabaseBranches.GetVitessBranch(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Object != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromOperationsGetVitessBranchResponseBody(ctx, res.Object)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
