// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/planetscale/terraform-provider-planetscale/internal/provider/types"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk/models/operations"
)

func (r *VitessKeyspaceDataSourceModel) RefreshFromOperationsGetKeyspaceResponseBody(ctx context.Context, resp *operations.GetKeyspaceResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ClusterDisplayName = types.StringValue(resp.ClusterDisplayName)
		r.ClusterSize = types.StringValue(resp.ClusterSize)
		r.ConfigChangeInProgress = types.BoolValue(resp.ConfigChangeInProgress)
		r.CreatedAt = types.StringValue(resp.CreatedAt)
		r.ExtraReplicas = types.Int64Value(resp.ExtraReplicas)
		r.ID = types.StringValue(resp.ID)
		r.Imported = types.BoolValue(resp.Imported)
		r.IsDefault = types.BoolValue(resp.IsDefault)
		r.Metal = types.BoolValue(resp.Metal)
		r.Name = types.StringValue(resp.Name)
		r.NodeTTLStrategy = types.StringValue(string(resp.NodeTTLStrategy))
		r.Ready = types.BoolValue(resp.Ready)
		r.Replicas = types.Int64Value(resp.Replicas)
		r.ReplicationDurabilityConstraints = &tfTypes.GetKeyspaceReplicationDurabilityConstraints{}
		if resp.ReplicationDurabilityConstraints.Strategy != nil {
			r.ReplicationDurabilityConstraints.Strategy = types.StringValue(string(*resp.ReplicationDurabilityConstraints.Strategy))
		} else {
			r.ReplicationDurabilityConstraints.Strategy = types.StringNull()
		}
		r.ResizeInProgress = types.BoolValue(resp.ResizeInProgress)
		r.ResizePending = types.BoolValue(resp.ResizePending)
		r.Resizing = types.BoolValue(resp.Resizing)
		r.Sharded = types.BoolValue(resp.Sharded)
		r.Shards = types.Int64Value(resp.Shards)
		r.UpdatedAt = types.StringValue(resp.UpdatedAt)
		r.VectorPoolAllocation = types.Float64PointerValue(resp.VectorPoolAllocation)
		r.VreplicationFlags = &tfTypes.GetKeyspaceVreplicationFlags{}
		r.VreplicationFlags.AllowNoBlobBinlogRowImage = types.BoolValue(resp.VreplicationFlags.AllowNoBlobBinlogRowImage)
		r.VreplicationFlags.OptimizeInserts = types.BoolValue(resp.VreplicationFlags.OptimizeInserts)
		r.VreplicationFlags.VplayerBatching = types.BoolValue(resp.VreplicationFlags.VplayerBatching)
	}

	return diags
}

func (r *VitessKeyspaceDataSourceModel) ToOperationsGetKeyspaceRequest(ctx context.Context) (*operations.GetKeyspaceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var organization string
	organization = r.Organization.ValueString()

	var database string
	database = r.Database.ValueString()

	var branch string
	branch = r.Branch.ValueString()

	var keyspace string
	keyspace = r.Name.ValueString()

	out := operations.GetKeyspaceRequest{
		Organization: organization,
		Database:     database,
		Branch:       branch,
		Keyspace:     keyspace,
	}

	return &out, diags
}
