// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/planetscale/terraform-provider-planetscale/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &WebhookDataSource{}
var _ datasource.DataSourceWithConfigure = &WebhookDataSource{}

func NewWebhookDataSource() datasource.DataSource {
	return &WebhookDataSource{}
}

// WebhookDataSource is the data source implementation.
type WebhookDataSource struct {
	// Provider configured SDK client.
	client *sdk.Planetscale
}

// WebhookDataSourceModel describes the data model.
type WebhookDataSourceModel struct {
	CreatedAt       types.String   `tfsdk:"created_at"`
	Database        types.String   `tfsdk:"database"`
	Enabled         types.Bool     `tfsdk:"enabled"`
	Events          []types.String `tfsdk:"events"`
	ID              types.String   `tfsdk:"id"`
	LastSentAt      types.String   `tfsdk:"last_sent_at"`
	LastSentResult  types.String   `tfsdk:"last_sent_result"`
	LastSentSuccess types.Bool     `tfsdk:"last_sent_success"`
	Organization    types.String   `tfsdk:"organization"`
	Secret          types.String   `tfsdk:"secret"`
	UpdatedAt       types.String   `tfsdk:"updated_at"`
	URL             types.String   `tfsdk:"url"`
}

// Metadata returns the data source type name.
func (r *WebhookDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_webhook"
}

// Schema defines the schema for the data source.
func (r *WebhookDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Webhook DataSource",

		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `When the webhook was created`,
			},
			"database": schema.StringAttribute{
				Required:    true,
				Description: `The name of the database`,
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether the webhook is enabled`,
			},
			"events": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `The events this webhook subscribes to`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `The ID of the webhook`,
			},
			"last_sent_at": schema.StringAttribute{
				Computed:    true,
				Description: `When the last event was sent`,
			},
			"last_sent_result": schema.StringAttribute{
				Computed:    true,
				Description: `The last result sent by the webhook`,
			},
			"last_sent_success": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether the last sent was successful`,
			},
			"organization": schema.StringAttribute{
				Required:    true,
				Description: `The name of the organization`,
			},
			"secret": schema.StringAttribute{
				Computed:    true,
				Description: `The secret used to sign the webhook payloads`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `When the webhook was updated`,
			},
			"url": schema.StringAttribute{
				Computed:    true,
				Description: `The URL the webhook will send events to`,
			},
		},
	}
}

func (r *WebhookDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Planetscale)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Planetscale, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *WebhookDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *WebhookDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetWebhookRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Webhooks.GetWebhook(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Object != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromOperationsGetWebhookResponseBody(ctx, res.Object)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
