// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GetOrganizationTeamMember struct {
	AvatarURL               types.String                           `tfsdk:"avatar_url"`
	CreatedAt               types.String                           `tfsdk:"created_at"`
	DefaultOrganization     GetOrganizationTeamDefaultOrganization `tfsdk:"default_organization"`
	DirectoryManaged        types.Bool                             `tfsdk:"directory_managed"`
	DisplayName             types.String                           `tfsdk:"display_name"`
	Email                   types.String                           `tfsdk:"email"`
	EmailVerified           types.Bool                             `tfsdk:"email_verified"`
	ID                      types.String                           `tfsdk:"id"`
	Managed                 types.Bool                             `tfsdk:"managed"`
	Name                    types.String                           `tfsdk:"name"`
	Sso                     types.Bool                             `tfsdk:"sso"`
	TwoFactorAuthConfigured types.Bool                             `tfsdk:"two_factor_auth_configured"`
	UpdatedAt               types.String                           `tfsdk:"updated_at"`
}
