// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ListOrganizationsData struct {
	BillingEmail        types.String                    `tfsdk:"billing_email"`
	CreatedAt           types.String                    `tfsdk:"created_at"`
	DatabaseCount       types.Float64                   `tfsdk:"database_count"`
	Features            map[string]jsontypes.Normalized `tfsdk:"features"`
	HasCard             types.Bool                      `tfsdk:"has_card"`
	HasPastDueInvoices  types.Bool                      `tfsdk:"has_past_due_invoices"`
	ID                  types.String                    `tfsdk:"id"`
	IdpManagedRoles     types.Bool                      `tfsdk:"idp_managed_roles"`
	InvoiceBudgetAmount types.Float64                   `tfsdk:"invoice_budget_amount"`
	KeyspaceShardLimit  types.Float64                   `tfsdk:"keyspace_shard_limit"`
	ManagedTenancy      types.Bool                      `tfsdk:"managed_tenancy"`
	Name                types.String                    `tfsdk:"name"`
	PaymentInfoRequired types.Bool                      `tfsdk:"payment_info_required"`
	Plan                types.String                    `tfsdk:"plan"`
	SingleTenancy       types.Bool                      `tfsdk:"single_tenancy"`
	Sso                 types.Bool                      `tfsdk:"sso"`
	SsoDirectory        types.Bool                      `tfsdk:"sso_directory"`
	SsoPortalURL        types.String                    `tfsdk:"sso_portal_url"`
	UpdatedAt           types.String                    `tfsdk:"updated_at"`
	ValidBillingInfo    types.Bool                      `tfsdk:"valid_billing_info"`
}
