// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ListNekiRolesData struct {
	AccessHostURL                types.String   `tfsdk:"access_host_url"`
	ExpiresAt                    types.String   `tfsdk:"expires_at"`
	ID                           types.String   `tfsdk:"id"`
	InheritedRoles               []types.String `tfsdk:"inherited_roles"`
	Name                         types.String   `tfsdk:"name"`
	PrivateAccessHostURL         types.String   `tfsdk:"private_access_host_url"`
	PrivateConnectionServiceName types.String   `tfsdk:"private_connection_service_name"`
	TTL                          types.Int64    `tfsdk:"ttl"`
	Username                     types.String   `tfsdk:"username"`
	WithReplication              types.Bool     `tfsdk:"with_replication"`
}
