// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e646e23435b0

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ListVitessBranchBackupsDatabaseBranch struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}
