// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ListDatabasesData struct {
	AllowDataBranching                types.Bool              `tfsdk:"allow_data_branching"`
	AtBackupRestoreBranchesLimit      types.Bool              `tfsdk:"at_backup_restore_branches_limit"`
	AtDevelopmentBranchUsageLimit     types.Bool              `tfsdk:"at_development_branch_usage_limit"`
	AutomaticMigrations               types.Bool              `tfsdk:"automatic_migrations"`
	BranchesCount                     types.Float64           `tfsdk:"branches_count"`
	BranchesURL                       types.String            `tfsdk:"branches_url"`
	CreatedAt                         types.String            `tfsdk:"created_at"`
	DataImport                        ListDatabasesDataImport `tfsdk:"data_import"`
	DefaultBranch                     types.String            `tfsdk:"default_branch"`
	DefaultBranchReadOnlyRegionsCount types.Float64           `tfsdk:"default_branch_read_only_regions_count"`
	DefaultBranchShardCount           types.Float64           `tfsdk:"default_branch_shard_count"`
	DefaultBranchTableCount           types.Float64           `tfsdk:"default_branch_table_count"`
	DevelopmentBranchesCount          types.Float64           `tfsdk:"development_branches_count"`
	ForeignKeysEnabled                types.Bool              `tfsdk:"foreign_keys_enabled"`
	HTMLURL                           types.String            `tfsdk:"html_url"`
	ID                                types.String            `tfsdk:"id"`
	InsightsEnabled                   types.Bool              `tfsdk:"insights_enabled"`
	InsightsRawQueries                types.Bool              `tfsdk:"insights_raw_queries"`
	IssuesCount                       types.Float64           `tfsdk:"issues_count"`
	Kind                              types.String            `tfsdk:"kind"`
	MigrationFramework                types.String            `tfsdk:"migration_framework"`
	MigrationTableName                types.String            `tfsdk:"migration_table_name"`
	MultipleAdminsRequiredForDeletion types.Bool              `tfsdk:"multiple_admins_required_for_deletion"`
	Name                              types.String            `tfsdk:"name"`
	OpenSchemaRecommendationsCount    types.Float64           `tfsdk:"open_schema_recommendations_count"`
	Plan                              types.String            `tfsdk:"plan"`
	ProductionBranchWebConsole        types.Bool              `tfsdk:"production_branch_web_console"`
	ProductionBranchesCount           types.Float64           `tfsdk:"production_branches_count"`
	Ready                             types.Bool              `tfsdk:"ready"`
	Region                            ListDatabasesRegion     `tfsdk:"region"`
	RequireApprovalForDeploy          types.Bool              `tfsdk:"require_approval_for_deploy"`
	ResizeQueued                      types.Bool              `tfsdk:"resize_queued"`
	Resizing                          types.Bool              `tfsdk:"resizing"`
	RestrictBranchRegion              types.Bool              `tfsdk:"restrict_branch_region"`
	SchemaLastUpdatedAt               types.String            `tfsdk:"schema_last_updated_at"`
	Sharded                           types.Bool              `tfsdk:"sharded"`
	State                             types.String            `tfsdk:"state"`
	UpdatedAt                         types.String            `tfsdk:"updated_at"`
	URL                               types.String            `tfsdk:"url"`
}
