name: validate renovate.json

on:
  pull_request:

permissions:
  contents: read

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: docker://ghcr.io/renovatebot/renovate:44.13.1@sha256:3e4149122921d530218a4ca809c59636faa668b330e4c9ea7f9ee1e20ea505dd
        with:
          entrypoint: renovate-config-validator
          args: --no-global renovate.json5
